package com.sjzu.edu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _LpgMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		//下面的是阿里云LPG实时获取的数据
		arp.addMapping("t_iot_sync_rds_records", "id", IotSyncRdsRecords.class);
		arp.addMapping("t_iot_sync_rds_records_v2", "id", IotSyncRdsRecordsV2.class);
		arp.addMapping("t_iot_sync_records", "id", IotSyncRecords.class);
		arp.addMapping("t_iot_sync_records_v2", "id", IotSyncRecordsV2.class);
		//上面的是阿里云LPG实时获取的数据
	}
}


