package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAlgModelSdk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlgModelSdk extends BaseAlgModelSdk<AlgModelSdk> {
	
}

