package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAlgModelSdkEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlgModelSdkEvent extends BaseAlgModelSdkEvent<AlgModelSdkEvent> {
	
}

