package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAlgModelSdkParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlgModelSdkParam extends BaseAlgModelSdkParam<AlgModelSdkParam> {
	
}

