package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAppManage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppManage extends BaseAppManage<AppManage> {
	
}

