package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingWaitRecordHis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingWaitRecordHis extends BaseAutoGasFillingWaitRecordHis<AutoGasFillingWaitRecordHis> {
	
}

