package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingWaitQueue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingWaitQueue extends BaseAutoGasFillingWaitQueue<AutoGasFillingWaitQueue> {
	
}

