package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingRecordCheck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingRecordCheck extends BaseAutoGasFillingRecordCheck<AutoGasFillingRecordCheck> {
	
}

