package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingRecord extends BaseAutoGasFillingRecord<AutoGasFillingRecord> {
	
}

