package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoAnnualInspection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoAnnualInspection extends BaseAutoAnnualInspection<AutoAnnualInspection> {
	
}

