package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingStopRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingStopRecord extends BaseAutoGasFillingStopRecord<AutoGasFillingStopRecord> {
	
}

