package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingRecordPhotos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingRecordPhotos extends BaseAutoGasFillingRecordPhotos<AutoGasFillingRecordPhotos> {
	
}

