package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingImage extends BaseAutoGasFillingImage<AutoGasFillingImage> {
	
}

