package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseAutoGasFillingWaitRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoGasFillingWaitRecord extends BaseAutoGasFillingWaitRecord<AutoGasFillingWaitRecord> {
	
}

