package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBangdingren;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bangdingren extends BaseBangdingren<Bangdingren> {
	
}

