package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBasBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasBill extends BaseBasBill<BasBill> {
	
}

