package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBaseProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseProperty extends BaseBaseProperty<BaseProperty> {
	
}

