package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBasshexiangtouinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basshexiangtouinfo extends BaseBasshexiangtouinfo<Basshexiangtouinfo> {
	
}

