package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBillInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BillInfo extends BaseBillInfo<BillInfo> {
	
}

