package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBottlePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BottlePerson extends BaseBottlePerson<BottlePerson> {
	
}

