package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseCompanyCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseCompanyCopy1 extends BaseBseCompanyCopy1<BseCompanyCopy1> {
	
}

