package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseCompany extends BaseBseCompany<BseCompany> {
	
}

