package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseData extends BaseBseData<BseData> {
	
}

