package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseEquipOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseEquipOperation extends BaseBseEquipOperation<BseEquipOperation> {
	
}

