package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseEquipmentCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseEquipmentCopy1 extends BaseBseEquipmentCopy1<BseEquipmentCopy1> {
	
}

