package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseEquipment extends BaseBseEquipment<BseEquipment> {
	
}

