package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseFittOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseFittOperate extends BaseBseFittOperate<BseFittOperate> {
	
}

