package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseFitting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseFitting extends BaseBseFitting<BseFitting> {
	
}

