package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseGun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseGun extends BaseBseGun<BseGun> {
	
}

