package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseInterval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseInterval extends BaseBseInterval<BseInterval> {
	
}

