package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseMaintenanceCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseMaintenanceCopy1 extends BaseBseMaintenanceCopy1<BseMaintenanceCopy1> {
	
}

