package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseMaintenance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseMaintenance extends BaseBseMaintenance<BseMaintenance> {
	
}

