package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseBseXiaohezi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BseXiaohezi extends BaseBseXiaohezi<BseXiaohezi> {
	
}

