package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	
}

