package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseCustromer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Custromer extends BaseCustromer<Custromer> {
	
}

