package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseCylinder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cylinder extends BaseCylinder<Cylinder> {
	
}

