package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDetectCamera;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DetectCamera extends BaseDetectCamera<DetectCamera> {
	
}

