package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDetectSnapshot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DetectSnapshot extends BaseDetectSnapshot<DetectSnapshot> {
	
}

