package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDetectRaspi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DetectRaspi extends BaseDetectRaspi<DetectRaspi> {
	
}

