package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDeviceRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceRecords extends BaseDeviceRecords<DeviceRecords> {
	
}

