package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDeviceipaddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deviceipaddress extends BaseDeviceipaddress<Deviceipaddress> {
	
}

