package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDeviceCtrlCloudRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceCtrlCloudRecord extends BaseDeviceCtrlCloudRecord<DeviceCtrlCloudRecord> {
	
}

