package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDianzicheng;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dianzicheng extends BaseDianzicheng<Dianzicheng> {
	
}

