package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDianzibiaoqian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dianzibiaoqian extends BaseDianzibiaoqian<Dianzibiaoqian> {
	
}

