package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDowncar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Downcar extends BaseDowncar<Downcar> {
	
}

