package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDrivercar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drivercar extends BaseDrivercar<Drivercar> {
	
}

