package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseDrivergpsinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drivergpsinfo extends BaseDrivergpsinfo<Drivergpsinfo> {
	
}

