package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseEnterStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnterStation extends BaseEnterStation<EnterStation> {
	
}

