package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseFillRecordCheck1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FillRecordCheck1 extends BaseFillRecordCheck1<FillRecordCheck1> {
	
}

