package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseFillRecordCheck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FillRecordCheck extends BaseFillRecordCheck<FillRecordCheck> {
	
}

