package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasBotMedium;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasBotMedium extends BaseGasBotMedium<GasBotMedium> {
	
}

