package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasBottle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasBottle extends BaseGasBottle<GasBottle> {
	
}

