package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasBotCycleRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasBotCycleRecord extends BaseGasBotCycleRecord<GasBotCycleRecord> {
	
}

