package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasbottleinstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Gasbottleinstore extends BaseGasbottleinstore<Gasbottleinstore> {
	
}

