package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasDocs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasDocs extends BaseGasDocs<GasDocs> {
	
}

