package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasFile extends BaseGasFile<GasFile> {
	
}

