package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasFileCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasFileCopy1 extends BaseGasFileCopy1<GasFileCopy1> {
	
}

