package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasFile123;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasFile123 extends BaseGasFile123<GasFile123> {
	
}

