package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationStaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationStaff extends BaseGasStationStaff<GasStationStaff> {
	
}

