package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationPlatePrefix;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationPlatePrefix extends BaseGasStationPlatePrefix<GasStationPlatePrefix> {
	
}

