package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStaffWorkCheck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStaffWorkCheck extends BaseGasStaffWorkCheck<GasStaffWorkCheck> {
	
}

