package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStaffUserGov;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStaffUserGov extends BaseGasStaffUserGov<GasStaffUserGov> {
	
}

