package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationEnv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationEnv extends BaseGasStationEnv<GasStationEnv> {
	
}

