package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationGunPlc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationGunPlc extends BaseGasStationGunPlc<GasStationGunPlc> {
	
}

