package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationGunMap;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationGunMap extends BaseGasStationGunMap<GasStationGunMap> {
	
}

