package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationRemoteMap;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationRemoteMap extends BaseGasStationRemoteMap<GasStationRemoteMap> {
	
}

