package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStation extends BaseGasStation<GasStation> {
	
}

