package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStaffCertificate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStaffCertificate extends BaseGasStaffCertificate<GasStaffCertificate> {
	
}

