package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGasStationBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GasStationBase extends BaseGasStationBase<GasStationBase> {
	
}

