package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGenConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenConfig extends BaseGenConfig<GenConfig> {
	
}

