package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGenFieldConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenFieldConfig extends BaseGenFieldConfig<GenFieldConfig> {
	
}

