package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGenTableColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenTableColumn extends BaseGenTableColumn<GenTableColumn> {
	
}

