package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseGenTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenTable extends BaseGenTable<GenTable> {
	
}

