package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotCameraModelRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotCameraModelRegion extends BaseIotCameraModelRegion<IotCameraModelRegion> {
	
}

