package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotCameraModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotCameraModel extends BaseIotCameraModel<IotCameraModel> {
	
}

