package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotCameraModelRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotCameraModelRecord extends BaseIotCameraModelRecord<IotCameraModelRecord> {
	
}

