package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotCamera;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotCamera extends BaseIotCamera<IotCamera> {
	
}

