package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotGroup extends BaseIotGroup<IotGroup> {
	
}

