package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotGroupMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotGroupMember extends BaseIotGroupMember<IotGroupMember> {
	
}

