package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRdsRecordsV3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRdsRecordsV3 extends BaseIotSyncRdsRecordsV3<IotSyncRdsRecordsV3> {
	
}

