package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRecords extends BaseIotSyncRecords<IotSyncRecords> {
	
}

