package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRdsRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRdsRecords extends BaseIotSyncRdsRecords<IotSyncRdsRecords> {
	
}

