package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRdsRecordsV2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRdsRecordsV2 extends BaseIotSyncRdsRecordsV2<IotSyncRdsRecordsV2> {
	
}

