package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRecordsV2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRecordsV2 extends BaseIotSyncRecordsV2<IotSyncRecordsV2> {
	
}

