package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseIotSyncRecordsV3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IotSyncRecordsV3 extends BaseIotSyncRecordsV3<IotSyncRecordsV3> {
	
}

