package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseJiebangding;

import java.util.ServiceLoader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jiebangding extends BaseJiebangding<Jiebangding> {

 }

