package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseKongqianghardware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kongqianghardware extends BaseKongqianghardware<Kongqianghardware> {
	
}

