package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseManageuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manageuser extends BaseManageuser<Manageuser> {
	
}

