package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseManageXiaohezi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageXiaohezi extends BaseManageXiaohezi<ManageXiaohezi> {
	
}

