package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseMsgPushConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgPushConfig extends BaseMsgPushConfig<MsgPushConfig> {
	
}

