package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseOthergas;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Othergas extends BaseOthergas<Othergas> {
	
}

