package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BasePlckongzhi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plckongzhi extends BasePlckongzhi<Plckongzhi> {
	
}

