package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BasePlcxinhao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plcxinhao extends BasePlcxinhao<Plcxinhao> {
	
}

