package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BasePressureValueRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PressureValueRecords extends BasePressureValueRecords<PressureValueRecords> {
	
}

