package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BasePressureGaugeRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PressureGaugeRecords extends BasePressureGaugeRecords<PressureGaugeRecords> {
	
}

