package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BasePressureGaugeRecords1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PressureGaugeRecords1 extends BasePressureGaugeRecords1<PressureGaugeRecords1> {
	
}

