package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseProductRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductRecords extends BaseProductRecords<ProductRecords> {
	
}

