package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzSimpropTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSimpropTriggers extends BaseQrtzSimpropTriggers<QrtzSimpropTriggers> {
	
}

