package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzSimpleTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSimpleTriggers extends BaseQrtzSimpleTriggers<QrtzSimpleTriggers> {
	
}

