package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzTriggers extends BaseQrtzTriggers<QrtzTriggers> {
	
}

