package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzFiredTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzFiredTriggers extends BaseQrtzFiredTriggers<QrtzFiredTriggers> {
	
}

