package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzLocks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzLocks extends BaseQrtzLocks<QrtzLocks> {
	
}

