package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzPausedTriggerGrps;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzPausedTriggerGrps extends BaseQrtzPausedTriggerGrps<QrtzPausedTriggerGrps> {
	
}

