package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzBlobTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzBlobTriggers extends BaseQrtzBlobTriggers<QrtzBlobTriggers> {
	
}

