package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseQrtzCalendars;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzCalendars extends BaseQrtzCalendars<QrtzCalendars> {
	
}

