package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseRanqibiaobangding;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ranqibiaobangding extends BaseRanqibiaobangding<Ranqibiaobangding> {
	
}

