package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseRestaurant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Restaurant extends BaseRestaurant<Restaurant> {
	
}

