package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseScaleRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScaleRecords extends BaseScaleRecords<ScaleRecords> {
	
}

