package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseScpVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScpVideo extends BaseScpVideo<ScpVideo> {
	
}

