package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseScpVideoFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScpVideoFile extends BaseScpVideoFile<ScpVideoFile> {
	
}

