package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseShexiangtou;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shexiangtou extends BaseShexiangtou<Shexiangtou> {
	
}

