package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseShexiangtoulanya;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shexiangtoulanya extends BaseShexiangtoulanya<Shexiangtoulanya> {
	
}

