package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseStationCurrent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StationCurrent extends BaseStationCurrent<StationCurrent> {
	
}

