package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Station extends BaseStation<Station> {
	
}

