package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseStateTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StateTime extends BaseStateTime<StateTime> {
	
}

