package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSuccessfulRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SuccessfulRecords extends BaseSuccessfulRecords<SuccessfulRecords> {
	
}

