package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConfig extends BaseSysConfig<SysConfig> {
	
}

