package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysDictType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDictType extends BaseSysDictType<SysDictType> {
	
}

