package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysDictData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDictData extends BaseSysDictData<SysDictData> {
	
}

