package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysDictItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDictItem extends BaseSysDictItem<SysDictItem> {
	
}

