package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDept extends BaseSysDept<SysDept> {
	
}

