package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	
}

