package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysJobLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysJobLog extends BaseSysJobLog<SysJobLog> {
	
}

