package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysJob extends BaseSysJob<SysJob> {
	
}

