package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysLogininfor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLogininfor extends BaseSysLogininfor<SysLogininfor> {
	
}

