package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	
}

