package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	
}

