package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysNotice extends BaseSysNotice<SysNotice> {
	
}

