package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperLog extends BaseSysOperLog<SysOperLog> {
	
}

