package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysOssConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOssConfig extends BaseSysOssConfig<SysOssConfig> {
	
}

