package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysOss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOss extends BaseSysOss<SysOss> {
	
}

