package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPost extends BaseSysPost<SysPost> {
	
}

