package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	
}

