package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	
}

