package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysRoleDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleDept extends BaseSysRoleDept<SysRoleDept> {
	
}

