package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysUserPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserPost extends BaseSysUserPost<SysUserPost> {
	
}

