package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysUserNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserNotice extends BaseSysUserNotice<SysUserNotice> {
	
}

