package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	
}

