package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseSysUserStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserStation extends BaseSysUserStation<SysUserStation> {
	
}

