package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseTransport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Transport extends BaseTransport<Transport> {
	
}

