package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseUploaddianzibiaoqian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Uploaddianzibiaoqian extends BaseUploaddianzibiaoqian<Uploaddianzibiaoqian> {
	
}

