package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseUseDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UseDetail extends BaseUseDetail<UseDetail> {
	
}

