package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseUserfunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userfunction extends BaseUserfunction<Userfunction> {
	
}

