package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseUserfunctionCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserfunctionCopy1 extends BaseUserfunctionCopy1<UserfunctionCopy1> {
	
}

