package com.sjzu.edu.common.model;

import com.sjzu.edu.common.model.base.BaseVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Version extends BaseVersion<Version> {
	
}

