package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzJobDetails<M extends BaseQrtzJobDetails<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * 任务名称
	 */
	public void setJobName(java.lang.String jobName) {
		set("job_name", jobName);
	}
	
	/**
	 * 任务名称
	 */
	public java.lang.String getJobName() {
		return getStr("job_name");
	}
	
	/**
	 * 任务组名
	 */
	public void setJobGroup(java.lang.String jobGroup) {
		set("job_group", jobGroup);
	}
	
	/**
	 * 任务组名
	 */
	public java.lang.String getJobGroup() {
		return getStr("job_group");
	}
	
	/**
	 * 相关介绍
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 相关介绍
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 执行任务类名称
	 */
	public void setJobClassName(java.lang.String jobClassName) {
		set("job_class_name", jobClassName);
	}
	
	/**
	 * 执行任务类名称
	 */
	public java.lang.String getJobClassName() {
		return getStr("job_class_name");
	}
	
	/**
	 * 是否持久化
	 */
	public void setIsDurable(java.lang.String isDurable) {
		set("is_durable", isDurable);
	}
	
	/**
	 * 是否持久化
	 */
	public java.lang.String getIsDurable() {
		return getStr("is_durable");
	}
	
	/**
	 * 是否并发
	 */
	public void setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("is_nonconcurrent", isNonconcurrent);
	}
	
	/**
	 * 是否并发
	 */
	public java.lang.String getIsNonconcurrent() {
		return getStr("is_nonconcurrent");
	}
	
	/**
	 * 是否更新数据
	 */
	public void setIsUpdateData(java.lang.String isUpdateData) {
		set("is_update_data", isUpdateData);
	}
	
	/**
	 * 是否更新数据
	 */
	public java.lang.String getIsUpdateData() {
		return getStr("is_update_data");
	}
	
	/**
	 * 是否接受恢复执行
	 */
	public void setRequestsRecovery(java.lang.String requestsRecovery) {
		set("requests_recovery", requestsRecovery);
	}
	
	/**
	 * 是否接受恢复执行
	 */
	public java.lang.String getRequestsRecovery() {
		return getStr("requests_recovery");
	}
	
	/**
	 * 存放持久化job对象
	 */
	public void setJobData(byte[] jobData) {
		set("job_data", jobData);
	}
	
	/**
	 * 存放持久化job对象
	 */
	public byte[] getJobData() {
		return get("job_data");
	}
	
}

