package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRestaurant<M extends BaseRestaurant<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRestaurantno(java.lang.String restaurantno) {
		set("restaurantno", restaurantno);
	}
	
	public java.lang.String getRestaurantno() {
		return getStr("restaurantno");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setLeader(java.lang.String leader) {
		set("leader", leader);
	}
	
	public java.lang.String getLeader() {
		return getStr("leader");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	/**
	 * 密码
	 */
	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPwd() {
		return getStr("pwd");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 饭店的秤的编码
	 */
	public void setChengno(java.lang.String chengno) {
		set("chengno", chengno);
	}
	
	/**
	 * 饭店的秤的编码
	 */
	public java.lang.String getChengno() {
		return getStr("chengno");
	}
	
	public void setBiaoji(java.lang.Integer biaoji) {
		set("biaoji", biaoji);
	}
	
	public java.lang.Integer getBiaoji() {
		return getInt("biaoji");
	}
	
	/**
	 * 小盒子编号
	 */
	public void setXiaohezi(java.lang.String xiaohezi) {
		set("xiaohezi", xiaohezi);
	}
	
	/**
	 * 小盒子编号
	 */
	public java.lang.String getXiaohezi() {
		return getStr("xiaohezi");
	}
	
	/**
	 * 发生危险，发消息给手机，手机号用-分割。13591402086-13608921978
	 */
	public void setBaojingren(java.lang.String baojingren) {
		set("baojingren", baojingren);
	}
	
	/**
	 * 发生危险，发消息给手机，手机号用-分割。13591402086-13608921978
	 */
	public java.lang.String getBaojingren() {
		return getStr("baojingren");
	}
	
}

