package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStationGunPlc<M extends BaseGasStationGunPlc<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 站点编码
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	/**
	 * 加气枪编号
	 */
	public void setGunNo(java.lang.Integer gunNo) {
		set("gun_no", gunNo);
	}
	
	/**
	 * 加气枪编号
	 */
	public java.lang.Integer getGunNo() {
		return getInt("gun_no");
	}
	
	/**
	 * 控枪服务地址
	 */
	public void setRestUrl(java.lang.String restUrl) {
		set("rest_url", restUrl);
	}
	
	/**
	 * 控枪服务地址
	 */
	public java.lang.String getRestUrl() {
		return getStr("rest_url");
	}
	
	/**
	 * PLC设备IP
	 */
	public void setPlcIp(java.lang.String plcIp) {
		set("plc_ip", plcIp);
	}
	
	/**
	 * PLC设备IP
	 */
	public java.lang.String getPlcIp() {
		return getStr("plc_ip");
	}
	
	/**
	 * PLC设备端口
	 */
	public void setPlcPort(java.lang.String plcPort) {
		set("plc_port", plcPort);
	}
	
	/**
	 * PLC设备端口
	 */
	public java.lang.String getPlcPort() {
		return getStr("plc_port");
	}
	
	/**
	 * 子站ID
	 */
	public void setSlaveId(java.lang.String slaveId) {
		set("slave_id", slaveId);
	}
	
	/**
	 * 子站ID
	 */
	public java.lang.String getSlaveId() {
		return getStr("slave_id");
	}
	
	/**
	 * PLC寄存器地址
	 */
	public void setPlcRegisterId(java.lang.String plcRegisterId) {
		set("plc_register_id", plcRegisterId);
	}
	
	/**
	 * PLC寄存器地址
	 */
	public java.lang.String getPlcRegisterId() {
		return getStr("plc_register_id");
	}
	
	/**
	 * PLC开启信号值
	 */
	public void setOpenValue(java.lang.String openValue) {
		set("open_value", openValue);
	}
	
	/**
	 * PLC开启信号值
	 */
	public java.lang.String getOpenValue() {
		return getStr("open_value");
	}
	
	/**
	 * PLC自动重置间隔
	 */
	public void setResetInterval(java.lang.Long resetInterval) {
		set("reset_interval", resetInterval);
	}
	
	/**
	 * PLC自动重置间隔
	 */
	public java.lang.Long getResetInterval() {
		return getLong("reset_interval");
	}
	
	/**
	 * PLC关闭信号值
	 */
	public void setCloseValue(java.lang.String closeValue) {
		set("close_value", closeValue);
	}
	
	/**
	 * PLC关闭信号值
	 */
	public java.lang.String getCloseValue() {
		return getStr("close_value");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}
	
	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

