package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScaleRecords<M extends BaseScaleRecords<M>> extends Model<M> implements IBean {

	/**
	 * id 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * id 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 电子秤编号
	 */
	public void setScaleno(java.lang.Long scaleno) {
		set("scaleno", scaleno);
	}
	
	/**
	 * 电子秤编号
	 */
	public java.lang.Long getScaleno() {
		return getLong("scaleno");
	}
	
	/**
	 * 属性名称
	 */
	public void setPropertyName(java.lang.String propertyName) {
		set("property_name", propertyName);
	}
	
	/**
	 * 属性名称
	 */
	public java.lang.String getPropertyName() {
		return getStr("property_name");
	}
	
	/**
	 * 属性值
	 */
	public void setPropertyValue(java.lang.String propertyValue) {
		set("property_value", propertyValue);
	}
	
	/**
	 * 属性值
	 */
	public java.lang.String getPropertyValue() {
		return getStr("property_value");
	}
	
	/**
	 * 发生时间
	 */
	public void setPropertyDatetime(java.lang.String propertyDatetime) {
		set("property_datetime", propertyDatetime);
	}
	
	/**
	 * 发生时间
	 */
	public java.lang.String getPropertyDatetime() {
		return getStr("property_datetime");
	}
	
}

