package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysOss<M extends BaseSysOss<M>> extends Model<M> implements IBean {

	/**
	 * 对象存储主键
	 */
	public void setOssId(java.lang.Long ossId) {
		set("oss_id", ossId);
	}
	
	/**
	 * 对象存储主键
	 */
	public java.lang.Long getOssId() {
		return getLong("oss_id");
	}
	
	/**
	 * 文件名
	 */
	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileName() {
		return getStr("file_name");
	}
	
	/**
	 * 原名
	 */
	public void setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
	}
	
	/**
	 * 原名
	 */
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}
	
	/**
	 * 文件后缀名
	 */
	public void setFileSuffix(java.lang.String fileSuffix) {
		set("file_suffix", fileSuffix);
	}
	
	/**
	 * 文件后缀名
	 */
	public java.lang.String getFileSuffix() {
		return getStr("file_suffix");
	}
	
	/**
	 * URL地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * URL地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 上传人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 上传人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 服务商
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 服务商
	 */
	public java.lang.String getService() {
		return getStr("service");
	}
	
}

