package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	/**
	 * 主键 
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键 
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 类型编码
	 */
	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}
	
	/**
	 * 类型编码
	 */
	public java.lang.String getDictCode() {
		return getStr("dict_code");
	}
	
	/**
	 * 类型名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 类型名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 状态(0:正常;1:禁用)
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}
	
	/**
	 * 状态(0:正常;1:禁用)
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 创建人ID
	 */
	public void setCreateBy(java.lang.Long createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Long getCreateBy() {
		return getLong("create_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 修改人ID
	 */
	public void setUpdateBy(java.lang.Long updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人ID
	 */
	public java.lang.Long getUpdateBy() {
		return getLong("update_by");
	}
	
	/**
	 * 是否删除(1-删除，0-未删除)
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除(1-删除，0-未删除)
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
}

