package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotCameraModelRecord<M extends BaseIotCameraModelRecord<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 摄像头ID
	 */
	public void setCameraId(java.lang.Long cameraId) {
		set("camera_id", cameraId);
	}
	
	/**
	 * 摄像头ID
	 */
	public java.lang.Long getCameraId() {
		return getLong("camera_id");
	}
	
	/**
	 * 模型ID
	 */
	public void setModelId(java.lang.Long modelId) {
		set("model_id", modelId);
	}
	
	/**
	 * 模型ID
	 */
	public java.lang.Long getModelId() {
		return getLong("model_id");
	}
	
	/**
	 * 模型名称
	 */
	public void setModelName(java.lang.String modelName) {
		set("model_name", modelName);
	}
	
	/**
	 * 模型名称
	 */
	public java.lang.String getModelName() {
		return getStr("model_name");
	}
	
	/**
	 * 模型缓存标识
	 */
	public void setModelKey(java.lang.String modelKey) {
		set("model_key", modelKey);
	}
	
	/**
	 * 模型缓存标识
	 */
	public java.lang.String getModelKey() {
		return getStr("model_key");
	}
	
	/**
	 * 记录类型：0 普通记录，1 告警记录
	 */
	public void setRecordType(java.lang.String recordType) {
		set("record_type", recordType);
	}
	
	/**
	 * 记录类型：0 普通记录，1 告警记录
	 */
	public java.lang.String getRecordType() {
		return getStr("record_type");
	}
	
	/**
	 * 开始监测时间
	 */
	public void setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
	}
	
	/**
	 * 开始监测时间
	 */
	public java.util.Date getBeginTime() {
		return getDate("begin_time");
	}
	
	/**
	 * 提醒时间
	 */
	public void setAlertTime(java.util.Date alertTime) {
		set("alert_time", alertTime);
	}
	
	/**
	 * 提醒时间
	 */
	public java.util.Date getAlertTime() {
		return getDate("alert_time");
	}
	
	/**
	 * 记录时间
	 */
	public void setRecordTime(java.util.Date recordTime) {
		set("record_time", recordTime);
	}
	
	/**
	 * 记录时间
	 */
	public java.util.Date getRecordTime() {
		return getDate("record_time");
	}
	
	/**
	 * 保存检测结果图片路径
	 */
	public void setImgPath(java.lang.String imgPath) {
		set("img_path", imgPath);
	}
	
	/**
	 * 保存检测结果图片路径
	 */
	public java.lang.String getImgPath() {
		return getStr("img_path");
	}
	
	/**
	 * 图片路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 图片路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}
	
	/**
	 * 事件名称
	 */
	public void setEventName(java.lang.String eventName) {
		set("event_name", eventName);
	}
	
	/**
	 * 事件名称
	 */
	public java.lang.String getEventName() {
		return getStr("event_name");
	}
	
	/**
	 * 火车ID
	 */
	public void setTrain(java.lang.Long train) {
		set("train", train);
	}
	
	/**
	 * 火车ID
	 */
	public java.lang.Long getTrain() {
		return getLong("train");
	}
	
	/**
	 * 视频ID
	 */
	public void setVideoId(java.lang.Long videoId) {
		set("video_id", videoId);
	}
	
	/**
	 * 视频ID
	 */
	public java.lang.Long getVideoId() {
		return getLong("video_id");
	}
	
	/**
	 * 视频路径
	 */
	public void setVideoPath(java.lang.String videoPath) {
		set("video_path", videoPath);
	}
	
	/**
	 * 视频路径
	 */
	public java.lang.String getVideoPath() {
		return getStr("video_path");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

