package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFillRecordCheck<M extends BaseFillRecordCheck<M>> extends Model<M> implements IBean {

	/**
	 * 记录主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 记录主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 充气记录UUID
	 */
	public void setFillId(java.lang.String fillId) {
		set("fill_id", fillId);
	}
	
	/**
	 * 充气记录UUID
	 */
	public java.lang.String getFillId() {
		return getStr("fill_id");
	}
	
	/**
	 * 订单号
	 */
	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}
	
	/**
	 * 充气前检查
	 */
	public void setBeforeFillingCheck(java.lang.String beforeFillingCheck) {
		set("before_filling_check", beforeFillingCheck);
	}
	
	/**
	 * 充气前检查
	 */
	public java.lang.String getBeforeFillingCheck() {
		return getStr("before_filling_check");
	}
	
	/**
	 * 充气后检查
	 */
	public void setAfterFillingCheck(java.lang.String afterFillingCheck) {
		set("after_filling_check", afterFillingCheck);
	}
	
	/**
	 * 充气后检查
	 */
	public java.lang.String getAfterFillingCheck() {
		return getStr("after_filling_check");
	}
	
	/**
	 * 充气时间
	 */
	public void setRealTime(java.lang.String realTime) {
		set("real_time", realTime);
	}
	
	/**
	 * 充气时间
	 */
	public java.lang.String getRealTime() {
		return getStr("real_time");
	}
	
	/**
	 * 充气人员ID
	 */
	public void setFillingStaffId(java.lang.String fillingStaffId) {
		set("filling_staff_id", fillingStaffId);
	}
	
	/**
	 * 充气人员ID
	 */
	public java.lang.String getFillingStaffId() {
		return getStr("filling_staff_id");
	}
	
	/**
	 * 充气人员
	 */
	public void setFillingStaffName(java.lang.String fillingStaffName) {
		set("filling_staff_name", fillingStaffName);
	}
	
	/**
	 * 充气人员
	 */
	public java.lang.String getFillingStaffName() {
		return getStr("filling_staff_name");
	}
	
	/**
	 * 检查人员ID
	 */
	public void setFillingCheckStaffId(java.lang.String fillingCheckStaffId) {
		set("filling_check_staff_id", fillingCheckStaffId);
	}
	
	/**
	 * 检查人员ID
	 */
	public java.lang.String getFillingCheckStaffId() {
		return getStr("filling_check_staff_id");
	}
	
	/**
	 * 检查人员
	 */
	public void setFillingCheckStaffName(java.lang.String fillingCheckStaffName) {
		set("filling_check_staff_name", fillingCheckStaffName);
	}
	
	/**
	 * 检查人员
	 */
	public java.lang.String getFillingCheckStaffName() {
		return getStr("filling_check_staff_name");
	}
	
	/**
	 * 气枪号
	 */
	public void setGunNo(java.lang.String gunNo) {
		set("gun_no", gunNo);
	}
	
	/**
	 * 气枪号
	 */
	public java.lang.String getGunNo() {
		return getStr("gun_no");
	}
	
	/**
	 * 电子标签
	 */
	public void setGasBottleNo(java.lang.String gasBottleNo) {
		set("gas_bottle_no", gasBottleNo);
	}
	
	/**
	 * 电子标签
	 */
	public java.lang.String getGasBottleNo() {
		return getStr("gas_bottle_no");
	}
	
	/**
	 * 出厂编码
	 */
	public void setGasBottleExnum(java.lang.String gasBottleExnum) {
		set("gas_bottle_exnum", gasBottleExnum);
	}
	
	/**
	 * 出厂编码
	 */
	public java.lang.String getGasBottleExnum() {
		return getStr("gas_bottle_exnum");
	}
	
	/**
	 * 气瓶编码
	 */
	public void setLicensePlate(java.lang.String licensePlate) {
		set("license_plate", licensePlate);
	}
	
	/**
	 * 气瓶编码
	 */
	public java.lang.String getLicensePlate() {
		return getStr("license_plate");
	}
	
	/**
	 * 充装后检查图片ossid
	 */
	public void setAfterCheckImageOssId(java.lang.String afterCheckImageOssId) {
		set("after_check_image_oss_id", afterCheckImageOssId);
	}
	
	/**
	 * 充装后检查图片ossid
	 */
	public java.lang.String getAfterCheckImageOssId() {
		return getStr("after_check_image_oss_id");
	}
	
	/**
	 * 充装后检查图片路径
	 */
	public void setAfterCheckImageUrl(java.lang.String afterCheckImageUrl) {
		set("after_check_image_url", afterCheckImageUrl);
	}
	
	/**
	 * 充装后检查图片路径
	 */
	public java.lang.String getAfterCheckImageUrl() {
		return getStr("after_check_image_url");
	}
	
	/**
	 * 充装后检查图片名称
	 */
	public void setAfterCheckImageFillName(java.lang.String afterCheckImageFillName) {
		set("after_check_image_fill_name", afterCheckImageFillName);
	}
	
	/**
	 * 充装后检查图片名称
	 */
	public java.lang.String getAfterCheckImageFillName() {
		return getStr("after_check_image_fill_name");
	}
	
	/**
	 * 充装前检查图片ossid
	 */
	public void setBeforeCheckImageOssId(java.lang.String beforeCheckImageOssId) {
		set("before_check_image_oss_id", beforeCheckImageOssId);
	}
	
	/**
	 * 充装前检查图片ossid
	 */
	public java.lang.String getBeforeCheckImageOssId() {
		return getStr("before_check_image_oss_id");
	}
	
	/**
	 * 充装前检查图片名称
	 */
	public void setBeforeCheckImageFillName(java.lang.String beforeCheckImageFillName) {
		set("before_check_image_fill_name", beforeCheckImageFillName);
	}
	
	/**
	 * 充装前检查图片名称
	 */
	public java.lang.String getBeforeCheckImageFillName() {
		return getStr("before_check_image_fill_name");
	}
	
	/**
	 * 充装前检查图片路径
	 */
	public void setBeforeCheckImageUrl(java.lang.String beforeCheckImageUrl) {
		set("before_check_image_url", beforeCheckImageUrl);
	}
	
	/**
	 * 充装前检查图片路径
	 */
	public java.lang.String getBeforeCheckImageUrl() {
		return getStr("before_check_image_url");
	}
	
	/**
	 * 所属加气站ID
	 */
	public void setStationId(java.lang.String stationId) {
		set("station_id", stationId);
	}
	
	/**
	 * 所属加气站ID
	 */
	public java.lang.String getStationId() {
		return getStr("station_id");
	}
	
	/**
	 * 所属加气站名称
	 */
	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	/**
	 * 所属加气站名称
	 */
	public java.lang.String getStationName() {
		return getStr("station_name");
	}
	
	/**
	 * 到期时间
	 */
	public void setValidTime(java.lang.String validTime) {
		set("valid_time", validTime);
	}
	
	/**
	 * 到期时间
	 */
	public java.lang.String getValidTime() {
		return getStr("valid_time");
	}
	
	/**
	 * 充气类型
	 */
	public void setGasType(java.lang.String gasType) {
		set("gas_type", gasType);
	}
	
	/**
	 * 充气类型
	 */
	public java.lang.String getGasType() {
		return getStr("gas_type");
	}
	
	/**
	 * 充气量
	 */
	public void setNowGas(java.lang.String nowGas) {
		set("now_gas", nowGas);
	}
	
	/**
	 * 充气量
	 */
	public java.lang.String getNowGas() {
		return getStr("now_gas");
	}
	
	/**
	 * 充气时长
	 */
	public void setAddGasLong(java.lang.String addGasLong) {
		set("add_gas_long", addGasLong);
	}
	
	/**
	 * 充气时长
	 */
	public java.lang.String getAddGasLong() {
		return getStr("add_gas_long");
	}
	
	/**
	 * 充气单位
	 */
	public void setGasUnit(java.lang.String gasUnit) {
		set("gas_unit", gasUnit);
	}
	
	/**
	 * 充气单位
	 */
	public java.lang.String getGasUnit() {
		return getStr("gas_unit");
	}
	
	/**
	 * 充装前重量
	 */
	public void setPressureBegin(java.lang.String pressureBegin) {
		set("pressure_begin", pressureBegin);
	}
	
	/**
	 * 充装前重量
	 */
	public java.lang.String getPressureBegin() {
		return getStr("pressure_begin");
	}
	
	/**
	 * 总重/充装后重量
	 */
	public void setPressureFinish(java.lang.String pressureFinish) {
		set("pressure_finish", pressureFinish);
	}
	
	/**
	 * 总重/充装后重量
	 */
	public java.lang.String getPressureFinish() {
		return getStr("pressure_finish");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 是否是禁止加气/或者错误代码，10是正常，20是禁止，30是错误单
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 是否是禁止加气/或者错误代码，10是正常，20是禁止，30是错误单
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 记录是否完整,记录是否完整,10不完整，20完整，30是异常，40是错误
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 记录是否完整,记录是否完整,10不完整，20完整，30是异常，40是错误
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
}

