package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasBotCycleRecord<M extends BaseGasBotCycleRecord<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * LPG气瓶编码
	 */
	public void setLpgCode(java.lang.String lpgCode) {
		set("lpg_code", lpgCode);
	}
	
	/**
	 * LPG气瓶编码
	 */
	public java.lang.String getLpgCode() {
		return getStr("lpg_code");
	}
	
	/**
	 * 气瓶状态
	 */
	public void setBotSts(java.lang.String botSts) {
		set("bot_sts", botSts);
	}
	
	/**
	 * 气瓶状态
	 */
	public java.lang.String getBotSts() {
		return getStr("bot_sts");
	}
	
	/**
	 * 气瓶燃气量
	 */
	public void setNowGas(java.lang.String nowGas) {
		set("now_gas", nowGas);
	}
	
	/**
	 * 气瓶燃气量
	 */
	public java.lang.String getNowGas() {
		return getStr("now_gas");
	}
	
	/**
	 * 气瓶毛重
	 */
	public void setBotWeight(java.lang.Double botWeight) {
		set("bot_weight", botWeight);
	}
	
	/**
	 * 气瓶毛重
	 */
	public java.lang.Double getBotWeight() {
		return getDouble("bot_weight");
	}
	
	/**
	 * 总重量
	 */
	public void setTotalWeight(java.lang.Double totalWeight) {
		set("total_weight", totalWeight);
	}
	
	/**
	 * 总重量
	 */
	public java.lang.Double getTotalWeight() {
		return getDouble("total_weight");
	}
	
	/**
	 * 流转动作
	 */
	public void setCycleAction(java.lang.String cycleAction) {
		set("cycle_action", cycleAction);
	}
	
	/**
	 * 流转动作
	 */
	public java.lang.String getCycleAction() {
		return getStr("cycle_action");
	}
	
	/**
	 * 动作时间
	 */
	public void setActionTime(java.util.Date actionTime) {
		set("action_time", actionTime);
	}
	
	/**
	 * 动作时间
	 */
	public java.util.Date getActionTime() {
		return getDate("action_time");
	}
	
	/**
	 * 操作人
	 */
	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	/**
	 * 操作人
	 */
	public java.lang.String getOperator() {
		return getStr("operator");
	}
	
	/**
	 * 操作位置
	 */
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	/**
	 * 操作位置
	 */
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	/**
	 * 机构类型
	 */
	public void setOrgType(java.lang.String orgType) {
		set("org_type", orgType);
	}
	
	/**
	 * 机构类型
	 */
	public java.lang.String getOrgType() {
		return getStr("org_type");
	}
	
	/**
	 * 机构编码
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	/**
	 * 机构编码
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	/**
	 * 运输车牌
	 */
	public void setCarPlate(java.lang.String carPlate) {
		set("car_plate", carPlate);
	}
	
	/**
	 * 运输车牌
	 */
	public java.lang.String getCarPlate() {
		return getStr("car_plate");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

