package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenConfig<M extends BaseGenConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 表名
	 */
	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	/**
	 * 表名
	 */
	public java.lang.String getTableName() {
		return getStr("table_name");
	}
	
	/**
	 * 模块名
	 */
	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}
	
	/**
	 * 模块名
	 */
	public java.lang.String getModuleName() {
		return getStr("module_name");
	}
	
	/**
	 * 包名
	 */
	public void setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
	}
	
	/**
	 * 包名
	 */
	public java.lang.String getPackageName() {
		return getStr("package_name");
	}
	
	/**
	 * 业务名
	 */
	public void setBusinessName(java.lang.String businessName) {
		set("business_name", businessName);
	}
	
	/**
	 * 业务名
	 */
	public java.lang.String getBusinessName() {
		return getStr("business_name");
	}
	
	/**
	 * 实体类名
	 */
	public void setEntityName(java.lang.String entityName) {
		set("entity_name", entityName);
	}
	
	/**
	 * 实体类名
	 */
	public java.lang.String getEntityName() {
		return getStr("entity_name");
	}
	
	/**
	 * 作者
	 */
	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	/**
	 * 作者
	 */
	public java.lang.String getAuthor() {
		return getStr("author");
	}
	
	/**
	 * 上级菜单ID，对应sys_menu的id 
	 */
	public void setParentMenuId(java.lang.Long parentMenuId) {
		set("parent_menu_id", parentMenuId);
	}
	
	/**
	 * 上级菜单ID，对应sys_menu的id 
	 */
	public java.lang.Long getParentMenuId() {
		return getLong("parent_menu_id");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 是否删除
	 */
	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}
	
}

