package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCourcename(java.lang.String courcename) {
		set("courcename", courcename);
	}
	
	public java.lang.String getCourcename() {
		return getStr("courcename");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatue(java.lang.Integer statue) {
		set("statue", statue);
	}
	
	public java.lang.Integer getStatue() {
		return getInt("statue");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 插入的时间
	 */
	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 插入的时间
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}
	
	/**
	 * 谁插入的输入
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 谁插入的输入
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
}

