package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStation<M extends BaseStation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
	}
	
	public java.lang.Integer getStationId() {
		return getInt("station_id");
	}
	
	public void setBottleId(java.lang.String bottleId) {
		set("bottle_id", bottleId);
	}
	
	public java.lang.String getBottleId() {
		return getStr("bottle_id");
	}
	
	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	public java.lang.String getStationName() {
		return getStr("station_name");
	}
	
	public void setBottleName(java.lang.String bottleName) {
		set("bottle_name", bottleName);
	}
	
	public java.lang.String getBottleName() {
		return getStr("bottle_name");
	}
	
	public void setStationSize(java.lang.Integer stationSize) {
		set("station_size", stationSize);
	}
	
	public java.lang.Integer getStationSize() {
		return getInt("station_size");
	}
	
	public void setBottleSize(java.lang.Integer bottleSize) {
		set("bottle_size", bottleSize);
	}
	
	public java.lang.Integer getBottleSize() {
		return getInt("bottle_size");
	}
	
	public void setTime(java.lang.String time) {
		set("time", time);
	}
	
	public java.lang.String getTime() {
		return getStr("time");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStaff(java.lang.String staff) {
		set("staff", staff);
	}
	
	public java.lang.String getStaff() {
		return getStr("staff");
	}
	
}

