package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserNotice<M extends BaseSysUserNotice<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 公共通知id
	 */
	public void setNoticeId(java.lang.Long noticeId) {
		set("notice_id", noticeId);
	}
	
	/**
	 * 公共通知id
	 */
	public java.lang.Long getNoticeId() {
		return getLong("notice_id");
	}
	
	/**
	 * 用户id
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 读取状态（0: 未读, 1: 已读）
	 */
	public void setIsRead(java.lang.Long isRead) {
		set("is_read", isRead);
	}
	
	/**
	 * 读取状态（0: 未读, 1: 已读）
	 */
	public java.lang.Long getIsRead() {
		return getLong("is_read");
	}
	
	/**
	 * 阅读时间
	 */
	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}
	
	/**
	 * 阅读时间
	 */
	public java.util.Date getReadTime() {
		return getDate("read_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 逻辑删除(0: 未删除, 1: 已删除)
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 逻辑删除(0: 未删除, 1: 已删除)
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
}

