package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductRecords<M extends BaseProductRecords<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}
	
	public void setProductKey(java.lang.String productKey) {
		set("product_key", productKey);
	}
	
	public java.lang.String getProductKey() {
		return getStr("product_key");
	}
	
	public void setProductType(java.lang.String productType) {
		set("product_type", productType);
	}
	
	public java.lang.String getProductType() {
		return getStr("product_type");
	}
	
	public void setProductSecret(java.lang.String productSecret) {
		set("product_secret", productSecret);
	}
	
	public java.lang.String getProductSecret() {
		return getStr("product_secret");
	}
	
}

