package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasBottle<M extends BaseGasBottle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * qipignbianma
	 */
	public void setBottleId(java.lang.String bottleId) {
		set("bottle_id", bottleId);
	}
	
	/**
	 * qipignbianma
	 */
	public java.lang.String getBottleId() {
		return getStr("bottle_id");
	}
	
	/**
	 * 公司名称
	 */
	public void setGasName(java.lang.String gasName) {
		set("gas_name", gasName);
	}
	
	/**
	 * 公司名称
	 */
	public java.lang.String getGasName() {
		return getStr("gas_name");
	}
	
	/**
	 * 运输人，运输司机的姓名
	 */
	public void setTransStaff(java.lang.String transStaff) {
		set("trans_staff", transStaff);
	}
	
	/**
	 * 运输人，运输司机的姓名
	 */
	public java.lang.String getTransStaff() {
		return getStr("trans_staff");
	}
	
	public void setTransReceiver(java.lang.String transReceiver) {
		set("trans_receiver", transReceiver);
	}
	
	public java.lang.String getTransReceiver() {
		return getStr("trans_receiver");
	}
	
	public void setTransUninstall(java.lang.String transUninstall) {
		set("trans_uninstall", transUninstall);
	}
	
	public java.lang.String getTransUninstall() {
		return getStr("trans_uninstall");
	}
	
	public void setStateId(java.lang.Integer stateId) {
		set("state_id", stateId);
	}
	
	public java.lang.Integer getStateId() {
		return getInt("state_id");
	}
	
	/**
	 * 运输状态
	 */
	public void setTransState(java.lang.String transState) {
		set("trans_state", transState);
	}
	
	/**
	 * 运输状态
	 */
	public java.lang.String getTransState() {
		return getStr("trans_state");
	}
	
	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}
	
	public java.lang.String getStartTime() {
		return getStr("start_time");
	}
	
	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}
	
	public java.lang.String getEndTime() {
		return getStr("end_time");
	}
	
	public void setCarId(java.lang.String carId) {
		set("car_id", carId);
	}
	
	public java.lang.String getCarId() {
		return getStr("car_id");
	}
	
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}
	
	public void setJingDu(java.lang.String jingDu) {
		set("jingDu", jingDu);
	}
	
	public java.lang.String getJingDu() {
		return getStr("jingDu");
	}
	
	public void setWeiDu(java.lang.String weiDu) {
		set("weiDu", weiDu);
	}
	
	public java.lang.String getWeiDu() {
		return getStr("weiDu");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setJieshujingdu(java.lang.String jieshujingdu) {
		set("jieshujingdu", jieshujingdu);
	}
	
	public java.lang.String getJieshujingdu() {
		return getStr("jieshujingdu");
	}
	
	public void setJieshuweidu(java.lang.String jieshuweidu) {
		set("jieshuweidu", jieshuweidu);
	}
	
	public java.lang.String getJieshuweidu() {
		return getStr("jieshuweidu");
	}
	
	public void setJieshuaddress(java.lang.String jieshuaddress) {
		set("jieshuaddress", jieshuaddress);
	}
	
	public java.lang.String getJieshuaddress() {
		return getStr("jieshuaddress");
	}
	
}

