package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzCalendars<M extends BaseQrtzCalendars<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * 日历名称
	 */
	public void setCalendarName(java.lang.String calendarName) {
		set("calendar_name", calendarName);
	}
	
	/**
	 * 日历名称
	 */
	public java.lang.String getCalendarName() {
		return getStr("calendar_name");
	}
	
	/**
	 * 存放持久化calendar对象
	 */
	public void setCalendar(byte[] calendar) {
		set("calendar", calendar);
	}
	
	/**
	 * 存放持久化calendar对象
	 */
	public byte[] getCalendar() {
		return get("calendar");
	}
	
}

