package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotCameraModel<M extends BaseIotCameraModel<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 摄像头ID
	 */
	public void setCameraId(java.lang.Long cameraId) {
		set("camera_id", cameraId);
	}
	
	/**
	 * 摄像头ID
	 */
	public java.lang.Long getCameraId() {
		return getLong("camera_id");
	}
	
	/**
	 * 模型ID
	 */
	public void setModelId(java.lang.Long modelId) {
		set("model_id", modelId);
	}
	
	/**
	 * 模型ID
	 */
	public java.lang.Long getModelId() {
		return getLong("model_id");
	}
	
	/**
	 * 模型名称
	 */
	public void setModelName(java.lang.String modelName) {
		set("model_name", modelName);
	}
	
	/**
	 * 模型名称
	 */
	public java.lang.String getModelName() {
		return getStr("model_name");
	}
	
	/**
	 * 模型缓存标识
	 */
	public void setModelKey(java.lang.String modelKey) {
		set("model_key", modelKey);
	}
	
	/**
	 * 模型缓存标识
	 */
	public java.lang.String getModelKey() {
		return getStr("model_key");
	}
	
	/**
	 * 模型版本
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * 模型版本
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}
	
	/**
	 * 模型开启标识
	 */
	public void setModelOpenFlag(java.lang.String modelOpenFlag) {
		set("model_open_flag", modelOpenFlag);
	}
	
	/**
	 * 模型开启标识
	 */
	public java.lang.String getModelOpenFlag() {
		return getStr("model_open_flag");
	}
	
	/**
	 * 模型检测事件
	 */
	public void setDetectEvents(java.lang.String detectEvents) {
		set("detect_events", detectEvents);
	}
	
	/**
	 * 模型检测事件
	 */
	public java.lang.String getDetectEvents() {
		return getStr("detect_events");
	}
	
	/**
	 * GPU标号
	 */
	public void setGpuId(java.lang.Integer gpuId) {
		set("gpu_id", gpuId);
	}
	
	/**
	 * GPU标号
	 */
	public java.lang.Integer getGpuId() {
		return getInt("gpu_id");
	}
	
	/**
	 * 应用标号
	 */
	public void setAppId(java.lang.Integer appId) {
		set("app_id", appId);
	}
	
	/**
	 * 应用标号
	 */
	public java.lang.Integer getAppId() {
		return getInt("app_id");
	}
	
	/**
	 * 保存检测结果图片标识，0 不保存；1 保存
	 */
	public void setImgSaveFlag(java.lang.String imgSaveFlag) {
		set("img_save_flag", imgSaveFlag);
	}
	
	/**
	 * 保存检测结果图片标识，0 不保存；1 保存
	 */
	public java.lang.String getImgSaveFlag() {
		return getStr("img_save_flag");
	}
	
	/**
	 * 保存检测结果图片路径
	 */
	public void setImgSavePath(java.lang.String imgSavePath) {
		set("img_save_path", imgSavePath);
	}
	
	/**
	 * 保存检测结果图片路径
	 */
	public java.lang.String getImgSavePath() {
		return getStr("img_save_path");
	}
	
	/**
	 * 保存检测结果图片相对路径
	 */
	public void setImgRelativePath(java.lang.String imgRelativePath) {
		set("img_relative_path", imgRelativePath);
	}
	
	/**
	 * 保存检测结果图片相对路径
	 */
	public java.lang.String getImgRelativePath() {
		return getStr("img_relative_path");
	}
	
	/**
	 * 码流类型
	 */
	public void setStreamType(java.lang.String streamType) {
		set("stream_type", streamType);
	}
	
	/**
	 * 码流类型
	 */
	public java.lang.String getStreamType() {
		return getStr("stream_type");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

