package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzSchedulerState<M extends BaseQrtzSchedulerState<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * 实例名称
	 */
	public void setInstanceName(java.lang.String instanceName) {
		set("instance_name", instanceName);
	}
	
	/**
	 * 实例名称
	 */
	public java.lang.String getInstanceName() {
		return getStr("instance_name");
	}
	
	/**
	 * 上次检查时间
	 */
	public void setLastCheckinTime(java.lang.Long lastCheckinTime) {
		set("last_checkin_time", lastCheckinTime);
	}
	
	/**
	 * 上次检查时间
	 */
	public java.lang.Long getLastCheckinTime() {
		return getLong("last_checkin_time");
	}
	
	/**
	 * 检查间隔时间
	 */
	public void setCheckinInterval(java.lang.Long checkinInterval) {
		set("checkin_interval", checkinInterval);
	}
	
	/**
	 * 检查间隔时间
	 */
	public java.lang.Long getCheckinInterval() {
		return getLong("checkin_interval");
	}
	
}

