package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotSyncRdsRecordsV2<M extends BaseIotSyncRdsRecordsV2<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * iot实例id
	 */
	public void setIotId(java.lang.String iotId) {
		set("iotId", iotId);
	}
	
	/**
	 * iot实例id
	 */
	public java.lang.String getIotId() {
		return getStr("iotId");
	}
	
	/**
	 * 产品key
	 */
	public void setProductKey(java.lang.String productKey) {
		set("productKey", productKey);
	}
	
	/**
	 * 产品key
	 */
	public java.lang.String getProductKey() {
		return getStr("productKey");
	}
	
	/**
	 * 设备名称
	 */
	public void setDevicename(java.lang.String devicename) {
		set("devicename", devicename);
	}
	
	/**
	 * 设备名称
	 */
	public java.lang.String getDevicename() {
		return getStr("devicename");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.lang.String createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreatedTime() {
		return getStr("created_time");
	}
	
	/**
	 * 用户编码
	 */
	public void setUser(java.lang.String user) {
		set("user", user);
	}
	
	/**
	 * 用户编码
	 */
	public java.lang.String getUser() {
		return getStr("user");
	}
	
	/**
	 * 系统供电状态
	 */
	public void setPowerStatus(java.lang.Integer PowerStatus) {
		set("PowerStatus", PowerStatus);
	}
	
	/**
	 * 系统供电状态
	 */
	public java.lang.Integer getPowerStatus() {
		return getInt("PowerStatus");
	}
	
	/**
	 * 报警
	 */
	public void setAlarm(java.lang.Integer Alarm) {
		set("Alarm", Alarm);
	}
	
	/**
	 * 报警
	 */
	public java.lang.Integer getAlarm() {
		return getInt("Alarm");
	}
	
	/**
	 * 视频连接状态
	 */
	public void setVideoLink(java.lang.Integer videoLink) {
		set("Video_Link", videoLink);
	}
	
	/**
	 * 视频连接状态
	 */
	public java.lang.Integer getVideoLink() {
		return getInt("Video_Link");
	}
	
	/**
	 * 一秤初始重量
	 */
	public void setValue11(java.lang.Float value11) {
		set("Value1_1", value11);
	}
	
	/**
	 * 一秤初始重量
	 */
	public java.lang.Float getValue11() {
		return getFloat("Value1_1");
	}
	
	/**
	 * 一秤实时重量
一秤实时重量
	 */
	public void setValue12(java.lang.Float value12) {
		set("Value1_2", value12);
	}
	
	/**
	 * 一秤实时重量
一秤实时重量
	 */
	public java.lang.Float getValue12() {
		return getFloat("Value1_2");
	}
	
	/**
	 * 一秤使用重量
	 */
	public void setValue13(java.lang.Float value13) {
		set("Value1_3", value13);
	}
	
	/**
	 * 一秤使用重量
	 */
	public java.lang.Float getValue13() {
		return getFloat("Value1_3");
	}
	
	/**
	 * 二秤初始重量
	 */
	public void setValue21(java.lang.Float value21) {
		set("Value2_1", value21);
	}
	
	/**
	 * 二秤初始重量
	 */
	public java.lang.Float getValue21() {
		return getFloat("Value2_1");
	}
	
	/**
	 * 二秤实时重量
一秤实时重量
	 */
	public void setValue22(java.lang.Float value22) {
		set("Value2_2", value22);
	}
	
	/**
	 * 二秤实时重量
一秤实时重量
	 */
	public java.lang.Float getValue22() {
		return getFloat("Value2_2");
	}
	
	/**
	 * 二秤使用重量
	 */
	public void setValue23(java.lang.Float value23) {
		set("Value2_3", value23);
	}
	
	/**
	 * 二秤使用重量
	 */
	public java.lang.Float getValue23() {
		return getFloat("Value2_3");
	}
	
	/**
	 * 三秤初始重量
	 */
	public void setValue31(java.lang.Float value31) {
		set("Value3_1", value31);
	}
	
	/**
	 * 三秤初始重量
	 */
	public java.lang.Float getValue31() {
		return getFloat("Value3_1");
	}
	
	/**
	 * 三秤实时重量
一秤实时重量
	 */
	public void setValue32(java.lang.Float value32) {
		set("Value3_2", value32);
	}
	
	/**
	 * 三秤实时重量
一秤实时重量
	 */
	public java.lang.Float getValue32() {
		return getFloat("Value3_2");
	}
	
	/**
	 * 三秤使用重量
	 */
	public void setValue33(java.lang.Float value33) {
		set("Value3_3", value33);
	}
	
	/**
	 * 三秤使用重量
	 */
	public java.lang.Float getValue33() {
		return getFloat("Value3_3");
	}
	
	/**
	 * 四秤初始重量
	 */
	public void setValue41(java.lang.Float value41) {
		set("Value4_1", value41);
	}
	
	/**
	 * 四秤初始重量
	 */
	public java.lang.Float getValue41() {
		return getFloat("Value4_1");
	}
	
	/**
	 * 四秤实时重量
四秤实时重量
	 */
	public void setValue42(java.lang.Float value42) {
		set("Value4_2", value42);
	}
	
	/**
	 * 四秤实时重量
四秤实时重量
	 */
	public java.lang.Float getValue42() {
		return getFloat("Value4_2");
	}
	
	/**
	 * 四秤使用重量
	 */
	public void setValue43(java.lang.Float value43) {
		set("Value4_3", value43);
	}
	
	/**
	 * 四秤使用重量
	 */
	public java.lang.Float getValue43() {
		return getFloat("Value4_3");
	}
	
	/**
	 * 1号电机阀状态
1号电机阀状态
	 */
	public void setValveStatus1(java.lang.Integer ValveStatus1) {
		set("ValveStatus1", ValveStatus1);
	}
	
	/**
	 * 1号电机阀状态
1号电机阀状态
	 */
	public java.lang.Integer getValveStatus1() {
		return getInt("ValveStatus1");
	}
	
	/**
	 * 2号电机阀状态
1号电机阀状态
	 */
	public void setValveStatus2(java.lang.Integer ValveStatus2) {
		set("ValveStatus2", ValveStatus2);
	}
	
	/**
	 * 2号电机阀状态
1号电机阀状态
	 */
	public java.lang.Integer getValveStatus2() {
		return getInt("ValveStatus2");
	}
	
	/**
	 * 3号电机阀状态
1号电机阀状态
	 */
	public void setValveStatus3(java.lang.Integer ValveStatus3) {
		set("ValveStatus3", ValveStatus3);
	}
	
	/**
	 * 3号电机阀状态
1号电机阀状态
	 */
	public java.lang.Integer getValveStatus3() {
		return getInt("ValveStatus3");
	}
	
	/**
	 * 4号电机阀状态
1号电机阀状态
	 */
	public void setValveStatus4(java.lang.Integer ValveStatus4) {
		set("ValveStatus4", ValveStatus4);
	}
	
	/**
	 * 4号电机阀状态
1号电机阀状态
	 */
	public java.lang.Integer getValveStatus4() {
		return getInt("ValveStatus4");
	}
	
	/**
	 * 1号秤绑定状态
	 */
	public void setBindingState1(java.lang.Integer BindingState1) {
		set("BindingState1", BindingState1);
	}
	
	/**
	 * 1号秤绑定状态
	 */
	public java.lang.Integer getBindingState1() {
		return getInt("BindingState1");
	}
	
	/**
	 * 2号秤绑定状态
	 */
	public void setBindingState2(java.lang.Integer BindingState2) {
		set("BindingState2", BindingState2);
	}
	
	/**
	 * 2号秤绑定状态
	 */
	public java.lang.Integer getBindingState2() {
		return getInt("BindingState2");
	}
	
	/**
	 * 3号秤绑定状态
	 */
	public void setBindingState3(java.lang.Integer BindingState3) {
		set("BindingState3", BindingState3);
	}
	
	/**
	 * 3号秤绑定状态
	 */
	public java.lang.Integer getBindingState3() {
		return getInt("BindingState3");
	}
	
	/**
	 * 4号秤绑定状态
	 */
	public void setBindingState4(java.lang.Integer BindingState4) {
		set("BindingState4", BindingState4);
	}
	
	/**
	 * 4号秤绑定状态
	 */
	public java.lang.Integer getBindingState4() {
		return getInt("BindingState4");
	}
	
	/**
	 * 数据来源
	 */
	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getSource() {
		return getStr("source");
	}
	
	/**
	 * 数据内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 数据内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
}

