package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgPushConfig<M extends BaseMsgPushConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setMsgType(java.lang.String msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.String getMsgType() {
		return getStr("msg_type");
	}
	
	public void setMsgTemplateCode(java.lang.String msgTemplateCode) {
		set("msg_template_code", msgTemplateCode);
	}
	
	public java.lang.String getMsgTemplateCode() {
		return getStr("msg_template_code");
	}
	
	public void setPhoneNum(java.lang.String phoneNum) {
		set("phone_num", phoneNum);
	}
	
	public java.lang.String getPhoneNum() {
		return getStr("phone_num");
	}
	
	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}
	
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}

