package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStateTime<M extends BaseStateTime<M>> extends Model<M> implements IBean {

	public void setStateId(java.lang.Integer stateId) {
		set("state_id", stateId);
	}
	
	public java.lang.Integer getStateId() {
		return getInt("state_id");
	}
	
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return getDate("start_time");
	}
	
	public void setTransTime(java.lang.String transTime) {
		set("trans_time", transTime);
	}
	
	public java.lang.String getTransTime() {
		return getStr("trans_time");
	}
	
	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return getDate("end_time");
	}
	
	public void setTransState(java.lang.String transState) {
		set("trans_state", transState);
	}
	
	public java.lang.String getTransState() {
		return getStr("trans_state");
	}
	
}

