package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDetectSnapshot<M extends BaseDetectSnapshot<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 摄像头设备编号
	 */
	public void setCameraUuid(java.lang.String cameraUuid) {
		set("camera_uuid", cameraUuid);
	}
	
	/**
	 * 摄像头设备编号
	 */
	public java.lang.String getCameraUuid() {
		return getStr("camera_uuid");
	}
	
	/**
	 * 湿度
	 */
	public void setWet(java.lang.String wet) {
		set("wet", wet);
	}
	
	/**
	 * 湿度
	 */
	public java.lang.String getWet() {
		return getStr("wet");
	}
	
	/**
	 * 温度
	 */
	public void setTem(java.lang.String tem) {
		set("tem", tem);
	}
	
	/**
	 * 温度
	 */
	public java.lang.String getTem() {
		return getStr("tem");
	}
	
	/**
	 * 照片描述信息
	 */
	public void setInfo(java.lang.String info) {
		set("info", info);
	}
	
	/**
	 * 照片描述信息
	 */
	public java.lang.String getInfo() {
		return getStr("info");
	}
	
	/**
	 * 烟雾浓度
	 */
	public void setSmoke(java.lang.String smoke) {
		set("smoke", smoke);
	}
	
	/**
	 * 烟雾浓度
	 */
	public java.lang.String getSmoke() {
		return getStr("smoke");
	}
	
	/**
	 * 图片存储路径
	 */
	public void setImagePath(java.lang.String imagePath) {
		set("image_path", imagePath);
	}
	
	/**
	 * 图片存储路径
	 */
	public java.lang.String getImagePath() {
		return getStr("image_path");
	}
	
	/**
	 * 识别出来的目标列表
	 */
	public void setDetectInfo(java.lang.String detectInfo) {
		set("detect_info", detectInfo);
	}
	
	/**
	 * 识别出来的目标列表
	 */
	public java.lang.String getDetectInfo() {
		return getStr("detect_info");
	}
	
	/**
	 * 抓取时间
	 */
	public void setGrabTime(java.util.Date grabTime) {
		set("grab_time", grabTime);
	}
	
	/**
	 * 抓取时间
	 */
	public java.util.Date getGrabTime() {
		return getDate("grab_time");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 逻辑删除标记(0:未删除 1:已删除)
	 */
	public void setIsDeleted(java.lang.Boolean isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 逻辑删除标记(0:未删除 1:已删除)
	 */
	public java.lang.Boolean getIsDeleted() {
		return get("is_deleted");
	}
	
}

