package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStaffCertificate<M extends BaseGasStaffCertificate<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 员工编码
	 */
	public void setStaffId(java.lang.String staffId) {
		set("staff_id", staffId);
	}
	
	/**
	 * 员工编码
	 */
	public java.lang.String getStaffId() {
		return getStr("staff_id");
	}
	
	/**
	 * 员工姓名
	 */
	public void setStaffName(java.lang.String staffName) {
		set("staff_name", staffName);
	}
	
	/**
	 * 员工姓名
	 */
	public java.lang.String getStaffName() {
		return getStr("staff_name");
	}
	
	/**
	 * 站点编码
	 */
	public void setStationCode(java.lang.String stationCode) {
		set("station_code", stationCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getStationCode() {
		return getStr("station_code");
	}
	
	/**
	 * 身份证编码
	 */
	public void setIdNum(java.lang.String idNum) {
		set("id_num", idNum);
	}
	
	/**
	 * 身份证编码
	 */
	public java.lang.String getIdNum() {
		return getStr("id_num");
	}
	
	/**
	 * 特种设备P证编码
	 */
	public void setSecpNum(java.lang.String secpNum) {
		set("secp_num", secpNum);
	}
	
	/**
	 * 特种设备P证编码
	 */
	public java.lang.String getSecpNum() {
		return getStr("secp_num");
	}
	
	/**
	 * P证有效期开始日期
	 */
	public void setSecpValidBegin(java.util.Date secpValidBegin) {
		set("secp_valid_begin", secpValidBegin);
	}
	
	/**
	 * P证有效期开始日期
	 */
	public java.util.Date getSecpValidBegin() {
		return getDate("secp_valid_begin");
	}
	
	/**
	 * P证有效期截止日期
	 */
	public void setSecpValidEnd(java.util.Date secpValidEnd) {
		set("secp_valid_end", secpValidEnd);
	}
	
	/**
	 * P证有效期截止日期
	 */
	public java.util.Date getSecpValidEnd() {
		return getDate("secp_valid_end");
	}
	
	/**
	 * P证照片
	 */
	public void setSecpImage(java.lang.String secpImage) {
		set("secp_image", secpImage);
	}
	
	/**
	 * P证照片
	 */
	public java.lang.String getSecpImage() {
		return getStr("secp_image");
	}
	
	/**
	 * 燃气从业人员证编码
	 */
	public void setGpcNum(java.lang.String gpcNum) {
		set("gpc_num", gpcNum);
	}
	
	/**
	 * 燃气从业人员证编码
	 */
	public java.lang.String getGpcNum() {
		return getStr("gpc_num");
	}
	
	/**
	 * 从业证有效期开始日期
	 */
	public void setGpcValidBegin(java.util.Date gpcValidBegin) {
		set("gpc_valid_begin", gpcValidBegin);
	}
	
	/**
	 * 从业证有效期开始日期
	 */
	public java.util.Date getGpcValidBegin() {
		return getDate("gpc_valid_begin");
	}
	
	/**
	 * 从业证有效期截止日期
	 */
	public void setGpcValidEnd(java.util.Date gpcValidEnd) {
		set("gpc_valid_end", gpcValidEnd);
	}
	
	/**
	 * 从业证有效期截止日期
	 */
	public java.util.Date getGpcValidEnd() {
		return getDate("gpc_valid_end");
	}
	
	/**
	 * 员工人脸照片
	 */
	public void setFaceImage(java.lang.String faceImage) {
		set("face_image", faceImage);
	}
	
	/**
	 * 员工人脸照片
	 */
	public java.lang.String getFaceImage() {
		return getStr("face_image");
	}
	
	/**
	 * 员工电子签名
	 */
	public void setEsImage(java.lang.String esImage) {
		set("es_image", esImage);
	}
	
	/**
	 * 员工电子签名
	 */
	public java.lang.String getEsImage() {
		return getStr("es_image");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

