package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFunc<M extends BaseFunc<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setFunName(java.lang.String funName) {
		set("fun_name", funName);
	}
	
	public java.lang.String getFunName() {
		return getStr("fun_name");
	}
	
	public void setFunUrl(java.lang.String funUrl) {
		set("fun_url", funUrl);
	}
	
	public java.lang.String getFunUrl() {
		return getStr("fun_url");
	}
	
	public void setFunCreatetime(java.lang.String funCreatetime) {
		set("fun_createtime", funCreatetime);
	}
	
	public java.lang.String getFunCreatetime() {
		return getStr("fun_createtime");
	}
	
	public void setFunCreater(java.lang.String funCreater) {
		set("fun_creater", funCreater);
	}
	
	public java.lang.String getFunCreater() {
		return getStr("fun_creater");
	}
	
	public void setFunParentid(java.lang.Integer funParentid) {
		set("fun_parentid", funParentid);
	}
	
	public java.lang.Integer getFunParentid() {
		return getInt("fun_parentid");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setFunLogo(java.lang.String funLogo) {
		set("fun_logo", funLogo);
	}
	
	public java.lang.String getFunLogo() {
		return getStr("fun_logo");
	}
	
}

