package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户ID
	 */
	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	/**
	 * 部门ID
	 */
	public void setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
	}
	
	/**
	 * 部门ID
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
	/**
	 * 用户账号
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户账号
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 用户昵称
	 */
	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}
	
	/**
	 * 用户类型（sys_user系统用户）
	 */
	public void setUserType(java.lang.String userType) {
		set("user_type", userType);
	}
	
	/**
	 * 用户类型（sys_user系统用户）
	 */
	public java.lang.String getUserType() {
		return getStr("user_type");
	}
	
	/**
	 * 用户邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 用户邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 手机号码
	 */
	public void setPhonenumber(java.lang.String phonenumber) {
		set("phonenumber", phonenumber);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getPhonenumber() {
		return getStr("phonenumber");
	}
	
	/**
	 * 用户性别（0男 1女 2未知）
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	/**
	 * 用户性别（0男 1女 2未知）
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	/**
	 * 头像地址
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像地址
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 所属站点
	 */
	public void setStationId(java.lang.String stationId) {
		set("station_id", stationId);
	}
	
	/**
	 * 所属站点
	 */
	public java.lang.String getStationId() {
		return getStr("station_id");
	}
	
	/**
	 * 角色名
	 */
	public void setCharacterName(java.lang.String characterName) {
		set("character_name", characterName);
	}
	
	/**
	 * 角色名
	 */
	public java.lang.String getCharacterName() {
		return getStr("character_name");
	}
	
	/**
	 * 帐号状态（0正常 1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 帐号状态（0正常 1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}
	
	/**
	 * 最后登录IP
	 */
	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}
	
	/**
	 * 最后登录IP
	 */
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}
	
	/**
	 * 最后登录时间
	 */
	public void setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
	}
	
	/**
	 * 最后登录时间
	 */
	public java.util.Date getLoginDate() {
		return getDate("login_date");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

