package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStationStaff<M extends BaseGasStationStaff<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 员工id
	 */
	public void setStaffId(java.lang.String staffId) {
		set("staff_id", staffId);
	}
	
	/**
	 * 员工id
	 */
	public java.lang.String getStaffId() {
		return getStr("staff_id");
	}
	
	/**
	 * 员工姓名
	 */
	public void setStaffName(java.lang.String staffName) {
		set("staff_name", staffName);
	}
	
	/**
	 * 员工姓名
	 */
	public java.lang.String getStaffName() {
		return getStr("staff_name");
	}
	
	/**
	 * 所属加气站
	 */
	public void setStationId(java.lang.String stationId) {
		set("station_id", stationId);
	}
	
	/**
	 * 所属加气站
	 */
	public java.lang.String getStationId() {
		return getStr("station_id");
	}
	
	/**
	 * 手机号
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
}

