package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKongqianghardware<M extends BaseKongqianghardware<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 硬件名称
	 */
	public void setHardwareno(java.lang.String hardwareno) {
		set("hardwareno", hardwareno);
	}
	
	/**
	 * 硬件名称
	 */
	public java.lang.String getHardwareno() {
		return getStr("hardwareno");
	}
	
	/**
	 * 加气站 id
	 */
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	/**
	 * 加气站 id
	 */
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
	/**
	 * 加气站名称
	 */
	public void setStationname(java.lang.String stationname) {
		set("stationname", stationname);
	}
	
	/**
	 * 加气站名称
	 */
	public java.lang.String getStationname() {
		return getStr("stationname");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}
	
	/**
	 * 创建人
	 */
	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreater() {
		return getStr("creater");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
}

