package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStationEnv<M extends BaseGasStationEnv<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	public void setEnvType(java.lang.String envType) {
		set("env_type", envType);
	}
	
	public java.lang.String getEnvType() {
		return getStr("env_type");
	}
	
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
}

