package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasDocs<M extends BaseGasDocs<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 文件地址
	 */
	public void setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
	}
	
	/**
	 * 文件地址
	 */
	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}
	
	/**
	 * 检验机构
	 */
	public void setInspOrg(java.lang.String inspOrg) {
		set("insp_org", inspOrg);
	}
	
	/**
	 * 检验机构
	 */
	public java.lang.String getInspOrg() {
		return getStr("insp_org");
	}
	
	/**
	 * 检验日期
	 */
	public void setInspData(java.util.Date inspData) {
		set("insp_data", inspData);
	}
	
	/**
	 * 检验日期
	 */
	public java.util.Date getInspData() {
		return getDate("insp_data");
	}
	
	/**
	 * 报告编号
	 */
	public void setReportNo(java.lang.String reportNo) {
		set("report_no", reportNo);
	}
	
	/**
	 * 报告编号
	 */
	public java.lang.String getReportNo() {
		return getStr("report_no");
	}
	
	/**
	 * 合格瓶数
	 */
	public void setQualifiedBottles(java.lang.String qualifiedBottles) {
		set("qualified_bottles", qualifiedBottles);
	}
	
	/**
	 * 合格瓶数
	 */
	public java.lang.String getQualifiedBottles() {
		return getStr("qualified_bottles");
	}
	
	/**
	 * 报废瓶数
	 */
	public void setScrapBottles(java.lang.String scrapBottles) {
		set("scrap_bottles", scrapBottles);
	}
	
	/**
	 * 报废瓶数
	 */
	public java.lang.String getScrapBottles() {
		return getStr("scrap_bottles");
	}
	
	/**
	 * 上传时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 上传用户id
	 */
	public void setCreateUserid(java.lang.Integer createUserid) {
		set("create_userid", createUserid);
	}
	
	/**
	 * 上传用户id
	 */
	public java.lang.Integer getCreateUserid() {
		return getInt("create_userid");
	}
	
}

