package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseFittOperate<M extends BaseBseFittOperate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}
	
	public java.lang.Integer getCount() {
		return getInt("count");
	}
	
	public void setEquipment(java.lang.String equipment) {
		set("equipment", equipment);
	}
	
	public java.lang.String getEquipment() {
		return getStr("equipment");
	}
	
	public void setCreattime(java.util.Date creattime) {
		set("creattime", creattime);
	}
	
	public java.util.Date getCreattime() {
		return getDate("creattime");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
	public void setStaff(java.lang.String staff) {
		set("staff", staff);
	}
	
	public java.lang.String getStaff() {
		return getStr("staff");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setMemory(java.lang.String memory) {
		set("memory", memory);
	}
	
	public java.lang.String getMemory() {
		return getStr("memory");
	}
	
	public void setRemark1(java.lang.String remark1) {
		set("remark1", remark1);
	}
	
	public java.lang.String getRemark1() {
		return getStr("remark1");
	}
	
	public void setRemark2(java.lang.String remark2) {
		set("remark2", remark2);
	}
	
	public java.lang.String getRemark2() {
		return getStr("remark2");
	}
	
	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}
	
}

