package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJiebangding<M extends BaseJiebangding<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setQipingbianma(java.lang.String qipingbianma) {
		set("qipingbianma", qipingbianma);
	}
	
	public java.lang.String getQipingbianma() {
		return getStr("qipingbianma");
	}
	
	public void setChengbianma(java.lang.String chengbianma) {
		set("chengbianma", chengbianma);
	}
	
	public java.lang.String getChengbianma() {
		return getStr("chengbianma");
	}
	
	public void setBangdingshijian(java.lang.String bangdingshijian) {
		set("bangdingshijian", bangdingshijian);
	}
	
	public java.lang.String getBangdingshijian() {
		return getStr("bangdingshijian");
	}
	
	public void setBangdingrendianhua(java.lang.String bangdingrendianhua) {
		set("bangdingrendianhua", bangdingrendianhua);
	}
	
	public java.lang.String getBangdingrendianhua() {
		return getStr("bangdingrendianhua");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setJiebangdingshijian(java.lang.String jiebangdingshijian) {
		set("jiebangdingshijian", jiebangdingshijian);
	}
	
	public java.lang.String getJiebangdingshijian() {
		return getStr("jiebangdingshijian");
	}
	
	public void setJiebangdingrendianhua(java.lang.String jiebangdingrendianhua) {
		set("jiebangdingrendianhua", jiebangdingrendianhua);
	}
	
	public java.lang.String getJiebangdingrendianhua() {
		return getStr("jiebangdingrendianhua");
	}
	
	/**
	 * bangdingqianchushizhongliang
	 */
	public void setBdqcszl(java.lang.String bdqcszl) {
		set("bdqcszl", bdqcszl);
	}
	
	/**
	 * bangdingqianchushizhongliang
	 */
	public java.lang.String getBdqcszl() {
		return getStr("bdqcszl");
	}
	
	/**
	 * bangdingqiandangqianzhongliang
	 */
	public void setBdqdqzl(java.lang.String bdqdqzl) {
		set("bdqdqzl", bdqdqzl);
	}
	
	/**
	 * bangdingqiandangqianzhongliang
	 */
	public java.lang.String getBdqdqzl() {
		return getStr("bdqdqzl");
	}
	
	/**
	 * bangdingqianshiyongzhongliang
	 */
	public void setBdqsyzl(java.lang.String bdqsyzl) {
		set("bdqsyzl", bdqsyzl);
	}
	
	/**
	 * bangdingqianshiyongzhongliang
	 */
	public java.lang.String getBdqsyzl() {
		return getStr("bdqsyzl");
	}
	
	/**
	 * jiebangdinghouchushizhongliang
	 */
	public void setJbdhcszl(java.lang.String jbdhcszl) {
		set("jbdhcszl", jbdhcszl);
	}
	
	/**
	 * jiebangdinghouchushizhongliang
	 */
	public java.lang.String getJbdhcszl() {
		return getStr("jbdhcszl");
	}
	
	/**
	 * jiebangdinghoudangqianzhongliang
	 */
	public void setJbdhdqzl(java.lang.String jbdhdqzl) {
		set("jbdhdqzl", jbdhdqzl);
	}
	
	/**
	 * jiebangdinghoudangqianzhongliang
	 */
	public java.lang.String getJbdhdqzl() {
		return getStr("jbdhdqzl");
	}
	
	/**
	 * jiebangdinghoushiyongzhongliang
	 */
	public void setJbdhsyzl(java.lang.String jbdhsyzl) {
		set("jbdhsyzl", jbdhsyzl);
	}
	
	/**
	 * jiebangdinghoushiyongzhongliang
	 */
	public java.lang.String getJbdhsyzl() {
		return getStr("jbdhsyzl");
	}
	
	public void setShiyongfandianmingzi(java.lang.String shiyongfandianmingzi) {
		set("shiyongfandianmingzi", shiyongfandianmingzi);
	}
	
	public java.lang.String getShiyongfandianmingzi() {
		return getStr("shiyongfandianmingzi");
	}
	
	public void setBangdingren(java.lang.String bangdingren) {
		set("bangdingren", bangdingren);
	}
	
	public java.lang.String getBangdingren() {
		return getStr("bangdingren");
	}
	
	public void setJiebangren(java.lang.String jiebangren) {
		set("jiebangren", jiebangren);
	}
	
	public java.lang.String getJiebangren() {
		return getStr("jiebangren");
	}
	
	/**
	 * 闃€闂?
	 */
	public void setFaMen(java.lang.Integer faMen) {
		set("faMen", faMen);
	}
	
	/**
	 * 闃€闂?
	 */
	public java.lang.Integer getFaMen() {
		return getInt("faMen");
	}
	
	/**
	 * 饭店地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 饭店地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 饭店电话
	 */
	public void setShiyongfandiantelephone(java.lang.String shiyongfandiantelephone) {
		set("shiyongfandiantelephone", shiyongfandiantelephone);
	}
	
	/**
	 * 饭店电话
	 */
	public java.lang.String getShiyongfandiantelephone() {
		return getStr("shiyongfandiantelephone");
	}
	
	public void setChangeTime(java.lang.String changeTime) {
		set("change_time", changeTime);
	}
	
	public java.lang.String getChangeTime() {
		return getStr("change_time");
	}
	
	public void setChangeGas(java.lang.String changeGas) {
		set("change_gas", changeGas);
	}
	
	public java.lang.String getChangeGas() {
		return getStr("change_gas");
	}
	
	public void setDanjia(java.lang.String danjia) {
		set("danjia", danjia);
	}
	
	public java.lang.String getDanjia() {
		return getStr("danjia");
	}
	
}

