package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScpVideo<M extends BaseScpVideo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCareerName(java.lang.String careerName) {
		set("career_name", careerName);
	}
	
	public java.lang.String getCareerName() {
		return getStr("career_name");
	}
	
	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}
	
	public void setCollectorNum(java.lang.String collectorNum) {
		set("collector_num", collectorNum);
	}
	
	public java.lang.String getCollectorNum() {
		return getStr("collector_num");
	}
	
	public void setRemake(java.lang.String remake) {
		set("remake", remake);
	}
	
	public java.lang.String getRemake() {
		return getStr("remake");
	}
	
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setWatchNumber(java.lang.String watchNumber) {
		set("watch_number", watchNumber);
	}
	
	public java.lang.String getWatchNumber() {
		return getStr("watch_number");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}
	
	/**
	 * 创建时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}
	
}

