package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManageXiaohezi<M extends BaseManageXiaohezi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setXiaoheziNo(java.lang.String xiaoheziNo) {
		set("xiaohezi_no", xiaoheziNo);
	}
	
	public java.lang.String getXiaoheziNo() {
		return getStr("xiaohezi_no");
	}
	
	public void setRestaurantid(java.lang.String restaurantid) {
		set("restaurantid", restaurantid);
	}
	
	public java.lang.String getRestaurantid() {
		return getStr("restaurantid");
	}
	
	public void setFamen1open(java.lang.String famen1open) {
		set("famen1open", famen1open);
	}
	
	public java.lang.String getFamen1open() {
		return getStr("famen1open");
	}
	
	public void setFamen1close(java.lang.String famen1close) {
		set("famen1close", famen1close);
	}
	
	public java.lang.String getFamen1close() {
		return getStr("famen1close");
	}
	
	public void setFamen2open(java.lang.String famen2open) {
		set("famen2open", famen2open);
	}
	
	public java.lang.String getFamen2open() {
		return getStr("famen2open");
	}
	
	public void setFamen2close(java.lang.String famen2close) {
		set("famen2close", famen2close);
	}
	
	public java.lang.String getFamen2close() {
		return getStr("famen2close");
	}
	
	public void setFamen3open(java.lang.String famen3open) {
		set("famen3open", famen3open);
	}
	
	public java.lang.String getFamen3open() {
		return getStr("famen3open");
	}
	
	public void setFamen3close(java.lang.String famen3close) {
		set("famen3close", famen3close);
	}
	
	public java.lang.String getFamen3close() {
		return getStr("famen3close");
	}
	
	public void setFamen4open(java.lang.String famen4open) {
		set("famen4open", famen4open);
	}
	
	public java.lang.String getFamen4open() {
		return getStr("famen4open");
	}
	
	public void setFamen4close(java.lang.String famen4close) {
		set("famen4close", famen4close);
	}
	
	public java.lang.String getFamen4close() {
		return getStr("famen4close");
	}
	
	public void setFamen5open(java.lang.String famen5open) {
		set("famen5open", famen5open);
	}
	
	public java.lang.String getFamen5open() {
		return getStr("famen5open");
	}
	
	public void setFamen5close(java.lang.String famen5close) {
		set("famen5close", famen5close);
	}
	
	public java.lang.String getFamen5close() {
		return getStr("famen5close");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setYuliu1(java.lang.String yuliu1) {
		set("yuliu1", yuliu1);
	}
	
	public java.lang.String getYuliu1() {
		return getStr("yuliu1");
	}
	
	public void setYuliu2(java.lang.String yuliu2) {
		set("yuliu2", yuliu2);
	}
	
	public java.lang.String getYuliu2() {
		return getStr("yuliu2");
	}
	
	public void setRestaurant(java.lang.String restaurant) {
		set("restaurant", restaurant);
	}
	
	public java.lang.String getRestaurant() {
		return getStr("restaurant");
	}
	
}

