package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppManage<M extends BaseAppManage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * app编码，一个app对应一个编码,自动生成
	 */
	public void setAppcode(java.lang.String appcode) {
		set("appcode", appcode);
	}
	
	/**
	 * app编码，一个app对应一个编码,自动生成
	 */
	public java.lang.String getAppcode() {
		return getStr("appcode");
	}
	
	/**
	 * app名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * app名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * app文件
	 */
	public void setFile(java.lang.String file) {
		set("file", file);
	}
	
	/**
	 * app文件
	 */
	public java.lang.String getFile() {
		return getStr("file");
	}
	
	/**
	 * app版本号
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * app版本号
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 更新内容说明
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 更新内容说明
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 是否强制更新，1是0否
	 */
	public void setIsforce(java.lang.Integer isforce) {
		set("isforce", isforce);
	}
	
	/**
	 * 是否强制更新，1是0否
	 */
	public java.lang.Integer getIsforce() {
		return getInt("isforce");
	}
	
}

