package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseCompanyCopy1<M extends BaseBseCompanyCopy1<M>> extends Model<M> implements IBean {

	/**
	 * 加油站id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 加油站id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 加油站名字名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 加油站名字名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 加油站地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 加油站地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 加油站登录账号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 加油站登录账号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 授权码
	 */
	public void setToken(java.lang.String token) {
		set("token", token);
	}
	
	/**
	 * 授权码
	 */
	public java.lang.String getToken() {
		return getStr("token");
	}
	
	/**
	 * 预留字段
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}
	
	/**
	 * 预留字段
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 加油站登录密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 加油站登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 加油站星级
	 */
	public void setStarlevel(java.lang.String starlevel) {
		set("starlevel", starlevel);
	}
	
	/**
	 * 加油站星级
	 */
	public java.lang.String getStarlevel() {
		return getStr("starlevel");
	}
	
	/**
	 * 记录录入人的信息
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 记录录入人的信息
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间
	 */
	public void setWritetime(java.lang.String writetime) {
		set("writetime", writetime);
	}
	
	/**
	 * 录入时间
	 */
	public java.lang.String getWritetime() {
		return getStr("writetime");
	}
	
	/**
	 * 预留字段
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 预留字段
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
}

