package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBottlePerson<M extends BaseBottlePerson<M>> extends Model<M> implements IBean {

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}
	
	public void setPersonSend(java.lang.String personSend) {
		set("person_send", personSend);
	}
	
	public java.lang.String getPersonSend() {
		return getStr("person_send");
	}
	
	public void setPersonUninstall(java.lang.String personUninstall) {
		set("person_uninstall", personUninstall);
	}
	
	public java.lang.String getPersonUninstall() {
		return getStr("person_uninstall");
	}
	
	public void setPersonReceiver(java.lang.String personReceiver) {
		set("person_receiver", personReceiver);
	}
	
	public java.lang.String getPersonReceiver() {
		return getStr("person_receiver");
	}
	
}

