package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}
	
	/**
	 * 角色名称
	 */
	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}
	
	/**
	 * 角色名称
	 */
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}
	
	/**
	 * 角色权限字符串
	 */
	public void setRoleKey(java.lang.String roleKey) {
		set("role_key", roleKey);
	}
	
	/**
	 * 角色权限字符串
	 */
	public java.lang.String getRoleKey() {
		return getStr("role_key");
	}
	
	/**
	 * 显示顺序
	 */
	public void setRoleSort(java.lang.Integer roleSort) {
		set("role_sort", roleSort);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getRoleSort() {
		return getInt("role_sort");
	}
	
	/**
	 * 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	 */
	public void setDataScope(java.lang.String dataScope) {
		set("data_scope", dataScope);
	}
	
	/**
	 * 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	 */
	public java.lang.String getDataScope() {
		return getStr("data_scope");
	}
	
	/**
	 * 菜单树选择项是否关联显示
	 */
	public void setMenuCheckStrictly(java.lang.Boolean menuCheckStrictly) {
		set("menu_check_strictly", menuCheckStrictly);
	}
	
	/**
	 * 菜单树选择项是否关联显示
	 */
	public java.lang.Boolean getMenuCheckStrictly() {
		return get("menu_check_strictly");
	}
	
	/**
	 * 部门树选择项是否关联显示
	 */
	public void setDeptCheckStrictly(java.lang.Boolean deptCheckStrictly) {
		set("dept_check_strictly", deptCheckStrictly);
	}
	
	/**
	 * 部门树选择项是否关联显示
	 */
	public java.lang.Boolean getDeptCheckStrictly() {
		return get("dept_check_strictly");
	}
	
	/**
	 * 角色状态（0正常 1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 角色状态（0正常 1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

