package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzFiredTriggers<M extends BaseQrtzFiredTriggers<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * 调度器实例id
	 */
	public void setEntryId(java.lang.String entryId) {
		set("entry_id", entryId);
	}
	
	/**
	 * 调度器实例id
	 */
	public java.lang.String getEntryId() {
		return getStr("entry_id");
	}
	
	/**
	 * qrtz_triggers表trigger_name的外键
	 */
	public void setTriggerName(java.lang.String triggerName) {
		set("trigger_name", triggerName);
	}
	
	/**
	 * qrtz_triggers表trigger_name的外键
	 */
	public java.lang.String getTriggerName() {
		return getStr("trigger_name");
	}
	
	/**
	 * qrtz_triggers表trigger_group的外键
	 */
	public void setTriggerGroup(java.lang.String triggerGroup) {
		set("trigger_group", triggerGroup);
	}
	
	/**
	 * qrtz_triggers表trigger_group的外键
	 */
	public java.lang.String getTriggerGroup() {
		return getStr("trigger_group");
	}
	
	/**
	 * 调度器实例名
	 */
	public void setInstanceName(java.lang.String instanceName) {
		set("instance_name", instanceName);
	}
	
	/**
	 * 调度器实例名
	 */
	public java.lang.String getInstanceName() {
		return getStr("instance_name");
	}
	
	/**
	 * 触发的时间
	 */
	public void setFiredTime(java.lang.Long firedTime) {
		set("fired_time", firedTime);
	}
	
	/**
	 * 触发的时间
	 */
	public java.lang.Long getFiredTime() {
		return getLong("fired_time");
	}
	
	/**
	 * 定时器制定的时间
	 */
	public void setSchedTime(java.lang.Long schedTime) {
		set("sched_time", schedTime);
	}
	
	/**
	 * 定时器制定的时间
	 */
	public java.lang.Long getSchedTime() {
		return getLong("sched_time");
	}
	
	/**
	 * 优先级
	 */
	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}
	
	/**
	 * 优先级
	 */
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}
	
	/**
	 * 状态
	 */
	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getState() {
		return getStr("state");
	}
	
	/**
	 * 任务名称
	 */
	public void setJobName(java.lang.String jobName) {
		set("job_name", jobName);
	}
	
	/**
	 * 任务名称
	 */
	public java.lang.String getJobName() {
		return getStr("job_name");
	}
	
	/**
	 * 任务组名
	 */
	public void setJobGroup(java.lang.String jobGroup) {
		set("job_group", jobGroup);
	}
	
	/**
	 * 任务组名
	 */
	public java.lang.String getJobGroup() {
		return getStr("job_group");
	}
	
	/**
	 * 是否并发
	 */
	public void setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("is_nonconcurrent", isNonconcurrent);
	}
	
	/**
	 * 是否并发
	 */
	public java.lang.String getIsNonconcurrent() {
		return getStr("is_nonconcurrent");
	}
	
	/**
	 * 是否接受恢复执行
	 */
	public void setRequestsRecovery(java.lang.String requestsRecovery) {
		set("requests_recovery", requestsRecovery);
	}
	
	/**
	 * 是否接受恢复执行
	 */
	public java.lang.String getRequestsRecovery() {
		return getStr("requests_recovery");
	}
	
}

