package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStaffWorkCheck<M extends BaseGasStaffWorkCheck<M>> extends Model<M> implements IBean {

	/**
	 * 主键标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 验证生效日期
	 */
	public void setCheckDate(java.lang.String checkDate) {
		set("check_date", checkDate);
	}
	
	/**
	 * 验证生效日期
	 */
	public java.lang.String getCheckDate() {
		return getStr("check_date");
	}
	
	/**
	 * 验证失效日期
	 */
	public void setValidDate(java.lang.String validDate) {
		set("valid_date", validDate);
	}
	
	/**
	 * 验证失效日期
	 */
	public java.lang.String getValidDate() {
		return getStr("valid_date");
	}
	
	/**
	 * 站点编码
	 */
	public void setStationCode(java.lang.String stationCode) {
		set("station_code", stationCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getStationCode() {
		return getStr("station_code");
	}
	
	/**
	 * 员工ID
	 */
	public void setStaffId(java.lang.String staffId) {
		set("staff_id", staffId);
	}
	
	/**
	 * 员工ID
	 */
	public java.lang.String getStaffId() {
		return getStr("staff_id");
	}
	
	/**
	 * 员工姓名
	 */
	public void setStaffName(java.lang.String staffName) {
		set("staff_name", staffName);
	}
	
	/**
	 * 员工姓名
	 */
	public java.lang.String getStaffName() {
		return getStr("staff_name");
	}
	
	/**
	 * 认证信息ID
	 */
	public void setCertificateId(java.lang.Integer certificateId) {
		set("certificate_id", certificateId);
	}
	
	/**
	 * 认证信息ID
	 */
	public java.lang.Integer getCertificateId() {
		return getInt("certificate_id");
	}
	
	/**
	 * 验证照片
	 */
	public void setFaceImage(java.lang.String faceImage) {
		set("face_image", faceImage);
	}
	
	/**
	 * 验证照片
	 */
	public java.lang.String getFaceImage() {
		return getStr("face_image");
	}
	
	/**
	 * 电子签名
	 */
	public void setEsImage(java.lang.String esImage) {
		set("es_image", esImage);
	}
	
	/**
	 * 电子签名
	 */
	public java.lang.String getEsImage() {
		return getStr("es_image");
	}
	
	/**
	 * 身份证号码
	 */
	public void setIdNum(java.lang.String idNum) {
		set("id_num", idNum);
	}
	
	/**
	 * 身份证号码
	 */
	public java.lang.String getIdNum() {
		return getStr("id_num");
	}
	
	/**
	 * 特种设备P证编码
	 */
	public void setSecpNum(java.lang.String secpNum) {
		set("secp_num", secpNum);
	}
	
	/**
	 * 特种设备P证编码
	 */
	public java.lang.String getSecpNum() {
		return getStr("secp_num");
	}
	
	/**
	 * P证有效期开始日期
	 */
	public void setSecpValidBegin(java.util.Date secpValidBegin) {
		set("secp_valid_begin", secpValidBegin);
	}
	
	/**
	 * P证有效期开始日期
	 */
	public java.util.Date getSecpValidBegin() {
		return getDate("secp_valid_begin");
	}
	
	/**
	 * P证有效期截止日期
	 */
	public void setSecpValidEnd(java.util.Date secpValidEnd) {
		set("secp_valid_end", secpValidEnd);
	}
	
	/**
	 * P证有效期截止日期
	 */
	public java.util.Date getSecpValidEnd() {
		return getDate("secp_valid_end");
	}
	
	/**
	 * 燃气从业人员证编码
	 */
	public void setGpcNum(java.lang.String gpcNum) {
		set("gpc_num", gpcNum);
	}
	
	/**
	 * 燃气从业人员证编码
	 */
	public java.lang.String getGpcNum() {
		return getStr("gpc_num");
	}
	
	/**
	 * 从业证有效期开始日期
	 */
	public void setGpcValidBegin(java.util.Date gpcValidBegin) {
		set("gpc_valid_begin", gpcValidBegin);
	}
	
	/**
	 * 从业证有效期开始日期
	 */
	public java.util.Date getGpcValidBegin() {
		return getDate("gpc_valid_begin");
	}
	
	/**
	 * 从业证有效期截止日期
	 */
	public void setGpcValidEnd(java.util.Date gpcValidEnd) {
		set("gpc_valid_end", gpcValidEnd);
	}
	
	/**
	 * 从业证有效期截止日期
	 */
	public java.util.Date getGpcValidEnd() {
		return getDate("gpc_valid_end");
	}
	
	/**
	 * 人脸相似度
	 */
	public void setScore(java.lang.String score) {
		set("score", score);
	}
	
	/**
	 * 人脸相似度
	 */
	public java.lang.String getScore() {
		return getStr("score");
	}
	
}

