package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDianzicheng<M extends BaseDianzicheng<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setBianma(java.lang.String bianma) {
		set("bianma", bianma);
	}
	
	public java.lang.String getBianma() {
		return getStr("bianma");
	}
	
	/**
	 * 秤在阿里云的名字
	 */
	public void setAlichengmingzi(java.lang.String alichengmingzi) {
		set("alichengmingzi", alichengmingzi);
	}
	
	/**
	 * 秤在阿里云的名字
	 */
	public java.lang.String getAlichengmingzi() {
		return getStr("alichengmingzi");
	}
	
	/**
	 * 生产厂家
	 */
	public void setShengchangchangjia(java.lang.String shengchangchangjia) {
		set("shengchangchangjia", shengchangchangjia);
	}
	
	/**
	 * 生产厂家
	 */
	public java.lang.String getShengchangchangjia() {
		return getStr("shengchangchangjia");
	}
	
	public void setShengchanriqi(java.lang.String shengchanriqi) {
		set("shengchanriqi", shengchanriqi);
	}
	
	public java.lang.String getShengchanriqi() {
		return getStr("shengchanriqi");
	}
	
	public void setZhuceriqi(java.lang.String zhuceriqi) {
		set("zhuceriqi", zhuceriqi);
	}
	
	public java.lang.String getZhuceriqi() {
		return getStr("zhuceriqi");
	}
	
	/**
	 * 饭店id，这个和shiyongfangmingzi，shiyognfangphone都是指向一个饭店
	 */
	public void setShiyongfangphoneid(java.lang.Integer shiyongfangphoneid) {
		set("shiyongfangphoneid", shiyongfangphoneid);
	}
	
	/**
	 * 饭店id，这个和shiyongfangmingzi，shiyognfangphone都是指向一个饭店
	 */
	public java.lang.Integer getShiyongfangphoneid() {
		return getInt("shiyongfangphoneid");
	}
	
	/**
	 * 浣跨敤鐨勯キ搴梚d鍜屽悕瀛?
	 */
	public void setShiyongfangphone(java.lang.String shiyongfangphone) {
		set("shiyongfangphone", shiyongfangphone);
	}
	
	/**
	 * 浣跨敤鐨勯キ搴梚d鍜屽悕瀛?
	 */
	public java.lang.String getShiyongfangphone() {
		return getStr("shiyongfangphone");
	}
	
	/**
	 * 使用饭店名字
	 */
	public void setShiyongfandianmingzi(java.lang.String shiyongfandianmingzi) {
		set("shiyongfandianmingzi", shiyongfandianmingzi);
	}
	
	/**
	 * 使用饭店名字
	 */
	public java.lang.String getShiyongfandianmingzi() {
		return getStr("shiyongfandianmingzi");
	}
	
	/**
	 * 打开阀门
	 */
	public void setDakaifamen(java.lang.String dakaifamen) {
		set("dakaifamen", dakaifamen);
	}
	
	/**
	 * 打开阀门
	 */
	public java.lang.String getDakaifamen() {
		return getStr("dakaifamen");
	}
	
	/**
	 * 关闭阀门
	 */
	public void setGuanbifamen(java.lang.String guanbifamen) {
		set("guanbifamen", guanbifamen);
	}
	
	/**
	 * 关闭阀门
	 */
	public java.lang.String getGuanbifamen() {
		return getStr("guanbifamen");
	}
	
	/**
	 * 获取秤的全部状态信息
	 */
	public void setHuoquchengxinxi(java.lang.String huoquchengxinxi) {
		set("huoquchengxinxi", huoquchengxinxi);
	}
	
	/**
	 * 获取秤的全部状态信息
	 */
	public java.lang.String getHuoquchengxinxi() {
		return getStr("huoquchengxinxi");
	}
	
	/**
	 * 获取警报，这个信息通常也可以通过huoquchengxinxi获得
	 */
	public void setHuoqujingbao(java.lang.String huoqujingbao) {
		set("huoqujingbao", huoqujingbao);
	}
	
	/**
	 * 获取警报，这个信息通常也可以通过huoquchengxinxi获得
	 */
	public java.lang.String getHuoqujingbao() {
		return getStr("huoqujingbao");
	}
	
	/**
	 * 打开警报
	 */
	public void setDakaijingbao(java.lang.String dakaijingbao) {
		set("dakaijingbao", dakaijingbao);
	}
	
	/**
	 * 打开警报
	 */
	public java.lang.String getDakaijingbao() {
		return getStr("dakaijingbao");
	}
	
	/**
	 * 关闭警报
	 */
	public void setGuanbijingbao(java.lang.String guanbijingbao) {
		set("guanbijingbao", guanbijingbao);
	}
	
	/**
	 * 关闭警报
	 */
	public java.lang.String getGuanbijingbao() {
		return getStr("guanbijingbao");
	}
	
	/**
	 * 秤的状态。10是添加完成。20是经过初始重量测量，饭店可以使用；30是不可以使用。
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 秤的状态。10是添加完成。20是经过初始重量测量，饭店可以使用；30是不可以使用。
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 预留1--用于记录是几号称，1，2，3，4分别代表4个称
	 */
	public void setYuliu1(java.lang.String yuliu1) {
		set("yuliu1", yuliu1);
	}
	
	/**
	 * 预留1--用于记录是几号称，1，2，3，4分别代表4个称
	 */
	public java.lang.String getYuliu1() {
		return getStr("yuliu1");
	}
	
	/**
	 * 预留2
	 */
	public void setYuliu2(java.lang.String yuliu2) {
		set("yuliu2", yuliu2);
	}
	
	/**
	 * 预留2
	 */
	public java.lang.String getYuliu2() {
		return getStr("yuliu2");
	}
	
	/**
	 * 预留3
	 */
	public void setYuliu3(java.lang.String yuliu3) {
		set("yuliu3", yuliu3);
	}
	
	/**
	 * 预留3
	 */
	public java.lang.String getYuliu3() {
		return getStr("yuliu3");
	}
	
	/**
	 * 这个用来解释预留的三个命令的位置
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 这个用来解释预留的三个命令的位置
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setBangdingjiekou(java.lang.String bangdingjiekou) {
		set("bangdingjiekou", bangdingjiekou);
	}
	
	public java.lang.String getBangdingjiekou() {
		return getStr("bangdingjiekou");
	}
	
	public void setJiebangdingjiekou(java.lang.String jiebangdingjiekou) {
		set("jiebangdingjiekou", jiebangdingjiekou);
	}
	
	public java.lang.String getJiebangdingjiekou() {
		return getStr("jiebangdingjiekou");
	}
	
}

