package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysConfig<M extends BaseSysConfig<M>> extends Model<M> implements IBean {

	/**
	 * 参数主键
	 */
	public void setConfigId(java.lang.Long configId) {
		set("config_id", configId);
	}
	
	/**
	 * 参数主键
	 */
	public java.lang.Long getConfigId() {
		return getLong("config_id");
	}
	
	/**
	 * 参数名称
	 */
	public void setConfigName(java.lang.String configName) {
		set("config_name", configName);
	}
	
	/**
	 * 参数名称
	 */
	public java.lang.String getConfigName() {
		return getStr("config_name");
	}
	
	/**
	 * 参数键名
	 */
	public void setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
	}
	
	/**
	 * 参数键名
	 */
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}
	
	/**
	 * 参数键值
	 */
	public void setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
	}
	
	/**
	 * 参数键值
	 */
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}
	
	/**
	 * 系统内置（Y是 N否）
	 */
	public void setConfigType(java.lang.String configType) {
		set("config_type", configType);
	}
	
	/**
	 * 系统内置（Y是 N否）
	 */
	public java.lang.String getConfigType() {
		return getStr("config_type");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

