package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseInterval<M extends BaseBseInterval<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCompanyid(java.lang.Integer companyid) {
		set("companyid", companyid);
	}
	
	public java.lang.Integer getCompanyid() {
		return getInt("companyid");
	}
	
	public void setEquipmentid(java.lang.Integer equipmentid) {
		set("equipmentid", equipmentid);
	}
	
	public java.lang.Integer getEquipmentid() {
		return getInt("equipmentid");
	}
	
	public void setFittingid(java.lang.Integer fittingid) {
		set("fittingid", fittingid);
	}
	
	public java.lang.Integer getFittingid() {
		return getInt("fittingid");
	}
	
	public void setKind(java.lang.String kind) {
		set("kind", kind);
	}
	
	public java.lang.String getKind() {
		return getStr("kind");
	}
	
	public void setTime(java.lang.Integer time) {
		set("time", time);
	}
	
	public java.lang.Integer getTime() {
		return getInt("time");
	}
	
	public void setWarn(java.lang.Integer warn) {
		set("warn", warn);
	}
	
	public java.lang.Integer getWarn() {
		return getInt("warn");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setMemo(java.lang.Integer memo) {
		set("memo", memo);
	}
	
	public java.lang.Integer getMemo() {
		return getInt("memo");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	public void setWritetime(java.lang.String writetime) {
		set("writetime", writetime);
	}
	
	public java.lang.String getWritetime() {
		return getStr("writetime");
	}
	
}

