package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseXiaohezi<M extends BaseBseXiaohezi<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 第一个输入框的二维码数值
	 */
	public void setGasNumber1(java.lang.String gasNumber1) {
		set("gas_number1", gasNumber1);
	}
	
	/**
	 * 第一个输入框的二维码数值
	 */
	public java.lang.String getGasNumber1() {
		return getStr("gas_number1");
	}
	
	/**
	 * 第一个输入框对应的小盒子数值
	 */
	public void setTongdao1(java.lang.Integer tongdao1) {
		set("tongdao1", tongdao1);
	}
	
	/**
	 * 第一个输入框对应的小盒子数值
	 */
	public java.lang.Integer getTongdao1() {
		return getInt("tongdao1");
	}
	
	/**
	 * 第二个输入框的二维码数值
	 */
	public void setGasNumber2(java.lang.String gasNumber2) {
		set("gas_number2", gasNumber2);
	}
	
	/**
	 * 第二个输入框的二维码数值
	 */
	public java.lang.String getGasNumber2() {
		return getStr("gas_number2");
	}
	
	/**
	 * 第二个输入框的小盒子数值
	 */
	public void setTongdao2(java.lang.Integer tongdao2) {
		set("tongdao2", tongdao2);
	}
	
	/**
	 * 第二个输入框的小盒子数值
	 */
	public java.lang.Integer getTongdao2() {
		return getInt("tongdao2");
	}
	
	/**
	 * 第三个输入框的二维码数值
	 */
	public void setGasNumber3(java.lang.String gasNumber3) {
		set("gas_number3", gasNumber3);
	}
	
	/**
	 * 第三个输入框的二维码数值
	 */
	public java.lang.String getGasNumber3() {
		return getStr("gas_number3");
	}
	
	/**
	 * 第三个输入框对应的小盒子数值
	 */
	public void setTongdao3(java.lang.Integer tongdao3) {
		set("tongdao3", tongdao3);
	}
	
	/**
	 * 第三个输入框对应的小盒子数值
	 */
	public java.lang.Integer getTongdao3() {
		return getInt("tongdao3");
	}
	
	/**
	 * 第四个输入框的二维码数值
	 */
	public void setGasNumber4(java.lang.String gasNumber4) {
		set("gas_number4", gasNumber4);
	}
	
	/**
	 * 第四个输入框的二维码数值
	 */
	public java.lang.String getGasNumber4() {
		return getStr("gas_number4");
	}
	
	/**
	 * 第四个输入框对应的小盒子数值
	 */
	public void setTongdao4(java.lang.Integer tongdao4) {
		set("tongdao4", tongdao4);
	}
	
	/**
	 * 第四个输入框对应的小盒子数值
	 */
	public java.lang.Integer getTongdao4() {
		return getInt("tongdao4");
	}
	
	/**
	 * 小盒子编号
	 */
	public void setXiaoheziNumber(java.lang.String xiaoheziNumber) {
		set("xiaohezi_number", xiaoheziNumber);
	}
	
	/**
	 * 小盒子编号
	 */
	public java.lang.String getXiaoheziNumber() {
		return getStr("xiaohezi_number");
	}
	
	/**
	 * 安装人
	 */
	public void setWorker(java.lang.String worker) {
		set("worker", worker);
	}
	
	/**
	 * 安装人
	 */
	public java.lang.String getWorker() {
		return getStr("worker");
	}
	
	public void setJingdu(java.lang.String jingdu) {
		set("jingdu", jingdu);
	}
	
	public java.lang.String getJingdu() {
		return getStr("jingdu");
	}
	
	public void setWeidu(java.lang.String weidu) {
		set("weidu", weidu);
	}
	
	public java.lang.String getWeidu() {
		return getStr("weidu");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setYuliu(java.lang.String yuliu) {
		set("yuliu", yuliu);
	}
	
	public java.lang.String getYuliu() {
		return getStr("yuliu");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setCreattime(java.util.Date creattime) {
		set("creattime", creattime);
	}
	
	public java.util.Date getCreattime() {
		return getDate("creattime");
	}
	
}

