package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenTable<M extends BaseGenTable<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setTableId(java.lang.Long tableId) {
		set("table_id", tableId);
	}
	
	/**
	 * 编号
	 */
	public java.lang.Long getTableId() {
		return getLong("table_id");
	}
	
	/**
	 * 表名称
	 */
	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	/**
	 * 表名称
	 */
	public java.lang.String getTableName() {
		return getStr("table_name");
	}
	
	/**
	 * 表描述
	 */
	public void setTableComment(java.lang.String tableComment) {
		set("table_comment", tableComment);
	}
	
	/**
	 * 表描述
	 */
	public java.lang.String getTableComment() {
		return getStr("table_comment");
	}
	
	/**
	 * 关联子表的表名
	 */
	public void setSubTableName(java.lang.String subTableName) {
		set("sub_table_name", subTableName);
	}
	
	/**
	 * 关联子表的表名
	 */
	public java.lang.String getSubTableName() {
		return getStr("sub_table_name");
	}
	
	/**
	 * 子表关联的外键名
	 */
	public void setSubTableFkName(java.lang.String subTableFkName) {
		set("sub_table_fk_name", subTableFkName);
	}
	
	/**
	 * 子表关联的外键名
	 */
	public java.lang.String getSubTableFkName() {
		return getStr("sub_table_fk_name");
	}
	
	/**
	 * 实体类名称
	 */
	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}
	
	/**
	 * 实体类名称
	 */
	public java.lang.String getClassName() {
		return getStr("class_name");
	}
	
	/**
	 * 使用的模板（crud单表操作 tree树表操作）
	 */
	public void setTplCategory(java.lang.String tplCategory) {
		set("tpl_category", tplCategory);
	}
	
	/**
	 * 使用的模板（crud单表操作 tree树表操作）
	 */
	public java.lang.String getTplCategory() {
		return getStr("tpl_category");
	}
	
	/**
	 * 生成包路径
	 */
	public void setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
	}
	
	/**
	 * 生成包路径
	 */
	public java.lang.String getPackageName() {
		return getStr("package_name");
	}
	
	/**
	 * 生成模块名
	 */
	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}
	
	/**
	 * 生成模块名
	 */
	public java.lang.String getModuleName() {
		return getStr("module_name");
	}
	
	/**
	 * 生成业务名
	 */
	public void setBusinessName(java.lang.String businessName) {
		set("business_name", businessName);
	}
	
	/**
	 * 生成业务名
	 */
	public java.lang.String getBusinessName() {
		return getStr("business_name");
	}
	
	/**
	 * 生成功能名
	 */
	public void setFunctionName(java.lang.String functionName) {
		set("function_name", functionName);
	}
	
	/**
	 * 生成功能名
	 */
	public java.lang.String getFunctionName() {
		return getStr("function_name");
	}
	
	/**
	 * 生成功能作者
	 */
	public void setFunctionAuthor(java.lang.String functionAuthor) {
		set("function_author", functionAuthor);
	}
	
	/**
	 * 生成功能作者
	 */
	public java.lang.String getFunctionAuthor() {
		return getStr("function_author");
	}
	
	/**
	 * 生成代码方式（0zip压缩包 1自定义路径）
	 */
	public void setGenType(java.lang.String genType) {
		set("gen_type", genType);
	}
	
	/**
	 * 生成代码方式（0zip压缩包 1自定义路径）
	 */
	public java.lang.String getGenType() {
		return getStr("gen_type");
	}
	
	/**
	 * 生成路径（不填默认项目路径）
	 */
	public void setGenPath(java.lang.String genPath) {
		set("gen_path", genPath);
	}
	
	/**
	 * 生成路径（不填默认项目路径）
	 */
	public java.lang.String getGenPath() {
		return getStr("gen_path");
	}
	
	/**
	 * 其它生成选项
	 */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}
	
	/**
	 * 其它生成选项
	 */
	public java.lang.String getOptions() {
		return getStr("options");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

