package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 日志模块
	 */
	public void setModule(java.lang.String module) {
		set("module", module);
	}
	
	/**
	 * 日志模块
	 */
	public java.lang.String getModule() {
		return getStr("module");
	}
	
	/**
	 * 请求方式
	 */
	public void setRequestMethod(java.lang.String requestMethod) {
		set("request_method", requestMethod);
	}
	
	/**
	 * 请求方式
	 */
	public java.lang.String getRequestMethod() {
		return getStr("request_method");
	}
	
	/**
	 * 请求参数(批量请求参数可能会超过text)
	 */
	public void setRequestParams(java.lang.String requestParams) {
		set("request_params", requestParams);
	}
	
	/**
	 * 请求参数(批量请求参数可能会超过text)
	 */
	public java.lang.String getRequestParams() {
		return getStr("request_params");
	}
	
	/**
	 * 返回参数
	 */
	public void setResponseContent(java.lang.String responseContent) {
		set("response_content", responseContent);
	}
	
	/**
	 * 返回参数
	 */
	public java.lang.String getResponseContent() {
		return getStr("response_content");
	}
	
	/**
	 * 日志内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 日志内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 请求路径
	 */
	public void setRequestUri(java.lang.String requestUri) {
		set("request_uri", requestUri);
	}
	
	/**
	 * 请求路径
	 */
	public java.lang.String getRequestUri() {
		return getStr("request_uri");
	}
	
	/**
	 * 方法名
	 */
	public void setMethod(java.lang.String method) {
		set("method", method);
	}
	
	/**
	 * 方法名
	 */
	public java.lang.String getMethod() {
		return getStr("method");
	}
	
	/**
	 * IP地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * IP地址
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}
	
	/**
	 * 省份
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省份
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}
	
	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}
	
	/**
	 * 执行时间(ms)
	 */
	public void setExecutionTime(java.lang.Long executionTime) {
		set("execution_time", executionTime);
	}
	
	/**
	 * 执行时间(ms)
	 */
	public java.lang.Long getExecutionTime() {
		return getLong("execution_time");
	}
	
	/**
	 * 浏览器
	 */
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	/**
	 * 浏览器
	 */
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	/**
	 * 浏览器版本
	 */
	public void setBrowserVersion(java.lang.String browserVersion) {
		set("browser_version", browserVersion);
	}
	
	/**
	 * 浏览器版本
	 */
	public java.lang.String getBrowserVersion() {
		return getStr("browser_version");
	}
	
	/**
	 * 终端系统
	 */
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	/**
	 * 终端系统
	 */
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	/**
	 * 创建人ID
	 */
	public void setCreateBy(java.lang.Long createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Long getCreateBy() {
		return getLong("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 逻辑删除标识(1-已删除 0-未删除)
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 逻辑删除标识(1-已删除 0-未删除)
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
}

