package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotGroupMember<M extends BaseIotGroupMember<M>> extends Model<M> implements IBean {

	/**
	 * 记录标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 记录标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 分组标识
	 */
	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	/**
	 * 分组标识
	 */
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}
	
	/**
	 * 分组类型
	 */
	public void setGroupType(java.lang.String groupType) {
		set("group_type", groupType);
	}
	
	/**
	 * 分组类型
	 */
	public java.lang.String getGroupType() {
		return getStr("group_type");
	}
	
	/**
	 * 成员标识
	 */
	public void setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
	}
	
	/**
	 * 成员标识
	 */
	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}
	
	/**
	 * 成员名称
	 */
	public void setMemberName(java.lang.String memberName) {
		set("member_name", memberName);
	}
	
	/**
	 * 成员名称
	 */
	public java.lang.String getMemberName() {
		return getStr("member_name");
	}
	
	/**
	 * 成员主从标识
	 */
	public void setMainFlag(java.lang.String mainFlag) {
		set("main_flag", mainFlag);
	}
	
	/**
	 * 成员主从标识
	 */
	public java.lang.String getMainFlag() {
		return getStr("main_flag");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

