package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotCamera<M extends BaseIotCamera<M>> extends Model<M> implements IBean {

	/**
	 * 摄像头主键标识
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 摄像头主键标识
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 摄像头编码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 摄像头编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	/**
	 * 用户名
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * IP地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * IP地址
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}
	
	/**
	 * RTSP端口
	 */
	public void setRtspPort(java.lang.Integer rtspPort) {
		set("rtsp_port", rtspPort);
	}
	
	/**
	 * RTSP端口
	 */
	public java.lang.Integer getRtspPort() {
		return getInt("rtsp_port");
	}
	
	/**
	 * SDK端口
	 */
	public void setSdkPort(java.lang.Integer sdkPort) {
		set("sdk_port", sdkPort);
	}
	
	/**
	 * SDK端口
	 */
	public java.lang.Integer getSdkPort() {
		return getInt("sdk_port");
	}
	
	/**
	 * 主码流通道
	 */
	public void setMainChannel(java.lang.String mainChannel) {
		set("main_channel", mainChannel);
	}
	
	/**
	 * 主码流通道
	 */
	public java.lang.String getMainChannel() {
		return getStr("main_channel");
	}
	
	/**
	 * 主码流开启标识
	 */
	public void setMainStreamFlag(java.lang.String mainStreamFlag) {
		set("main_stream_flag", mainStreamFlag);
	}
	
	/**
	 * 主码流开启标识
	 */
	public java.lang.String getMainStreamFlag() {
		return getStr("main_stream_flag");
	}
	
	/**
	 * 子码流通道
	 */
	public void setSubChannel(java.lang.String subChannel) {
		set("sub_channel", subChannel);
	}
	
	/**
	 * 子码流通道
	 */
	public java.lang.String getSubChannel() {
		return getStr("sub_channel");
	}
	
	/**
	 * 子码流开启标识
	 */
	public void setSubStreamFlag(java.lang.String subStreamFlag) {
		set("sub_stream_flag", subStreamFlag);
	}
	
	/**
	 * 子码流开启标识
	 */
	public java.lang.String getSubStreamFlag() {
		return getStr("sub_stream_flag");
	}
	
	/**
	 * 安装位置
	 */
	public void setInstallPos(java.lang.String installPos) {
		set("install_pos", installPos);
	}
	
	/**
	 * 安装位置
	 */
	public java.lang.String getInstallPos() {
		return getStr("install_pos");
	}
	
	/**
	 * 品牌
	 */
	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}
	
	/**
	 * 品牌
	 */
	public java.lang.String getBrand() {
		return getStr("brand");
	}
	
	/**
	 * 监控通道
	 */
	public void setMonitorChannel(java.lang.String monitorChannel) {
		set("monitor_channel", monitorChannel);
	}
	
	/**
	 * 监控通道
	 */
	public java.lang.String getMonitorChannel() {
		return getStr("monitor_channel");
	}
	
	/**
	 * 工作状态
	 */
	public void setWorkSts(java.lang.String workSts) {
		set("work_sts", workSts);
	}
	
	/**
	 * 工作状态
	 */
	public java.lang.String getWorkSts() {
		return getStr("work_sts");
	}
	
	/**
	 * 连接摄像头类型: RTSP, SDK
	 */
	public void setLinkType(java.lang.String linkType) {
		set("link_type", linkType);
	}
	
	/**
	 * 连接摄像头类型: RTSP, SDK
	 */
	public java.lang.String getLinkType() {
		return getStr("link_type");
	}
	
	/**
	 * 应用标识
	 */
	public void setAppId(java.lang.Integer appId) {
		set("app_id", appId);
	}
	
	/**
	 * 应用标识
	 */
	public java.lang.Integer getAppId() {
		return getInt("app_id");
	}
	
	/**
	 * 组织机构
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	/**
	 * 组织机构
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

