package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseFitting<M extends BaseBseFitting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCompanyid(java.lang.Integer companyid) {
		set("companyid", companyid);
	}
	
	public java.lang.Integer getCompanyid() {
		return getInt("companyid");
	}
	
	public void setChild(java.lang.String child) {
		set("child", child);
	}
	
	public java.lang.String getChild() {
		return getStr("child");
	}
	
	public void setLifetime(java.lang.String lifetime) {
		set("lifetime", lifetime);
	}
	
	public java.lang.String getLifetime() {
		return getStr("lifetime");
	}
	
	public void setKind(java.lang.String kind) {
		set("kind", kind);
	}
	
	public java.lang.String getKind() {
		return getStr("kind");
	}
	
	public void setEquipmentid(java.lang.Integer equipmentid) {
		set("equipmentid", equipmentid);
	}
	
	public java.lang.Integer getEquipmentid() {
		return getInt("equipmentid");
	}
	
	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	public void setWritetime(java.util.Date writetime) {
		set("writetime", writetime);
	}
	
	public java.util.Date getWritetime() {
		return getDate("writetime");
	}
	
}

