package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDictItem<M extends BaseSysDictItem<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 关联字典编码，与sys_dict表中的dict_code对应
	 */
	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}
	
	/**
	 * 关联字典编码，与sys_dict表中的dict_code对应
	 */
	public java.lang.String getDictCode() {
		return getStr("dict_code");
	}
	
	/**
	 * 字典项值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 字典项值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}
	
	/**
	 * 字典项标签
	 */
	public void setLabel(java.lang.String label) {
		set("label", label);
	}
	
	/**
	 * 字典项标签
	 */
	public java.lang.String getLabel() {
		return getStr("label");
	}
	
	/**
	 * 标签类型，用于前端样式展示（如success、warning等）
	 */
	public void setTagType(java.lang.String tagType) {
		set("tag_type", tagType);
	}
	
	/**
	 * 标签类型，用于前端样式展示（如success、warning等）
	 */
	public java.lang.String getTagType() {
		return getStr("tag_type");
	}
	
	/**
	 * 状态（1-正常，0-禁用）
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态（1-正常，0-禁用）
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 创建人ID
	 */
	public void setCreateBy(java.lang.Long createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Long getCreateBy() {
		return getLong("create_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 修改人ID
	 */
	public void setUpdateBy(java.lang.Long updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人ID
	 */
	public java.lang.Long getUpdateBy() {
		return getLong("update_by");
	}
	
}

