package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysJobLog<M extends BaseSysJobLog<M>> extends Model<M> implements IBean {

	/**
	 * 任务日志ID
	 */
	public void setJobLogId(java.lang.Long jobLogId) {
		set("job_log_id", jobLogId);
	}
	
	/**
	 * 任务日志ID
	 */
	public java.lang.Long getJobLogId() {
		return getLong("job_log_id");
	}
	
	/**
	 * 任务名称
	 */
	public void setJobName(java.lang.String jobName) {
		set("job_name", jobName);
	}
	
	/**
	 * 任务名称
	 */
	public java.lang.String getJobName() {
		return getStr("job_name");
	}
	
	/**
	 * 任务组名
	 */
	public void setJobGroup(java.lang.String jobGroup) {
		set("job_group", jobGroup);
	}
	
	/**
	 * 任务组名
	 */
	public java.lang.String getJobGroup() {
		return getStr("job_group");
	}
	
	/**
	 * 调用目标字符串
	 */
	public void setInvokeTarget(java.lang.String invokeTarget) {
		set("invoke_target", invokeTarget);
	}
	
	/**
	 * 调用目标字符串
	 */
	public java.lang.String getInvokeTarget() {
		return getStr("invoke_target");
	}
	
	/**
	 * 日志信息
	 */
	public void setJobMessage(java.lang.String jobMessage) {
		set("job_message", jobMessage);
	}
	
	/**
	 * 日志信息
	 */
	public java.lang.String getJobMessage() {
		return getStr("job_message");
	}
	
	/**
	 * 执行状态（0正常 1失败）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 执行状态（0正常 1失败）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 异常信息
	 */
	public void setExceptionInfo(java.lang.String exceptionInfo) {
		set("exception_info", exceptionInfo);
	}
	
	/**
	 * 异常信息
	 */
	public java.lang.String getExceptionInfo() {
		return getStr("exception_info");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
}

