package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIpaddress<M extends BaseIpaddress<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 设备编号
	 */
	public void setDeviceno(java.lang.String deviceno) {
		set("deviceno", deviceno);
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getDeviceno() {
		return getStr("deviceno");
	}
	
	/**
	 * 设备开关命令，10是正常，20是需要自动重启
	 */
	public void setPoweronoff(java.lang.String poweronoff) {
		set("poweronoff", poweronoff);
	}
	
	/**
	 * 设备开关命令，10是正常，20是需要自动重启
	 */
	public java.lang.String getPoweronoff() {
		return getStr("poweronoff");
	}
	
	public void setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
	}
	
	public java.lang.String getIpaddress() {
		return getStr("ipaddress");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setYuliu1(java.lang.String yuliu1) {
		set("yuliu1", yuliu1);
	}
	
	public java.lang.String getYuliu1() {
		return getStr("yuliu1");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setHappendtime(java.lang.String happendtime) {
		set("happendtime", happendtime);
	}
	
	public java.lang.String getHappendtime() {
		return getStr("happendtime");
	}
	
}

