package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseData<M extends BaseBseData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setDoorVideo(java.lang.String doorVideo) {
		set("door_video", doorVideo);
	}
	
	public java.lang.String getDoorVideo() {
		return getStr("door_video");
	}
	
	public void setQiguanVideo(java.lang.String qiguanVideo) {
		set("qiguan_video", qiguanVideo);
	}
	
	public java.lang.String getQiguanVideo() {
		return getStr("qiguan_video");
	}
	
	public void setDaoguanVideo(java.lang.String daoguanVideo) {
		set("daoguan_video", daoguanVideo);
	}
	
	public java.lang.String getDaoguanVideo() {
		return getStr("daoguan_video");
	}
	
	public void setLouguanVideo(java.lang.String louguanVideo) {
		set("louguan_video", louguanVideo);
	}
	
	public java.lang.String getLouguanVideo() {
		return getStr("louguan_video");
	}
	
	public void setWorker(java.lang.String worker) {
		set("worker", worker);
	}
	
	public java.lang.String getWorker() {
		return getStr("worker");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setYuliu(java.lang.String yuliu) {
		set("yuliu", yuliu);
	}
	
	public java.lang.String getYuliu() {
		return getStr("yuliu");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 连接两个表（bse_data和bse_xiaohezi)
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	/**
	 * 连接两个表（bse_data和bse_xiaohezi)
	 */
	public java.lang.String getUuid() {
		return getStr("uuid");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
}

