package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenTableColumn<M extends BaseGenTableColumn<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public void setColumnId(java.lang.Long columnId) {
		set("column_id", columnId);
	}
	
	/**
	 * 编号
	 */
	public java.lang.Long getColumnId() {
		return getLong("column_id");
	}
	
	/**
	 * 归属表编号
	 */
	public void setTableId(java.lang.Long tableId) {
		set("table_id", tableId);
	}
	
	/**
	 * 归属表编号
	 */
	public java.lang.Long getTableId() {
		return getLong("table_id");
	}
	
	/**
	 * 列名称
	 */
	public void setColumnName(java.lang.String columnName) {
		set("column_name", columnName);
	}
	
	/**
	 * 列名称
	 */
	public java.lang.String getColumnName() {
		return getStr("column_name");
	}
	
	/**
	 * 列描述
	 */
	public void setColumnComment(java.lang.String columnComment) {
		set("column_comment", columnComment);
	}
	
	/**
	 * 列描述
	 */
	public java.lang.String getColumnComment() {
		return getStr("column_comment");
	}
	
	/**
	 * 列类型
	 */
	public void setColumnType(java.lang.String columnType) {
		set("column_type", columnType);
	}
	
	/**
	 * 列类型
	 */
	public java.lang.String getColumnType() {
		return getStr("column_type");
	}
	
	/**
	 * JAVA类型
	 */
	public void setJavaType(java.lang.String javaType) {
		set("java_type", javaType);
	}
	
	/**
	 * JAVA类型
	 */
	public java.lang.String getJavaType() {
		return getStr("java_type");
	}
	
	/**
	 * JAVA字段名
	 */
	public void setJavaField(java.lang.String javaField) {
		set("java_field", javaField);
	}
	
	/**
	 * JAVA字段名
	 */
	public java.lang.String getJavaField() {
		return getStr("java_field");
	}
	
	/**
	 * 是否主键（1是）
	 */
	public void setIsPk(java.lang.String isPk) {
		set("is_pk", isPk);
	}
	
	/**
	 * 是否主键（1是）
	 */
	public java.lang.String getIsPk() {
		return getStr("is_pk");
	}
	
	/**
	 * 是否自增（1是）
	 */
	public void setIsIncrement(java.lang.String isIncrement) {
		set("is_increment", isIncrement);
	}
	
	/**
	 * 是否自增（1是）
	 */
	public java.lang.String getIsIncrement() {
		return getStr("is_increment");
	}
	
	/**
	 * 是否必填（1是）
	 */
	public void setIsRequired(java.lang.String isRequired) {
		set("is_required", isRequired);
	}
	
	/**
	 * 是否必填（1是）
	 */
	public java.lang.String getIsRequired() {
		return getStr("is_required");
	}
	
	/**
	 * 是否为插入字段（1是）
	 */
	public void setIsInsert(java.lang.String isInsert) {
		set("is_insert", isInsert);
	}
	
	/**
	 * 是否为插入字段（1是）
	 */
	public java.lang.String getIsInsert() {
		return getStr("is_insert");
	}
	
	/**
	 * 是否编辑字段（1是）
	 */
	public void setIsEdit(java.lang.String isEdit) {
		set("is_edit", isEdit);
	}
	
	/**
	 * 是否编辑字段（1是）
	 */
	public java.lang.String getIsEdit() {
		return getStr("is_edit");
	}
	
	/**
	 * 是否列表字段（1是）
	 */
	public void setIsList(java.lang.String isList) {
		set("is_list", isList);
	}
	
	/**
	 * 是否列表字段（1是）
	 */
	public java.lang.String getIsList() {
		return getStr("is_list");
	}
	
	/**
	 * 是否查询字段（1是）
	 */
	public void setIsQuery(java.lang.String isQuery) {
		set("is_query", isQuery);
	}
	
	/**
	 * 是否查询字段（1是）
	 */
	public java.lang.String getIsQuery() {
		return getStr("is_query");
	}
	
	/**
	 * 查询方式（等于、不等于、大于、小于、范围）
	 */
	public void setQueryType(java.lang.String queryType) {
		set("query_type", queryType);
	}
	
	/**
	 * 查询方式（等于、不等于、大于、小于、范围）
	 */
	public java.lang.String getQueryType() {
		return getStr("query_type");
	}
	
	/**
	 * 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	 */
	public void setHtmlType(java.lang.String htmlType) {
		set("html_type", htmlType);
	}
	
	/**
	 * 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	 */
	public java.lang.String getHtmlType() {
		return getStr("html_type");
	}
	
	/**
	 * 字典类型
	 */
	public void setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
	}
	
	/**
	 * 字典类型
	 */
	public java.lang.String getDictType() {
		return getStr("dict_type");
	}
	
	/**
	 * 排序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
}

