package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasFile123<M extends BaseGasFile123<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 气瓶编号
	 */
	public void setGasNumber(java.lang.String gasNumber) {
		set("gas_number", gasNumber);
	}
	
	/**
	 * 气瓶编号
	 */
	public java.lang.String getGasNumber() {
		return getStr("gas_number");
	}
	
	/**
	 * 所属于的气站id
	 */
	public void setGasstationid(java.lang.Integer gasstationid) {
		set("gasstationid", gasstationid);
	}
	
	/**
	 * 所属于的气站id
	 */
	public java.lang.Integer getGasstationid() {
		return getInt("gasstationid");
	}
	
	/**
	 * 建档气站名字
	 */
	public void setFilingGasStation(java.lang.String filingGasStation) {
		set("filing_gas_station", filingGasStation);
	}
	
	/**
	 * 建档气站名字
	 */
	public java.lang.String getFilingGasStation() {
		return getStr("filing_gas_station");
	}
	
	/**
	 * 阀体编码
	 */
	public void setValveBodyCode(java.lang.String valveBodyCode) {
		set("valve_body_code", valveBodyCode);
	}
	
	/**
	 * 阀体编码
	 */
	public java.lang.String getValveBodyCode() {
		return getStr("valve_body_code");
	}
	
	/**
	 * 阀体蓝牙
	 */
	public void setValveBodyBluetooth(java.lang.String valveBodyBluetooth) {
		set("valve_body_bluetooth", valveBodyBluetooth);
	}
	
	/**
	 * 阀体蓝牙
	 */
	public java.lang.String getValveBodyBluetooth() {
		return getStr("valve_body_bluetooth");
	}
	
	/**
	 * 制造单位
	 */
	public void setManufactureUnit(java.lang.String manufactureUnit) {
		set("manufacture_unit", manufactureUnit);
	}
	
	/**
	 * 制造单位
	 */
	public java.lang.String getManufactureUnit() {
		return getStr("manufacture_unit");
	}
	
	/**
	 * 制造日期
	 */
	public void setManufactureDate(java.util.Date manufactureDate) {
		set("manufacture_date", manufactureDate);
	}
	
	/**
	 * 制造日期
	 */
	public java.util.Date getManufactureDate() {
		return getDate("manufacture_date");
	}
	
	/**
	 * 检验日期
	 */
	public void setInspectDate(java.util.Date inspectDate) {
		set("inspect_date", inspectDate);
	}
	
	/**
	 * 检验日期
	 */
	public java.util.Date getInspectDate() {
		return getDate("inspect_date");
	}
	
	/**
	 * 定检日期
	 */
	public void setRegularCheckDate(java.util.Date regularCheckDate) {
		set("regular_check_date", regularCheckDate);
	}
	
	/**
	 * 定检日期
	 */
	public java.util.Date getRegularCheckDate() {
		return getDate("regular_check_date");
	}
	
	/**
	 * 终止使用日期
	 */
	public void setTerminateUseDate(java.util.Date terminateUseDate) {
		set("terminate_use_date", terminateUseDate);
	}
	
	/**
	 * 终止使用日期
	 */
	public java.util.Date getTerminateUseDate() {
		return getDate("terminate_use_date");
	}
	
	/**
	 * 监测站
	 */
	public void setMonitoringStation(java.lang.String monitoringStation) {
		set("monitoring_station", monitoringStation);
	}
	
	/**
	 * 监测站
	 */
	public java.lang.String getMonitoringStation() {
		return getStr("monitoring_station");
	}
	
	/**
	 * 充装规格
	 */
	public void setFillingSpecification(java.lang.String fillingSpecification) {
		set("filling_specification", fillingSpecification);
	}
	
	/**
	 * 充装规格
	 */
	public java.lang.String getFillingSpecification() {
		return getStr("filling_specification");
	}
	
	/**
	 * 气瓶规格
	 */
	public void setGasSpecification(java.lang.String gasSpecification) {
		set("gas_specification", gasSpecification);
	}
	
	/**
	 * 气瓶规格
	 */
	public java.lang.String getGasSpecification() {
		return getStr("gas_specification");
	}
	
	/**
	 * 充装介质
	 */
	public void setFillingMedium(java.lang.String fillingMedium) {
		set("filling_medium", fillingMedium);
	}
	
	/**
	 * 充装介质
	 */
	public java.lang.String getFillingMedium() {
		return getStr("filling_medium");
	}
	
	/**
	 * 气瓶净重
	 */
	public void setGasSuttle(java.lang.String gasSuttle) {
		set("gas_suttle", gasSuttle);
	}
	
	/**
	 * 气瓶净重
	 */
	public java.lang.String getGasSuttle() {
		return getStr("gas_suttle");
	}
	
	/**
	 * 投保日期
	 */
	public void setInsuranceDate(java.util.Date insuranceDate) {
		set("insurance_date", insuranceDate);
	}
	
	/**
	 * 投保日期
	 */
	public java.util.Date getInsuranceDate() {
		return getDate("insurance_date");
	}
	
	/**
	 * 建档日期
	 */
	public void setFilingDate(java.util.Date filingDate) {
		set("filing_date", filingDate);
	}
	
	/**
	 * 建档日期
	 */
	public java.util.Date getFilingDate() {
		return getDate("filing_date");
	}
	
	/**
	 * 车辆照片ossid
	 */
	public void setGasImageOssId(java.lang.String gasImageOssId) {
		set("gas_image_oss_id", gasImageOssId);
	}
	
	/**
	 * 车辆照片ossid
	 */
	public java.lang.String getGasImageOssId() {
		return getStr("gas_image_oss_id");
	}
	
	public void setGasImageUrl(java.lang.String gasImageUrl) {
		set("gas_image_url", gasImageUrl);
	}
	
	public java.lang.String getGasImageUrl() {
		return getStr("gas_image_url");
	}
	
}

