package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTransport<M extends BaseTransport<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
	public void setStationname(java.lang.String stationname) {
		set("stationname", stationname);
	}
	
	public java.lang.String getStationname() {
		return getStr("stationname");
	}
	
	public void setStaff(java.lang.String staff) {
		set("staff", staff);
	}
	
	public java.lang.String getStaff() {
		return getStr("staff");
	}
	
	public void setBottleid(java.lang.String bottleid) {
		set("bottleid", bottleid);
	}
	
	public java.lang.String getBottleid() {
		return getStr("bottleid");
	}
	
	public void setUptime(java.util.Date uptime) {
		set("uptime", uptime);
	}
	
	public java.util.Date getUptime() {
		return getDate("uptime");
	}
	
	public void setDowntime(java.lang.String downtime) {
		set("downtime", downtime);
	}
	
	public java.lang.String getDowntime() {
		return getStr("downtime");
	}
	
	public void setDownaddress(java.lang.String downaddress) {
		set("downaddress", downaddress);
	}
	
	public java.lang.String getDownaddress() {
		return getStr("downaddress");
	}
	
	/**
	 * 气瓶状态，运输中，已到站，破损回厂
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 气瓶状态，运输中，已到站，破损回厂
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCustomer(java.lang.String customer) {
		set("customer", customer);
	}
	
	public java.lang.String getCustomer() {
		return getStr("customer");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setRemark1(java.lang.String remark1) {
		set("remark1", remark1);
	}
	
	public java.lang.String getRemark1() {
		return getStr("remark1");
	}
	
	public void setRemark2(java.lang.String remark2) {
		set("remark2", remark2);
	}
	
	public java.lang.String getRemark2() {
		return getStr("remark2");
	}
	
	public void setRemark3(java.lang.String remark3) {
		set("remark3", remark3);
	}
	
	public java.lang.String getRemark3() {
		return getStr("remark3");
	}
	
	public void setJingdu(java.lang.String jingdu) {
		set("jingdu", jingdu);
	}
	
	public java.lang.String getJingdu() {
		return getStr("jingdu");
	}
	
	public void setWeidu(java.lang.String weidu) {
		set("weidu", weidu);
	}
	
	public java.lang.String getWeidu() {
		return getStr("weidu");
	}
	
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
}

