package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOthergas<M extends BaseOthergas<M>> extends Model<M> implements IBean {

	/**
	 * 开始灌装时间
	 */
	public void setTradeDate(java.util.Date TradeDate) {
		set("TradeDate", TradeDate);
	}
	
	/**
	 * 开始灌装时间
	 */
	public java.util.Date getTradeDate() {
		return getDate("TradeDate");
	}
	
	/**
	 * 机号(枪号)
	 */
	public void setGunNo(java.lang.Integer GunNo) {
		set("GunNo", GunNo);
	}
	
	/**
	 * 机号(枪号)
	 */
	public java.lang.Integer getGunNo() {
		return getInt("GunNo");
	}
	
	/**
	 * 加气机交易流水号
	 */
	public void setTradeNo(java.lang.Long TradeNo) {
		set("TradeNo", TradeNo);
	}
	
	/**
	 * 加气机交易流水号
	 */
	public java.lang.Long getTradeNo() {
		return getLong("TradeNo");
	}
	
	/**
	 * 灌装量(kg)
	 */
	public void setNowGas(java.lang.String NowGas) {
		set("NowGas", NowGas);
	}
	
	/**
	 * 灌装量(kg)
	 */
	public java.lang.String getNowGas() {
		return getStr("NowGas");
	}
	
	/**
	 * 充装金额
	 */
	public void setNowMoney(java.lang.String NowMoney) {
		set("NowMoney", NowMoney);
	}
	
	/**
	 * 充装金额
	 */
	public java.lang.String getNowMoney() {
		return getStr("NowMoney");
	}
	
	/**
	 * 单价
	 */
	public void setPrice(java.lang.String price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.lang.String getPrice() {
		return getStr("price");
	}
	
	/**
	 * 客户代码
	 */
	public void setUserCardNo(java.lang.String UserCardNo) {
		set("UserCardNo", UserCardNo);
	}
	
	/**
	 * 客户代码
	 */
	public java.lang.String getUserCardNo() {
		return getStr("UserCardNo");
	}
	
	public void setBZNo(java.lang.String BZNo) {
		set("BZNo", BZNo);
	}
	
	public java.lang.String getBZNo() {
		return getStr("BZNo");
	}
	
	/**
	 * 工号
	 */
	public void setYGCardNo(java.lang.String YGCardNo) {
		set("YGCardNo", YGCardNo);
	}
	
	/**
	 * 工号
	 */
	public java.lang.String getYGCardNo() {
		return getStr("YGCardNo");
	}
	
	/**
	 * 目标重量(kg)
	 */
	public void setBeginpressure(java.lang.String beginpressure) {
		set("beginpressure", beginpressure);
	}
	
	/**
	 * 目标重量(kg)
	 */
	public java.lang.String getBeginpressure() {
		return getStr("beginpressure");
	}
	
	/**
	 * 皮重(kg)
	 */
	public void setPressure(java.lang.String pressure) {
		set("pressure", pressure);
	}
	
	/**
	 * 皮重(kg)
	 */
	public java.lang.String getPressure() {
		return getStr("pressure");
	}
	
	public void setCarNo(java.lang.String CarNo) {
		set("CarNo", CarNo);
	}
	
	public java.lang.String getCarNo() {
		return getStr("CarNo");
	}
	
	/**
	 * 灌装用时
	 */
	public void setAddgaslong(java.lang.String addgaslong) {
		set("addgaslong", addgaslong);
	}
	
	/**
	 * 灌装用时
	 */
	public java.lang.String getAddgaslong() {
		return getStr("addgaslong");
	}
	
	/**
	 * 站点编码
	 */
	public void setStationCode(java.lang.String stationCode) {
		set("stationCode", stationCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getStationCode() {
		return getStr("stationCode");
	}
	
	/**
	 * 入库时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}

