package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasshexiangtouinfo<M extends BaseBasshexiangtouinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 摄像头编号
	 */
	public void setShexiangtoubianhao(java.lang.String shexiangtoubianhao) {
		set("shexiangtoubianhao", shexiangtoubianhao);
	}
	
	/**
	 * 摄像头编号
	 */
	public java.lang.String getShexiangtoubianhao() {
		return getStr("shexiangtoubianhao");
	}
	
	public void setShengchanchangjia(java.lang.String shengchanchangjia) {
		set("shengchanchangjia", shengchanchangjia);
	}
	
	public java.lang.String getShengchanchangjia() {
		return getStr("shengchanchangjia");
	}
	
	public void setChangjiadianhua(java.lang.String changjiadianhua) {
		set("changjiadianhua", changjiadianhua);
	}
	
	public java.lang.String getChangjiadianhua() {
		return getStr("changjiadianhua");
	}
	
	/**
	 * 生产日期
	 */
	public void setShengchanshijian(java.lang.String shengchanshijian) {
		set("shengchanshijian", shengchanshijian);
	}
	
	/**
	 * 生产日期
	 */
	public java.lang.String getShengchanshijian() {
		return getStr("shengchanshijian");
	}
	
	/**
	 * 饭店id关联，用来确定这个摄像头是哪个饭店用的
	 */
	public void setRestaurantid(java.lang.Integer restaurantid) {
		set("restaurantid", restaurantid);
	}
	
	/**
	 * 饭店id关联，用来确定这个摄像头是哪个饭店用的
	 */
	public java.lang.Integer getRestaurantid() {
		return getInt("restaurantid");
	}
	
	/**
	 * 饭店名字
	 */
	public void setRestaurantname(java.lang.String restaurantname) {
		set("restaurantname", restaurantname);
	}
	
	/**
	 * 饭店名字
	 */
	public java.lang.String getRestaurantname() {
		return getStr("restaurantname");
	}
	
	/**
	 * 饭店电话
	 */
	public void setRestaurantphone(java.lang.String restaurantphone) {
		set("restaurantphone", restaurantphone);
	}
	
	/**
	 * 饭店电话
	 */
	public java.lang.String getRestaurantphone() {
		return getStr("restaurantphone");
	}
	
	public void setFalg(java.lang.Integer falg) {
		set("falg", falg);
	}
	
	public java.lang.Integer getFalg() {
		return getInt("falg");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setMemo(java.lang.Integer memo) {
		set("memo", memo);
	}
	
	public java.lang.Integer getMemo() {
		return getInt("memo");
	}
	
	public void setYuliu1(java.lang.String yuliu1) {
		set("yuliu1", yuliu1);
	}
	
	public java.lang.String getYuliu1() {
		return getStr("yuliu1");
	}
	
	public void setYuliu2(java.lang.String yuliu2) {
		set("yuliu2", yuliu2);
	}
	
	public java.lang.String getYuliu2() {
		return getStr("yuliu2");
	}
	
	/**
	 * 饭店地址
	 */
	public void setRestaurantaddress(java.lang.String restaurantaddress) {
		set("restaurantaddress", restaurantaddress);
	}
	
	/**
	 * 饭店地址
	 */
	public java.lang.String getRestaurantaddress() {
		return getStr("restaurantaddress");
	}
	
}

