package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzSimpropTriggers<M extends BaseQrtzSimpropTriggers<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * qrtz_triggers表trigger_name的外键
	 */
	public void setTriggerName(java.lang.String triggerName) {
		set("trigger_name", triggerName);
	}
	
	/**
	 * qrtz_triggers表trigger_name的外键
	 */
	public java.lang.String getTriggerName() {
		return getStr("trigger_name");
	}
	
	/**
	 * qrtz_triggers表trigger_group的外键
	 */
	public void setTriggerGroup(java.lang.String triggerGroup) {
		set("trigger_group", triggerGroup);
	}
	
	/**
	 * qrtz_triggers表trigger_group的外键
	 */
	public java.lang.String getTriggerGroup() {
		return getStr("trigger_group");
	}
	
	/**
	 * String类型的trigger的第一个参数
	 */
	public void setStrProp1(java.lang.String strProp1) {
		set("str_prop_1", strProp1);
	}
	
	/**
	 * String类型的trigger的第一个参数
	 */
	public java.lang.String getStrProp1() {
		return getStr("str_prop_1");
	}
	
	/**
	 * String类型的trigger的第二个参数
	 */
	public void setStrProp2(java.lang.String strProp2) {
		set("str_prop_2", strProp2);
	}
	
	/**
	 * String类型的trigger的第二个参数
	 */
	public java.lang.String getStrProp2() {
		return getStr("str_prop_2");
	}
	
	/**
	 * String类型的trigger的第三个参数
	 */
	public void setStrProp3(java.lang.String strProp3) {
		set("str_prop_3", strProp3);
	}
	
	/**
	 * String类型的trigger的第三个参数
	 */
	public java.lang.String getStrProp3() {
		return getStr("str_prop_3");
	}
	
	/**
	 * int类型的trigger的第一个参数
	 */
	public void setIntProp1(java.lang.Integer intProp1) {
		set("int_prop_1", intProp1);
	}
	
	/**
	 * int类型的trigger的第一个参数
	 */
	public java.lang.Integer getIntProp1() {
		return getInt("int_prop_1");
	}
	
	/**
	 * int类型的trigger的第二个参数
	 */
	public void setIntProp2(java.lang.Integer intProp2) {
		set("int_prop_2", intProp2);
	}
	
	/**
	 * int类型的trigger的第二个参数
	 */
	public java.lang.Integer getIntProp2() {
		return getInt("int_prop_2");
	}
	
	/**
	 * long类型的trigger的第一个参数
	 */
	public void setLongProp1(java.lang.Long longProp1) {
		set("long_prop_1", longProp1);
	}
	
	/**
	 * long类型的trigger的第一个参数
	 */
	public java.lang.Long getLongProp1() {
		return getLong("long_prop_1");
	}
	
	/**
	 * long类型的trigger的第二个参数
	 */
	public void setLongProp2(java.lang.Long longProp2) {
		set("long_prop_2", longProp2);
	}
	
	/**
	 * long类型的trigger的第二个参数
	 */
	public java.lang.Long getLongProp2() {
		return getLong("long_prop_2");
	}
	
	/**
	 * decimal类型的trigger的第一个参数
	 */
	public void setDecProp1(java.math.BigDecimal decProp1) {
		set("dec_prop_1", decProp1);
	}
	
	/**
	 * decimal类型的trigger的第一个参数
	 */
	public java.math.BigDecimal getDecProp1() {
		return get("dec_prop_1");
	}
	
	/**
	 * decimal类型的trigger的第二个参数
	 */
	public void setDecProp2(java.math.BigDecimal decProp2) {
		set("dec_prop_2", decProp2);
	}
	
	/**
	 * decimal类型的trigger的第二个参数
	 */
	public java.math.BigDecimal getDecProp2() {
		return get("dec_prop_2");
	}
	
	/**
	 * Boolean类型的trigger的第一个参数
	 */
	public void setBoolProp1(java.lang.String boolProp1) {
		set("bool_prop_1", boolProp1);
	}
	
	/**
	 * Boolean类型的trigger的第一个参数
	 */
	public java.lang.String getBoolProp1() {
		return getStr("bool_prop_1");
	}
	
	/**
	 * Boolean类型的trigger的第二个参数
	 */
	public void setBoolProp2(java.lang.String boolProp2) {
		set("bool_prop_2", boolProp2);
	}
	
	/**
	 * Boolean类型的trigger的第二个参数
	 */
	public java.lang.String getBoolProp2() {
		return getStr("bool_prop_2");
	}
	
}

