package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStaffUserGov<M extends BaseGasStaffUserGov<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}
	
	public void setOrgInfoCode(java.lang.String orgInfoCode) {
		set("org_info_code", orgInfoCode);
	}
	
	public java.lang.String getOrgInfoCode() {
		return getStr("org_info_code");
	}
	
	public void setOrgInfoId(java.lang.String orgInfoId) {
		set("org_info_id", orgInfoId);
	}
	
	public java.lang.String getOrgInfoId() {
		return getStr("org_info_id");
	}
	
	public void setOrgInfoName(java.lang.String orgInfoName) {
		set("org_info_name", orgInfoName);
	}
	
	public java.lang.String getOrgInfoName() {
		return getStr("org_info_name");
	}
	
	public void setOrgInfoType(java.lang.String orgInfoType) {
		set("org_info_type", orgInfoType);
	}
	
	public java.lang.String getOrgInfoType() {
		return getStr("org_info_type");
	}
	
	public void setUserIdentity(java.lang.String userIdentity) {
		set("user_identity", userIdentity);
	}
	
	public java.lang.String getUserIdentity() {
		return getStr("user_identity");
	}
	
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public void setPost(java.lang.String post) {
		set("post", post);
	}
	
	public java.lang.String getPost() {
		return getStr("post");
	}
	
	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}
	
	public void setWorkNo(java.lang.String workNo) {
		set("work_no", workNo);
	}
	
	public java.lang.String getWorkNo() {
		return getStr("work_no");
	}
	
	public void setRelTenantIds(java.lang.String relTenantIds) {
		set("rel_tenant_ids", relTenantIds);
	}
	
	public java.lang.String getRelTenantIds() {
		return getStr("rel_tenant_ids");
	}
	
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}
	
	public java.lang.String getBirthday() {
		return getStr("birthday");
	}
	
	public void setClientId(java.lang.String clientId) {
		set("client_id", clientId);
	}
	
	public java.lang.String getClientId() {
		return getStr("client_id");
	}
	
	public void setClientIp(java.lang.String clientIp) {
		set("client_ip", clientIp);
	}
	
	public java.lang.String getClientIp() {
		return getStr("client_ip");
	}
	
	public void setDepartIds(java.lang.String departIds) {
		set("depart_ids", departIds);
	}
	
	public java.lang.String getDepartIds() {
		return getStr("depart_ids");
	}
	
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	public void setThirdId(java.lang.String thirdId) {
		set("third_id", thirdId);
	}
	
	public java.lang.String getThirdId() {
		return getStr("third_id");
	}
	
	public void setThirdType(java.lang.String thirdType) {
		set("third_type", thirdType);
	}
	
	public java.lang.String getThirdType() {
		return getStr("third_type");
	}
	
	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}
	
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}
	
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}
	
}

