package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasbottleinstore<M extends BaseGasbottleinstore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGasnumber(java.lang.String gasnumber) {
		set("gasnumber", gasnumber);
	}
	
	public java.lang.String getGasnumber() {
		return getStr("gasnumber");
	}
	
	public void setGasstationid(java.lang.String gasstationid) {
		set("gasstationid", gasstationid);
	}
	
	public java.lang.String getGasstationid() {
		return getStr("gasstationid");
	}
	
	public void setRukuren(java.lang.String rukuren) {
		set("rukuren", rukuren);
	}
	
	public java.lang.String getRukuren() {
		return getStr("rukuren");
	}
	
	public void setRukushijian(java.lang.String rukushijian) {
		set("rukushijian", rukushijian);
	}
	
	public java.lang.String getRukushijian() {
		return getStr("rukushijian");
	}
	
	/**
	 * 入库状态，是否合格
	 */
	public void setZhuangtai(java.lang.String zhuangtai) {
		set("zhuangtai", zhuangtai);
	}
	
	/**
	 * 入库状态，是否合格
	 */
	public java.lang.String getZhuangtai() {
		return getStr("zhuangtai");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setJingdu(java.lang.String jingdu) {
		set("jingdu", jingdu);
	}
	
	public java.lang.String getJingdu() {
		return getStr("jingdu");
	}
	
	public void setWeidu(java.lang.String weidu) {
		set("weidu", weidu);
	}
	
	public java.lang.String getWeidu() {
		return getStr("weidu");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setGasstationname(java.lang.String gasstationname) {
		set("gasstationname", gasstationname);
	}
	
	public java.lang.String getGasstationname() {
		return getStr("gasstationname");
	}
	
}

