package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCylinder<M extends BaseCylinder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 气瓶编号
	 */
	public void setQipingbianhao(java.lang.String qipingbianhao) {
		set("qipingbianhao", qipingbianhao);
	}
	
	/**
	 * 气瓶编号
	 */
	public java.lang.String getQipingbianhao() {
		return getStr("qipingbianhao");
	}
	
	/**
	 * 电子标签
	 */
	public void setDianzibiaoqian(java.lang.String dianzibiaoqian) {
		set("dianzibiaoqian", dianzibiaoqian);
	}
	
	/**
	 * 电子标签
	 */
	public java.lang.String getDianzibiaoqian() {
		return getStr("dianzibiaoqian");
	}
	
	/**
	 * 气瓶条码
	 */
	public void setQipingtiaoma(java.lang.String qipingtiaoma) {
		set("qipingtiaoma", qipingtiaoma);
	}
	
	/**
	 * 气瓶条码
	 */
	public java.lang.String getQipingtiaoma() {
		return getStr("qipingtiaoma");
	}
	
	public void setDanweineibianma(java.lang.String danweineibianma) {
		set("danweineibianma", danweineibianma);
	}
	
	public java.lang.String getDanweineibianma() {
		return getStr("danweineibianma");
	}
	
	public void setQipingzhongliang(java.lang.Float qipingzhongliang) {
		set("qipingzhongliang", qipingzhongliang);
	}
	
	public java.lang.Float getQipingzhongliang() {
		return getFloat("qipingzhongliang");
	}
	
	public void setChongqijiezhi(java.lang.String chongqijiezhi) {
		set("chongqijiezhi", chongqijiezhi);
	}
	
	public java.lang.String getChongqijiezhi() {
		return getStr("chongqijiezhi");
	}
	
	public void setZhizaodanwei(java.lang.String zhizaodanwei) {
		set("zhizaodanwei", zhizaodanwei);
	}
	
	public java.lang.String getZhizaodanwei() {
		return getStr("zhizaodanwei");
	}
	
	public void setJianyandanwei(java.lang.String jianyandanwei) {
		set("jianyandanwei", jianyandanwei);
	}
	
	public java.lang.String getJianyandanwei() {
		return getStr("jianyandanwei");
	}
	
	public void setZhizaoriqi(java.lang.String zhizaoriqi) {
		set("zhizaoriqi", zhizaoriqi);
	}
	
	public java.lang.String getZhizaoriqi() {
		return getStr("zhizaoriqi");
	}
	
	public void setJianyanriqi(java.lang.String jianyanriqi) {
		set("jianyanriqi", jianyanriqi);
	}
	
	public java.lang.String getJianyanriqi() {
		return getStr("jianyanriqi");
	}
	
	public void setXiajianriqi(java.lang.String xiajianriqi) {
		set("xiajianriqi", xiajianriqi);
	}
	
	public java.lang.String getXiajianriqi() {
		return getStr("xiajianriqi");
	}
	
	public void setBaofeiriqi(java.lang.String baofeiriqi) {
		set("baofeiriqi", baofeiriqi);
	}
	
	public java.lang.String getBaofeiriqi() {
		return getStr("baofeiriqi");
	}
	
	public void setFaleixing(java.lang.String faleixing) {
		set("faleixing", faleixing);
	}
	
	public java.lang.String getFaleixing() {
		return getStr("faleixing");
	}
	
	public void setJiaofachangjia(java.lang.String jiaofachangjia) {
		set("jiaofachangjia", jiaofachangjia);
	}
	
	public java.lang.String getJiaofachangjia() {
		return getStr("jiaofachangjia");
	}
	
	public void setQipingdengjibianhao(java.lang.String qipingdengjibianhao) {
		set("qipingdengjibianhao", qipingdengjibianhao);
	}
	
	public java.lang.String getQipingdengjibianhao() {
		return getStr("qipingdengjibianhao");
	}
	
	public void setChanquandanwei(java.lang.String chanquandanwei) {
		set("chanquandanwei", chanquandanwei);
	}
	
	public java.lang.String getChanquandanwei() {
		return getStr("chanquandanwei");
	}
	
}

