package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStation<M extends BaseGasStation<M>> extends Model<M> implements IBean {

	/**
	 * 主键，加气站ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键，加气站ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 加气站编码
	 */
	public void setStationId(java.lang.String stationId) {
		set("station_id", stationId);
	}
	
	/**
	 * 加气站编码
	 */
	public java.lang.String getStationId() {
		return getStr("station_id");
	}
	
	/**
	 * 加气站名称
	 */
	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	/**
	 * 加气站名称
	 */
	public java.lang.String getStationName() {
		return getStr("station_name");
	}
	
	/**
	 * 加气站地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 加气站地址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 法人
	 */
	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}
	
	/**
	 * 法人
	 */
	public java.lang.String getLegalPerson() {
		return getStr("legal_person");
	}
	
	/**
	 * 手机号码
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 状态未 10 的为正常上传；状态未 0 的为不上传
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态未 10 的为正常上传；状态未 0 的为不上传
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 经度
	 */
	public void setLONGITUDE(java.lang.String LONGITUDE) {
		set("LONGITUDE", LONGITUDE);
	}
	
	/**
	 * 经度
	 */
	public java.lang.String getLONGITUDE() {
		return getStr("LONGITUDE");
	}
	
	/**
	 * 维度
	 */
	public void setLATITUDE(java.lang.String LATITUDE) {
		set("LATITUDE", LATITUDE);
	}
	
	/**
	 * 维度
	 */
	public java.lang.String getLATITUDE() {
		return getStr("LATITUDE");
	}
	
	/**
	 * 高度
	 */
	public void setHEIGHT(java.lang.String HEIGHT) {
		set("HEIGHT", HEIGHT);
	}
	
	/**
	 * 高度
	 */
	public java.lang.String getHEIGHT() {
		return getStr("HEIGHT");
	}
	
}

