package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleDept<M extends BaseSysRoleDept<M>> extends Model<M> implements IBean {

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}
	
	/**
	 * 部门ID
	 */
	public void setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
	}
	
	/**
	 * 部门ID
	 */
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
}

