package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLogininfor<M extends BaseSysLogininfor<M>> extends Model<M> implements IBean {

	/**
	 * 访问ID
	 */
	public void setInfoId(java.lang.Long infoId) {
		set("info_id", infoId);
	}
	
	/**
	 * 访问ID
	 */
	public java.lang.Long getInfoId() {
		return getLong("info_id");
	}
	
	/**
	 * 用户账号
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户账号
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 登录IP地址
	 */
	public void setIpaddr(java.lang.String ipaddr) {
		set("ipaddr", ipaddr);
	}
	
	/**
	 * 登录IP地址
	 */
	public java.lang.String getIpaddr() {
		return getStr("ipaddr");
	}
	
	/**
	 * 登录地点
	 */
	public void setLoginLocation(java.lang.String loginLocation) {
		set("login_location", loginLocation);
	}
	
	/**
	 * 登录地点
	 */
	public java.lang.String getLoginLocation() {
		return getStr("login_location");
	}
	
	/**
	 * 浏览器类型
	 */
	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	/**
	 * 浏览器类型
	 */
	public java.lang.String getBrowser() {
		return getStr("browser");
	}
	
	/**
	 * 操作系统
	 */
	public void setOs(java.lang.String os) {
		set("os", os);
	}
	
	/**
	 * 操作系统
	 */
	public java.lang.String getOs() {
		return getStr("os");
	}
	
	/**
	 * 登录状态（0成功 1失败）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 登录状态（0成功 1失败）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 提示消息
	 */
	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	/**
	 * 提示消息
	 */
	public java.lang.String getMsg() {
		return getStr("msg");
	}
	
	/**
	 * 访问时间
	 */
	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}
	
	/**
	 * 访问时间
	 */
	public java.util.Date getLoginTime() {
		return getDate("login_time");
	}
	
}

