package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGenFieldConfig<M extends BaseGenFieldConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 关联的配置ID
	 */
	public void setConfigId(java.lang.Long configId) {
		set("config_id", configId);
	}
	
	/**
	 * 关联的配置ID
	 */
	public java.lang.Long getConfigId() {
		return getLong("config_id");
	}
	
	public void setColumnName(java.lang.String columnName) {
		set("column_name", columnName);
	}
	
	public java.lang.String getColumnName() {
		return getStr("column_name");
	}
	
	public void setColumnType(java.lang.String columnType) {
		set("column_type", columnType);
	}
	
	public java.lang.String getColumnType() {
		return getStr("column_type");
	}
	
	public void setColumnLength(java.lang.Integer columnLength) {
		set("column_length", columnLength);
	}
	
	public java.lang.Integer getColumnLength() {
		return getInt("column_length");
	}
	
	/**
	 * 字段名称
	 */
	public void setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
	}
	
	/**
	 * 字段名称
	 */
	public java.lang.String getFieldName() {
		return getStr("field_name");
	}
	
	/**
	 * 字段类型
	 */
	public void setFieldType(java.lang.String fieldType) {
		set("field_type", fieldType);
	}
	
	/**
	 * 字段类型
	 */
	public java.lang.String getFieldType() {
		return getStr("field_type");
	}
	
	/**
	 * 字段排序
	 */
	public void setFieldSort(java.lang.Integer fieldSort) {
		set("field_sort", fieldSort);
	}
	
	/**
	 * 字段排序
	 */
	public java.lang.Integer getFieldSort() {
		return getInt("field_sort");
	}
	
	/**
	 * 字段描述
	 */
	public void setFieldComment(java.lang.String fieldComment) {
		set("field_comment", fieldComment);
	}
	
	/**
	 * 字段描述
	 */
	public java.lang.String getFieldComment() {
		return getStr("field_comment");
	}
	
	public void setMaxLength(java.lang.Integer maxLength) {
		set("max_length", maxLength);
	}
	
	public java.lang.Integer getMaxLength() {
		return getInt("max_length");
	}
	
	/**
	 * 是否必填
	 */
	public void setIsRequired(java.lang.Boolean isRequired) {
		set("is_required", isRequired);
	}
	
	/**
	 * 是否必填
	 */
	public java.lang.Boolean getIsRequired() {
		return get("is_required");
	}
	
	/**
	 * 是否在列表显示
	 */
	public void setIsShowInList(java.lang.Boolean isShowInList) {
		set("is_show_in_list", isShowInList);
	}
	
	/**
	 * 是否在列表显示
	 */
	public java.lang.Boolean getIsShowInList() {
		return get("is_show_in_list");
	}
	
	/**
	 * 是否在表单显示
	 */
	public void setIsShowInForm(java.lang.Boolean isShowInForm) {
		set("is_show_in_form", isShowInForm);
	}
	
	/**
	 * 是否在表单显示
	 */
	public java.lang.Boolean getIsShowInForm() {
		return get("is_show_in_form");
	}
	
	/**
	 * 是否在查询条件显示
	 */
	public void setIsShowInQuery(java.lang.Boolean isShowInQuery) {
		set("is_show_in_query", isShowInQuery);
	}
	
	/**
	 * 是否在查询条件显示
	 */
	public java.lang.Boolean getIsShowInQuery() {
		return get("is_show_in_query");
	}
	
	/**
	 * 查询方式
	 */
	public void setQueryType(java.lang.Integer queryType) {
		set("query_type", queryType);
	}
	
	/**
	 * 查询方式
	 */
	public java.lang.Integer getQueryType() {
		return getInt("query_type");
	}
	
	/**
	 * 表单类型
	 */
	public void setFormType(java.lang.Integer formType) {
		set("form_type", formType);
	}
	
	/**
	 * 表单类型
	 */
	public java.lang.Integer getFormType() {
		return getInt("form_type");
	}
	
	/**
	 * 字典类型
	 */
	public void setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
	}
	
	/**
	 * 字典类型
	 */
	public java.lang.String getDictType() {
		return getStr("dict_type");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
}

