package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStationBase<M extends BaseGasStationBase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCurrentFlag(java.lang.String currentFlag) {
		set("current_flag", currentFlag);
	}
	
	public java.lang.String getCurrentFlag() {
		return getStr("current_flag");
	}
	
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	public void setStsDate(java.lang.String stsDate) {
		set("sts_date", stsDate);
	}
	
	public java.lang.String getStsDate() {
		return getStr("sts_date");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
	/**
	 * 政府平台的记录id
	 */
	public void setOrgInfoId(java.lang.String orgInfoId) {
		set("org_info_id", orgInfoId);
	}
	
	/**
	 * 政府平台的记录id
	 */
	public java.lang.String getOrgInfoId() {
		return getStr("org_info_id");
	}
	
	public void setOrgDeptId(java.lang.String orgDeptId) {
		set("org_dept_id", orgDeptId);
	}
	
	public java.lang.String getOrgDeptId() {
		return getStr("org_dept_id");
	}
	
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	public void setAgent(java.lang.String agent) {
		set("agent", agent);
	}
	
	public java.lang.String getAgent() {
		return getStr("agent");
	}
	
	public void setAgentIdcard(java.lang.String agentIdcard) {
		set("agent_idcard", agentIdcard);
	}
	
	public java.lang.String getAgentIdcard() {
		return getStr("agent_idcard");
	}
	
	public void setAgentPhone(java.lang.String agentPhone) {
		set("agent_phone", agentPhone);
	}
	
	public java.lang.String getAgentPhone() {
		return getStr("agent_phone");
	}
	
	public void setProvinceCode(java.lang.String provinceCode) {
		set("province_code", provinceCode);
	}
	
	public java.lang.String getProvinceCode() {
		return getStr("province_code");
	}
	
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}
	
	public void setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
	}
	
	public java.lang.String getCityCode() {
		return getStr("city_code");
	}
	
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}
	
	public void setCountyCode(java.lang.String countyCode) {
		set("county_code", countyCode);
	}
	
	public java.lang.String getCountyCode() {
		return getStr("county_code");
	}
	
	public void setCounty(java.lang.String county) {
		set("county", county);
	}
	
	public java.lang.String getCounty() {
		return getStr("county");
	}
	
	public void setTownCode(java.lang.String townCode) {
		set("town_code", townCode);
	}
	
	public java.lang.String getTownCode() {
		return getStr("town_code");
	}
	
	public void setTown(java.lang.String town) {
		set("town", town);
	}
	
	public java.lang.String getTown() {
		return getStr("town");
	}
	
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}
	
	public void setFullName(java.lang.String fullName) {
		set("full_name", fullName);
	}
	
	public java.lang.String getFullName() {
		return getStr("full_name");
	}
	
	public void setLegalRepresentative(java.lang.String legalRepresentative) {
		set("legal_representative", legalRepresentative);
	}
	
	public java.lang.String getLegalRepresentative() {
		return getStr("legal_representative");
	}
	
	public void setLrIdcard(java.lang.String lrIdcard) {
		set("lr_idcard", lrIdcard);
	}
	
	public java.lang.String getLrIdcard() {
		return getStr("lr_idcard");
	}
	
	public void setLrPhone(java.lang.String lrPhone) {
		set("lr_phone", lrPhone);
	}
	
	public java.lang.String getLrPhone() {
		return getStr("lr_phone");
	}
	
	public void setOrgType(java.lang.String orgType) {
		set("org_type", orgType);
	}
	
	public java.lang.String getOrgType() {
		return getStr("org_type");
	}
	
	public void setUscc(java.lang.String uscc) {
		set("uscc", uscc);
	}
	
	public java.lang.String getUscc() {
		return getStr("uscc");
	}
	
}

