package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScpVideoFile<M extends BaseScpVideoFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setVideoId(java.lang.String videoId) {
		set("video_id", videoId);
	}
	
	public java.lang.String getVideoId() {
		return getStr("video_id");
	}
	
	public void setVideoPath(java.lang.String videoPath) {
		set("video_path", videoPath);
	}
	
	public java.lang.String getVideoPath() {
		return getStr("video_path");
	}
	
	public void setVideoType(java.lang.String videoType) {
		set("video_type", videoType);
	}
	
	public java.lang.String getVideoType() {
		return getStr("video_type");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}
	
	/**
	 * 创建时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}
	
}

