package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPost<M extends BaseSysPost<M>> extends Model<M> implements IBean {

	/**
	 * 岗位ID
	 */
	public void setPostId(java.lang.Long postId) {
		set("post_id", postId);
	}
	
	/**
	 * 岗位ID
	 */
	public java.lang.Long getPostId() {
		return getLong("post_id");
	}
	
	/**
	 * 岗位编码
	 */
	public void setPostCode(java.lang.String postCode) {
		set("post_code", postCode);
	}
	
	/**
	 * 岗位编码
	 */
	public java.lang.String getPostCode() {
		return getStr("post_code");
	}
	
	/**
	 * 岗位名称
	 */
	public void setPostName(java.lang.String postName) {
		set("post_name", postName);
	}
	
	/**
	 * 岗位名称
	 */
	public java.lang.String getPostName() {
		return getStr("post_name");
	}
	
	/**
	 * 显示顺序
	 */
	public void setPostSort(java.lang.Integer postSort) {
		set("post_sort", postSort);
	}
	
	/**
	 * 显示顺序
	 */
	public java.lang.Integer getPostSort() {
		return getInt("post_sort");
	}
	
	/**
	 * 状态（0正常 1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态（0正常 1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

