package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzLocks<M extends BaseQrtzLocks<M>> extends Model<M> implements IBean {

	/**
	 * 调度名称
	 */
	public void setSchedName(java.lang.String schedName) {
		set("sched_name", schedName);
	}
	
	/**
	 * 调度名称
	 */
	public java.lang.String getSchedName() {
		return getStr("sched_name");
	}
	
	/**
	 * 悲观锁名称
	 */
	public void setLockName(java.lang.String lockName) {
		set("lock_name", lockName);
	}
	
	/**
	 * 悲观锁名称
	 */
	public java.lang.String getLockName() {
		return getStr("lock_name");
	}
	
}

