package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGasStationRemoteMap<M extends BaseGasStationRemoteMap<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	public java.lang.String getStationName() {
		return getStr("station_name");
	}
	
	public void setStationRemoteUrl(java.lang.String stationRemoteUrl) {
		set("station_remote_url", stationRemoteUrl);
	}
	
	public java.lang.String getStationRemoteUrl() {
		return getStr("station_remote_url");
	}
	
	public void setStationAccessCredentials(java.lang.String stationAccessCredentials) {
		set("station_access_credentials", stationAccessCredentials);
	}
	
	public java.lang.String getStationAccessCredentials() {
		return getStr("station_access_credentials");
	}
	
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}

