package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysJob<M extends BaseSysJob<M>> extends Model<M> implements IBean {

	/**
	 * 任务ID
	 */
	public void setJobId(java.lang.Long jobId) {
		set("job_id", jobId);
	}
	
	/**
	 * 任务ID
	 */
	public java.lang.Long getJobId() {
		return getLong("job_id");
	}
	
	/**
	 * 任务名称
	 */
	public void setJobName(java.lang.String jobName) {
		set("job_name", jobName);
	}
	
	/**
	 * 任务名称
	 */
	public java.lang.String getJobName() {
		return getStr("job_name");
	}
	
	/**
	 * 任务组名
	 */
	public void setJobGroup(java.lang.String jobGroup) {
		set("job_group", jobGroup);
	}
	
	/**
	 * 任务组名
	 */
	public java.lang.String getJobGroup() {
		return getStr("job_group");
	}
	
	/**
	 * 调用目标字符串
	 */
	public void setInvokeTarget(java.lang.String invokeTarget) {
		set("invoke_target", invokeTarget);
	}
	
	/**
	 * 调用目标字符串
	 */
	public java.lang.String getInvokeTarget() {
		return getStr("invoke_target");
	}
	
	/**
	 * cron执行表达式
	 */
	public void setCronExpression(java.lang.String cronExpression) {
		set("cron_expression", cronExpression);
	}
	
	/**
	 * cron执行表达式
	 */
	public java.lang.String getCronExpression() {
		return getStr("cron_expression");
	}
	
	/**
	 * 计划执行错误策略（1立即执行 2执行一次 3放弃执行）
	 */
	public void setMisfirePolicy(java.lang.String misfirePolicy) {
		set("misfire_policy", misfirePolicy);
	}
	
	/**
	 * 计划执行错误策略（1立即执行 2执行一次 3放弃执行）
	 */
	public java.lang.String getMisfirePolicy() {
		return getStr("misfire_policy");
	}
	
	/**
	 * 是否并发执行（0允许 1禁止）
	 */
	public void setConcurrent(java.lang.String concurrent) {
		set("concurrent", concurrent);
	}
	
	/**
	 * 是否并发执行（0允许 1禁止）
	 */
	public java.lang.String getConcurrent() {
		return getStr("concurrent");
	}
	
	/**
	 * 状态（0正常 1暂停）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态（0正常 1暂停）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 创建者
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 更新者
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 更新者
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注信息
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

