package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotCameraModelRegion<M extends BaseIotCameraModelRegion<M>> extends Model<M> implements IBean {

	/**
	 * 记录标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 记录标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 摄像机标识
	 */
	public void setCameraId(java.lang.Integer cameraId) {
		set("camera_id", cameraId);
	}
	
	/**
	 * 摄像机标识
	 */
	public java.lang.Integer getCameraId() {
		return getInt("camera_id");
	}
	
	/**
	 * 模型标识
	 */
	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}
	
	/**
	 * 模型标识
	 */
	public java.lang.Integer getModelId() {
		return getInt("model_id");
	}
	
	/**
	 * 模型名称
	 */
	public void setModelName(java.lang.String modelName) {
		set("model_name", modelName);
	}
	
	/**
	 * 模型名称
	 */
	public java.lang.String getModelName() {
		return getStr("model_name");
	}
	
	/**
	 * 模型缓存Key
	 */
	public void setModelKey(java.lang.String modelKey) {
		set("model_key", modelKey);
	}
	
	/**
	 * 模型缓存Key
	 */
	public java.lang.String getModelKey() {
		return getStr("model_key");
	}
	
	/**
	 * 模型版本
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * 模型版本
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}
	
	/**
	 * 模型检测事件
	 */
	public void setDetectEvent(java.lang.String detectEvent) {
		set("detect_event", detectEvent);
	}
	
	/**
	 * 模型检测事件
	 */
	public java.lang.String getDetectEvent() {
		return getStr("detect_event");
	}
	
	/**
	 * 检测区域起始点x坐标(百分比)
	 */
	public void setCx(java.lang.Double cx) {
		set("cx", cx);
	}
	
	/**
	 * 检测区域起始点x坐标(百分比)
	 */
	public java.lang.Double getCx() {
		return getDouble("cx");
	}
	
	/**
	 * 检测区域起始点y坐标(百分比)
	 */
	public void setCy(java.lang.Double cy) {
		set("cy", cy);
	}
	
	/**
	 * 检测区域起始点y坐标(百分比)
	 */
	public java.lang.Double getCy() {
		return getDouble("cy");
	}
	
	/**
	 * 检测区域宽度
	 */
	public void setWidth(java.lang.Double width) {
		set("width", width);
	}
	
	/**
	 * 检测区域宽度
	 */
	public java.lang.Double getWidth() {
		return getDouble("width");
	}
	
	/**
	 * 检测区域高度
	 */
	public void setHeight(java.lang.Double height) {
		set("height", height);
	}
	
	/**
	 * 检测区域高度
	 */
	public java.lang.Double getHeight() {
		return getDouble("height");
	}
	
	/**
	 * 参数json串
	 */
	public void setParamJson(java.lang.String paramJson) {
		set("param_json", paramJson);
	}
	
	/**
	 * 参数json串
	 */
	public java.lang.String getParamJson() {
		return getStr("param_json");
	}
	
	/**
	 * 状态
	 */
	public void setSts(java.lang.String sts) {
		set("sts", sts);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getSts() {
		return getStr("sts");
	}
	
	/**
	 * 状态时间
	 */
	public void setStsDate(java.util.Date stsDate) {
		set("sts_date", stsDate);
	}
	
	/**
	 * 状态时间
	 */
	public java.util.Date getStsDate() {
		return getDate("sts_date");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	/**
	 * 修改人
	 */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
}

