package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlcxinhao<M extends BasePlcxinhao<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 气瓶间报警，plc地址100，0正常，10是报警
	 */
	public void setQipingjianbaojing(java.lang.String qipingjianbaojing) {
		set("qipingjianbaojing", qipingjianbaojing);
	}
	
	/**
	 * 气瓶间报警，plc地址100，0正常，10是报警
	 */
	public java.lang.String getQipingjianbaojing() {
		return getStr("qipingjianbaojing");
	}
	
	/**
	 * 厨房泄露报警，plc101地址，0正常，10报警
	 */
	public void setChufangbaojing(java.lang.String chufangbaojing) {
		set("chufangbaojing", chufangbaojing);
	}
	
	/**
	 * 厨房泄露报警，plc101地址，0正常，10报警
	 */
	public java.lang.String getChufangbaojing() {
		return getStr("chufangbaojing");
	}
	
	/**
	 * 烟感报警，plc地址102，预留，0正常，10报警
	 */
	public void setYanganbaojing(java.lang.String yanganbaojing) {
		set("yanganbaojing", yanganbaojing);
	}
	
	/**
	 * 烟感报警，plc地址102，预留，0正常，10报警
	 */
	public java.lang.String getYanganbaojing() {
		return getStr("yanganbaojing");
	}
	
	/**
	 * 切断阀,0是关闭，10是打开
	 */
	public void setQieduanfa(java.lang.String qieduanfa) {
		set("qieduanfa", qieduanfa);
	}
	
	/**
	 * 切断阀,0是关闭，10是打开
	 */
	public java.lang.String getQieduanfa() {
		return getStr("qieduanfa");
	}
	
	/**
	 * 风机状态，0关，10是打开
	 */
	public void setFengji(java.lang.String fengji) {
		set("fengji", fengji);
	}
	
	/**
	 * 风机状态，0关，10是打开
	 */
	public java.lang.String getFengji() {
		return getStr("fengji");
	}
	
	/**
	 * 通道1，0是关闭，10是打开
	 */
	public void setTongdaoone(java.lang.String tongdaoone) {
		set("tongdaoone", tongdaoone);
	}
	
	/**
	 * 通道1，0是关闭，10是打开
	 */
	public java.lang.String getTongdaoone() {
		return getStr("tongdaoone");
	}
	
	/**
	 * 通道2，0是关闭，10是打开
	 */
	public void setTongdaotwo(java.lang.String tongdaotwo) {
		set("tongdaotwo", tongdaotwo);
	}
	
	/**
	 * 通道2，0是关闭，10是打开
	 */
	public java.lang.String getTongdaotwo() {
		return getStr("tongdaotwo");
	}
	
	/**
	 * 通道3，0是关闭，10是打开
	 */
	public void setTongdaothree(java.lang.String tongdaothree) {
		set("tongdaothree", tongdaothree);
	}
	
	/**
	 * 通道3，0是关闭，10是打开
	 */
	public java.lang.String getTongdaothree() {
		return getStr("tongdaothree");
	}
	
	/**
	 * 通道4，0是关闭，10是打开
	 */
	public void setTongdaofour(java.lang.String tongdaofour) {
		set("tongdaofour", tongdaofour);
	}
	
	/**
	 * 通道4，0是关闭，10是打开
	 */
	public java.lang.String getTongdaofour() {
		return getStr("tongdaofour");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * plc编号，也就是以前的小盒子编号。这个对应这个像盒子是哪个饭店安装的
	 */
	public void setPlcno(java.lang.String plcno) {
		set("plcno", plcno);
	}
	
	/**
	 * plc编号，也就是以前的小盒子编号。这个对应这个像盒子是哪个饭店安装的
	 */
	public java.lang.String getPlcno() {
		return getStr("plcno");
	}
	
	/**
	 * rfid标签
	 */
	public void setRfidno(java.lang.String rfidno) {
		set("rfidno", rfidno);
	}
	
	/**
	 * rfid标签
	 */
	public java.lang.String getRfidno() {
		return getStr("rfidno");
	}
	
}

