package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceRecords<M extends BaseDeviceRecords<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setDeviceName(java.lang.String deviceName) {
		set("device_name", deviceName);
	}
	
	public java.lang.String getDeviceName() {
		return getStr("device_name");
	}
	
	public void setBelongtoProduct(java.lang.Long belongtoProduct) {
		set("belongto_product", belongtoProduct);
	}
	
	public java.lang.Long getBelongtoProduct() {
		return getLong("belongto_product");
	}
	
	public void setClientId(java.lang.String clientId) {
		set("client_id", clientId);
	}
	
	public java.lang.String getClientId() {
		return getStr("client_id");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}
	
	public void setMqtthosturl(java.lang.String mqtthosturl) {
		set("mqtthosturl", mqtthosturl);
	}
	
	public java.lang.String getMqtthosturl() {
		return getStr("mqtthosturl");
	}
	
	public void setPort(java.lang.String port) {
		set("port", port);
	}
	
	public java.lang.String getPort() {
		return getStr("port");
	}
	
}

