package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceCtrlCloudRecord<M extends BaseDeviceCtrlCloudRecord<M>> extends Model<M> implements IBean {

	/**
	 * 记录标识
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 记录标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 加气枪号
	 */
	public void setGunNo(java.lang.Integer gunNo) {
		set("gun_no", gunNo);
	}
	
	/**
	 * 加气枪号
	 */
	public java.lang.Integer getGunNo() {
		return getInt("gun_no");
	}
	
	/**
	 * 控制指令：1 开始加气，0 停止加气
	 */
	public void setCtrlCmd(java.lang.String ctrlCmd) {
		set("ctrl_cmd", ctrlCmd);
	}
	
	/**
	 * 控制指令：1 开始加气，0 停止加气
	 */
	public java.lang.String getCtrlCmd() {
		return getStr("ctrl_cmd");
	}
	
	/**
	 * 指令下发时间
	 */
	public void setCtrlCmdTime(java.util.Date ctrlCmdTime) {
		set("ctrl_cmd_time", ctrlCmdTime);
	}
	
	/**
	 * 指令下发时间
	 */
	public java.util.Date getCtrlCmdTime() {
		return getDate("ctrl_cmd_time");
	}
	
	/**
	 * 处理标识：0 未处理，1 已处理
	 */
	public void setProcessFlag(java.lang.String processFlag) {
		set("process_flag", processFlag);
	}
	
	/**
	 * 处理标识：0 未处理，1 已处理
	 */
	public java.lang.String getProcessFlag() {
		return getStr("process_flag");
	}
	
	/**
	 * 处理时间
	 */
	public void setProcessTime(java.util.Date processTime) {
		set("process_time", processTime);
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getProcessTime() {
		return getDate("process_time");
	}
	
	/**
	 * 处理次数
	 */
	public void setProcessCount(java.lang.String processCount) {
		set("process_count", processCount);
	}
	
	/**
	 * 处理次数
	 */
	public java.lang.String getProcessCount() {
		return getStr("process_count");
	}
	
	/**
	 * 结果编码：0 处理失败，1 处理成功
	 */
	public void setResultCode(java.lang.String resultCode) {
		set("result_code", resultCode);
	}
	
	/**
	 * 结果编码：0 处理失败，1 处理成功
	 */
	public java.lang.String getResultCode() {
		return getStr("result_code");
	}
	
	/**
	 * 结果描述
	 */
	public void setResultMsg(java.lang.String resultMsg) {
		set("result_msg", resultMsg);
	}
	
	/**
	 * 结果描述
	 */
	public java.lang.String getResultMsg() {
		return getStr("result_msg");
	}
	
	/**
	 * 站点编码
	 */
	public void setStationCode(java.lang.String stationCode) {
		set("station_code", stationCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getStationCode() {
		return getStr("station_code");
	}
	
	/**
	 * 车牌号码
	 */
	public void setPlate(java.lang.String plate) {
		set("plate", plate);
	}
	
	/**
	 * 车牌号码
	 */
	public java.lang.String getPlate() {
		return getStr("plate");
	}
	
	/**
	 * 充装记录ID
	 */
	public void setFillId(java.lang.String fillId) {
		set("fill_id", fillId);
	}
	
	/**
	 * 充装记录ID
	 */
	public java.lang.String getFillId() {
		return getStr("fill_id");
	}
	
	/**
	 * 控枪接口地址
	 */
	public void setRestUrl(java.lang.String restUrl) {
		set("rest_url", restUrl);
	}
	
	/**
	 * 控枪接口地址
	 */
	public java.lang.String getRestUrl() {
		return getStr("rest_url");
	}
	
	/**
	 * 指令加密信息
	 */
	public void setCmdEncode(java.lang.String cmdEncode) {
		set("cmd_encode", cmdEncode);
	}
	
	/**
	 * 指令加密信息
	 */
	public java.lang.String getCmdEncode() {
		return getStr("cmd_encode");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
}

