package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDrivercar<M extends BaseDrivercar<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setDrivername(java.lang.String drivername) {
		set("drivername", drivername);
	}
	
	public java.lang.String getDrivername() {
		return getStr("drivername");
	}
	
	public void setDriverphone(java.lang.String driverphone) {
		set("driverphone", driverphone);
	}
	
	public java.lang.String getDriverphone() {
		return getStr("driverphone");
	}
	
	public void setDriverbirthday(java.util.Date driverbirthday) {
		set("driverbirthday", driverbirthday);
	}
	
	public java.util.Date getDriverbirthday() {
		return getDate("driverbirthday");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdentityCardNo(java.lang.String identityCardNo) {
		set("identity_card_no", identityCardNo);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdentityCardNo() {
		return getStr("identity_card_no");
	}
	
	public void setIdentityCardNoImgUrl(java.lang.String identityCardNoImgUrl) {
		set("identity_card_no_img_url", identityCardNoImgUrl);
	}
	
	public java.lang.String getIdentityCardNoImgUrl() {
		return getStr("identity_card_no_img_url");
	}
	
	public void setDriverpsw(java.lang.String driverpsw) {
		set("driverpsw", driverpsw);
	}
	
	public java.lang.String getDriverpsw() {
		return getStr("driverpsw");
	}
	
	public void setDriversex(java.lang.String driversex) {
		set("driversex", driversex);
	}
	
	public java.lang.String getDriversex() {
		return getStr("driversex");
	}
	
	/**
	 * 车牌号
	 */
	public void setDrivercarno(java.lang.String drivercarno) {
		set("drivercarno", drivercarno);
	}
	
	/**
	 * 车牌号
	 */
	public java.lang.String getDrivercarno() {
		return getStr("drivercarno");
	}
	
	/**
	 * 车品牌
	 */
	public void setCarname(java.lang.String carname) {
		set("carname", carname);
	}
	
	/**
	 * 车品牌
	 */
	public java.lang.String getCarname() {
		return getStr("carname");
	}
	
	public void setCarcolor(java.lang.String carcolor) {
		set("carcolor", carcolor);
	}
	
	public java.lang.String getCarcolor() {
		return getStr("carcolor");
	}
	
	public void setCarshengchanriqi(java.lang.String carshengchanriqi) {
		set("carshengchanriqi", carshengchanriqi);
	}
	
	public java.lang.String getCarshengchanriqi() {
		return getStr("carshengchanriqi");
	}
	
	/**
	 * 驾驶证照片ossid
	 */
	public void setDriverLicenseImageOssId(java.lang.String driverLicenseImageOssId) {
		set("driver_license_image_oss_id", driverLicenseImageOssId);
	}
	
	/**
	 * 驾驶证照片ossid
	 */
	public java.lang.String getDriverLicenseImageOssId() {
		return getStr("driver_license_image_oss_id");
	}
	
	public void setDriverLicenseImageUrl(java.lang.String driverLicenseImageUrl) {
		set("driver_license_image_url", driverLicenseImageUrl);
	}
	
	public java.lang.String getDriverLicenseImageUrl() {
		return getStr("driver_license_image_url");
	}
	
	/**
	 * 车辆照片ossid
	 */
	public void setCarImageOssId(java.lang.String carImageOssId) {
		set("car_image_oss_id", carImageOssId);
	}
	
	/**
	 * 车辆照片ossid
	 */
	public java.lang.String getCarImageOssId() {
		return getStr("car_image_oss_id");
	}
	
	public void setCarImageUrl(java.lang.String carImageUrl) {
		set("car_image_url", carImageUrl);
	}
	
	public java.lang.String getCarImageUrl() {
		return getStr("car_image_url");
	}
	
	public void setRiskCargoLicenseNo(java.lang.String riskCargoLicenseNo) {
		set("risk_cargo_license_no", riskCargoLicenseNo);
	}
	
	public java.lang.String getRiskCargoLicenseNo() {
		return getStr("risk_cargo_license_no");
	}
	
	public void setRiskCargoLicenseIndate(java.lang.String riskCargoLicenseIndate) {
		set("risk_cargo_license_indate", riskCargoLicenseIndate);
	}
	
	public java.lang.String getRiskCargoLicenseIndate() {
		return getStr("risk_cargo_license_indate");
	}
	
	public void setRiskCargoLicenseImageOssId(java.lang.String riskCargoLicenseImageOssId) {
		set("risk_cargo_license_image_oss_id", riskCargoLicenseImageOssId);
	}
	
	public java.lang.String getRiskCargoLicenseImageOssId() {
		return getStr("risk_cargo_license_image_oss_id");
	}
	
	public void setRiskCargoLicenseImageUrl(java.lang.String riskCargoLicenseImageUrl) {
		set("risk_cargo_license_image_url", riskCargoLicenseImageUrl);
	}
	
	public java.lang.String getRiskCargoLicenseImageUrl() {
		return getStr("risk_cargo_license_image_url");
	}
	
	public void setOtherImageUrl(java.lang.String otherImageUrl) {
		set("other_image_url", otherImageUrl);
	}
	
	public java.lang.String getOtherImageUrl() {
		return getStr("other_image_url");
	}
	
	/**
	 * 更新标识，1为后台，2为app端
	 */
	public void setUpdateSign(java.lang.Integer updateSign) {
		set("update_sign", updateSign);
	}
	
	/**
	 * 更新标识，1为后台，2为app端
	 */
	public java.lang.Integer getUpdateSign() {
		return getInt("update_sign");
	}
	
	public void setYayunyuanxingming(java.lang.String yayunyuanxingming) {
		set("yayunyuanxingming", yayunyuanxingming);
	}
	
	public java.lang.String getYayunyuanxingming() {
		return getStr("yayunyuanxingming");
	}
	
	public void setYayinyuanzhengjian(java.lang.String yayinyuanzhengjian) {
		set("yayinyuanzhengjian", yayinyuanzhengjian);
	}
	
	public java.lang.String getYayinyuanzhengjian() {
		return getStr("yayinyuanzhengjian");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
}

