package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAutoAnnualInspection<M extends BaseAutoAnnualInspection<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setLicensePlate(java.lang.String licensePlate) {
		set("license_plate", licensePlate);
	}
	
	public java.lang.String getLicensePlate() {
		return getStr("license_plate");
	}
	
	public void setKind(java.lang.String kind) {
		set("kind", kind);
	}
	
	public java.lang.String getKind() {
		return getStr("kind");
	}
	
	public void setOwner(java.lang.String owner) {
		set("owner", owner);
	}
	
	public java.lang.String getOwner() {
		return getStr("owner");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	public void setGasBottleNo(java.lang.String gasBottleNo) {
		set("gas_bottle_no", gasBottleNo);
	}
	
	public java.lang.String getGasBottleNo() {
		return getStr("gas_bottle_no");
	}
	
	public void setValidTime(java.util.Date validTime) {
		set("valid_time", validTime);
	}
	
	public java.util.Date getValidTime() {
		return getDate("valid_time");
	}
	
	public void setAnnualInspectDate(java.util.Date annualInspectDate) {
		set("annual_inspect_date", annualInspectDate);
	}
	
	public java.util.Date getAnnualInspectDate() {
		return getDate("annual_inspect_date");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setGasBottleExnum(java.lang.String gasBottleExnum) {
		set("gas_bottle_exnum", gasBottleExnum);
	}
	
	public java.lang.String getGasBottleExnum() {
		return getStr("gas_bottle_exnum");
	}
	
	public void setBotRegistration(java.lang.String botRegistration) {
		set("bot_registration", botRegistration);
	}
	
	public java.lang.String getBotRegistration() {
		return getStr("bot_registration");
	}
	
	public void setUnitName(java.lang.String unitName) {
		set("unit_name", unitName);
	}
	
	public java.lang.String getUnitName() {
		return getStr("unit_name");
	}
	
	public void setUnitAddress(java.lang.String unitAddress) {
		set("unit_address", unitAddress);
	}
	
	public java.lang.String getUnitAddress() {
		return getStr("unit_address");
	}
	
	public void setTestUnit(java.lang.String testUnit) {
		set("test_unit", testUnit);
	}
	
	public java.lang.String getTestUnit() {
		return getStr("test_unit");
	}
	
	public void setTestDate(java.lang.String testDate) {
		set("test_date", testDate);
	}
	
	public java.lang.String getTestDate() {
		return getStr("test_date");
	}
	
	public void setBotType(java.lang.String botType) {
		set("bot_type", botType);
	}
	
	public java.lang.String getBotType() {
		return getStr("bot_type");
	}
	
	public void setBotMedium(java.lang.String botMedium) {
		set("bot_medium", botMedium);
	}
	
	public java.lang.String getBotMedium() {
		return getStr("bot_medium");
	}
	
	public void setRegistrationFile(java.lang.String registrationFile) {
		set("registration_file", registrationFile);
	}
	
	public java.lang.String getRegistrationFile() {
		return getStr("registration_file");
	}
	
	public void setUseRegistrationFile(java.lang.String useRegistrationFile) {
		set("use_registration_file", useRegistrationFile);
	}
	
	public java.lang.String getUseRegistrationFile() {
		return getStr("use_registration_file");
	}
	
	public void setIdCode(java.lang.String idCode) {
		set("id_code", idCode);
	}
	
	public java.lang.String getIdCode() {
		return getStr("id_code");
	}
	
	public void setSyncSts(java.lang.String syncSts) {
		set("sync_sts", syncSts);
	}
	
	public java.lang.String getSyncSts() {
		return getStr("sync_sts");
	}
	
}

