package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserStation<M extends BaseSysUserStation<M>> extends Model<M> implements IBean {

	/**
	 * 用户名
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 站点编码
	 */
	public void setStationCode(java.lang.String stationCode) {
		set("station_code", stationCode);
	}
	
	/**
	 * 站点编码
	 */
	public java.lang.String getStationCode() {
		return getStr("station_code");
	}
	
}

