package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseMaintenanceCopy1<M extends BaseBseMaintenanceCopy1<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setKind(java.lang.String kind) {
		set("kind", kind);
	}
	
	public java.lang.String getKind() {
		return getStr("kind");
	}
	
	public void setCompanyid(java.lang.Integer companyid) {
		set("companyid", companyid);
	}
	
	public java.lang.Integer getCompanyid() {
		return getInt("companyid");
	}
	
	public void setEquipmentid(java.lang.Integer equipmentid) {
		set("equipmentid", equipmentid);
	}
	
	public java.lang.Integer getEquipmentid() {
		return getInt("equipmentid");
	}
	
	public void setReporter(java.lang.String reporter) {
		set("reporter", reporter);
	}
	
	public java.lang.String getReporter() {
		return getStr("reporter");
	}
	
	public void setReportday(java.lang.String reportday) {
		set("reportday", reportday);
	}
	
	public java.lang.String getReportday() {
		return getStr("reportday");
	}
	
	public void setRepairer(java.lang.String repairer) {
		set("repairer", repairer);
	}
	
	public java.lang.String getRepairer() {
		return getStr("repairer");
	}
	
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public void setRepairday(java.lang.String repairday) {
		set("repairday", repairday);
	}
	
	public java.lang.String getRepairday() {
		return getStr("repairday");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setProcess(java.lang.String process) {
		set("process", process);
	}
	
	public java.lang.String getProcess() {
		return getStr("process");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCheck(java.lang.String check) {
		set("check", check);
	}
	
	public java.lang.String getCheck() {
		return getStr("check");
	}
	
	public void setSign(java.lang.String sign) {
		set("sign", sign);
	}
	
	public java.lang.String getSign() {
		return getStr("sign");
	}
	
	public void setStep(java.lang.String step) {
		set("step", step);
	}
	
	public java.lang.String getStep() {
		return getStr("step");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setParentid(java.lang.String parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.String getParentid() {
		return getStr("parentid");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	public void setWritetime(java.lang.String writetime) {
		set("writetime", writetime);
	}
	
	public java.lang.String getWritetime() {
		return getStr("writetime");
	}
	
	public void setDeleteTime(java.util.Date deleteTime) {
		set("delete_time", deleteTime);
	}
	
	public java.util.Date getDeleteTime() {
		return getDate("delete_time");
	}
	
	public void setFid(java.lang.Integer fid) {
		set("fid", fid);
	}
	
	public java.lang.Integer getFid() {
		return getInt("fid");
	}
	
}

