package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePressureGaugeRecords1<M extends BasePressureGaugeRecords1<M>> extends Model<M> implements IBean {

	/**
	 * 无符号自增，主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 无符号自增，主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 控制器号，唯一标识
	 */
	public void setControllerId(java.lang.String controllerId) {
		set("controller_id", controllerId);
	}
	
	/**
	 * 控制器号，唯一标识
	 */
	public java.lang.String getControllerId() {
		return getStr("controller_id");
	}
	
	/**
	 * 当前状态。0：正常；1：异常；2：维修；3：其他
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 当前状态。0：正常；1：异常；2：维修；3：其他
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 外键，用户id，非空，首次创建记录时写入
	 */
	public void setCreatedId(java.lang.Integer createdId) {
		set("created_id", createdId);
	}
	
	/**
	 * 外键，用户id，非空，首次创建记录时写入
	 */
	public java.lang.Integer getCreatedId() {
		return getInt("created_id");
	}
	
	/**
	 * 非空，首次创建记录时写入数据库服务器时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 非空，首次创建记录时写入数据库服务器时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	public void setDakaifamen(java.lang.String dakaifamen) {
		set("dakaifamen", dakaifamen);
	}
	
	public java.lang.String getDakaifamen() {
		return getStr("dakaifamen");
	}
	
	public void setGuanbifamen(java.lang.String guanbifamen) {
		set("guanbifamen", guanbifamen);
	}
	
	public java.lang.String getGuanbifamen() {
		return getStr("guanbifamen");
	}
	
	/**
	 * 备用
	 */
	public void setXiafamingling(java.lang.String xiafamingling) {
		set("xiafamingling", xiafamingling);
	}
	
	/**
	 * 备用
	 */
	public java.lang.String getXiafamingling() {
		return getStr("xiafamingling");
	}
	
	public void setStoptime(java.lang.String stoptime) {
		set("stoptime", stoptime);
	}
	
	public java.lang.String getStoptime() {
		return getStr("stoptime");
	}
	
}

