package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUseDetail<M extends BaseUseDetail<M>> extends Model<M> implements IBean {

	public void setBottleId(java.lang.String bottleId) {
		set("bottle_id", bottleId);
	}
	
	public java.lang.String getBottleId() {
		return getStr("bottle_id");
	}
	
	public void setWeightId(java.lang.String weightId) {
		set("weight_id", weightId);
	}
	
	public java.lang.String getWeightId() {
		return getStr("weight_id");
	}
	
	public void setBindTime(java.util.Date bindTime) {
		set("bind_time", bindTime);
	}
	
	public java.util.Date getBindTime() {
		return getDate("bind_time");
	}
	
	public void setBindStaff(java.lang.String bindStaff) {
		set("bind_staff", bindStaff);
	}
	
	public java.lang.String getBindStaff() {
		return getStr("bind_staff");
	}
	
	/**
	 * 气瓶使用情况
	 */
	public void setBottleSize(java.lang.Double bottleSize) {
		set("bottle_size", bottleSize);
	}
	
	/**
	 * 气瓶使用情况
	 */
	public java.lang.Double getBottleSize() {
		return getDouble("bottle_size");
	}
	
	public void setNum(java.lang.Float num) {
		set("num", num);
	}
	
	public java.lang.Float getNum() {
		return getFloat("num");
	}
	
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
}

