package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotSyncRecords<M extends BaseIotSyncRecords<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 设备名称
	 */
	public void setDevicename(java.lang.String devicename) {
		set("devicename", devicename);
	}
	
	/**
	 * 设备名称
	 */
	public java.lang.String getDevicename() {
		return getStr("devicename");
	}
	
	/**
	 * 上传时间

	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 上传时间

	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 初始重量
	 */
	public void setValue1(java.lang.Double Value1) {
		set("Value1", Value1);
	}
	
	/**
	 * 初始重量
	 */
	public java.lang.Double getValue1() {
		return getDouble("Value1");
	}
	
	/**
	 * 实时重量
	 */
	public void setValue2(java.lang.Double Value2) {
		set("Value2", Value2);
	}
	
	/**
	 * 实时重量
	 */
	public java.lang.Double getValue2() {
		return getDouble("Value2");
	}
	
	/**
	 * 使用重量
	 */
	public void setValue3(java.lang.Double Value3) {
		set("Value3", Value3);
	}
	
	/**
	 * 使用重量
	 */
	public java.lang.Double getValue3() {
		return getDouble("Value3");
	}
	
	/**
	 * 电源状态
0：正常
1：故障
	 */
	public void setPowerStatus(java.lang.Integer PowerStatus) {
		set("PowerStatus", PowerStatus);
	}
	
	/**
	 * 电源状态
0：正常
1：故障
	 */
	public java.lang.Integer getPowerStatus() {
		return getInt("PowerStatus");
	}
	
	/**
	 * 阀门状态
0：关闭
1：开启
	 */
	public void setSwitchStatus(java.lang.Integer SwitchStatus) {
		set("SwitchStatus", SwitchStatus);
	}
	
	/**
	 * 阀门状态
0：关闭
1：开启
	 */
	public java.lang.Integer getSwitchStatus() {
		return getInt("SwitchStatus");
	}
	
	/**
	 * 报警状态
0：正常
1：故障
	 */
	public void setAlarm(java.lang.Integer Alarm) {
		set("Alarm", Alarm);
	}
	
	/**
	 * 报警状态
0：正常
1：故障
	 */
	public java.lang.Integer getAlarm() {
		return getInt("Alarm");
	}
	
	/**
	 * 用户编码

	 */
	public void setUser(java.lang.String user) {
		set("user", user);
	}
	
	/**
	 * 用户编码

	 */
	public java.lang.String getUser() {
		return getStr("user");
	}
	
}

