package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStationCurrent<M extends BaseStationCurrent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
	public void setStationname(java.lang.String stationname) {
		set("stationname", stationname);
	}
	
	public java.lang.String getStationname() {
		return getStr("stationname");
	}
	
	public void setCustumer(java.lang.String custumer) {
		set("custumer", custumer);
	}
	
	public java.lang.String getCustumer() {
		return getStr("custumer");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCreattime(java.util.Date creattime) {
		set("creattime", creattime);
	}
	
	public java.util.Date getCreattime() {
		return getDate("creattime");
	}
	
	public void setRemark1(java.lang.String remark1) {
		set("remark1", remark1);
	}
	
	public java.lang.String getRemark1() {
		return getStr("remark1");
	}
	
	public void setRemark2(java.lang.String remark2) {
		set("remark2", remark2);
	}
	
	public java.lang.String getRemark2() {
		return getStr("remark2");
	}
	
	public void setRemark3(java.lang.String remark3) {
		set("remark3", remark3);
	}
	
	public java.lang.String getRemark3() {
		return getStr("remark3");
	}
	
}

