package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBseEquipOperation<M extends BaseBseEquipOperation<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 生产厂商
	 */
	public void setFactory(java.lang.String factory) {
		set("factory", factory);
	}
	
	/**
	 * 生产厂商
	 */
	public java.lang.String getFactory() {
		return getStr("factory");
	}
	
	/**
	 * 型号规格
	 */
	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	/**
	 * 型号规格
	 */
	public java.lang.String getModel() {
		return getStr("model");
	}
	
	/**
	 * 设备名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 设备名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 操作类型：维修  更新  删除
	 */
	public void setOperationType(java.lang.String operationType) {
		set("operation_type", operationType);
	}
	
	/**
	 * 操作类型：维修  更新  删除
	 */
	public java.lang.String getOperationType() {
		return getStr("operation_type");
	}
	
	/**
	 * 创建时间。应取创建记录时的数据库时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间。应取创建记录时的数据库时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
	/**
	 * 操作人姓名
	 */
	public void setStaff(java.lang.String staff) {
		set("staff", staff);
	}
	
	/**
	 * 操作人姓名
	 */
	public java.lang.String getStaff() {
		return getStr("staff");
	}
	
}

