package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasBill<M extends BaseBasBill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 订气数量
	 */
	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	/**
	 * 订气数量
	 */
	public java.lang.Integer getNumber() {
		return getInt("number");
	}
	
	/**
	 * 公司
	 */
	public void setStation(java.lang.String station) {
		set("station", station);
	}
	
	/**
	 * 公司
	 */
	public java.lang.String getStation() {
		return getStr("station");
	}
	
	/**
	 * 顾客电话
	 */
	public void setBuyer(java.lang.String buyer) {
		set("buyer", buyer);
	}
	
	/**
	 * 顾客电话
	 */
	public java.lang.String getBuyer() {
		return getStr("buyer");
	}
	
	/**
	 * 司机
	 */
	public void setDriver(java.lang.String driver) {
		set("driver", driver);
	}
	
	/**
	 * 司机
	 */
	public java.lang.String getDriver() {
		return getStr("driver");
	}
	
	/**
	 * 价格
	 */
	public void setPrice(java.lang.Integer price) {
		set("price", price);
	}
	
	/**
	 * 价格
	 */
	public java.lang.Integer getPrice() {
		return getInt("price");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setYuliu(java.lang.String yuliu) {
		set("yuliu", yuliu);
	}
	
	public java.lang.String getYuliu() {
		return getStr("yuliu");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 期待接单时间
	 */
	public void setExpectTime(java.util.Date expectTime) {
		set("expect_time", expectTime);
	}
	
	/**
	 * 期待接单时间
	 */
	public java.util.Date getExpectTime() {
		return getDate("expect_time");
	}
	
	/**
	 * 气瓶规格
	 */
	public void setGasSpecification(java.lang.String gasSpecification) {
		set("gas_specification", gasSpecification);
	}
	
	/**
	 * 气瓶规格
	 */
	public java.lang.String getGasSpecification() {
		return getStr("gas_specification");
	}
	
	/**
	 * 饭店名称
	 */
	public void setRestaurant(java.lang.String restaurant) {
		set("restaurant", restaurant);
	}
	
	/**
	 * 饭店名称
	 */
	public java.lang.String getRestaurant() {
		return getStr("restaurant");
	}
	
	/**
	 * 饭店id
	 */
	public void setRestaurantid(java.lang.Integer restaurantid) {
		set("restaurantid", restaurantid);
	}
	
	/**
	 * 饭店id
	 */
	public java.lang.Integer getRestaurantid() {
		return getInt("restaurantid");
	}
	
	/**
	 * 接单状态
	 */
	public void setJiedanstatus(java.lang.Integer jiedanstatus) {
		set("jiedanstatus", jiedanstatus);
	}
	
	/**
	 * 接单状态
	 */
	public java.lang.Integer getJiedanstatus() {
		return getInt("jiedanstatus");
	}
	
	/**
	 * 顾客名称
	 */
	public void setCustormer(java.lang.String custormer) {
		set("custormer", custormer);
	}
	
	/**
	 * 顾客名称
	 */
	public java.lang.String getCustormer() {
		return getStr("custormer");
	}
	
	/**
	 * 接单时间
	 */
	public void setJiedanshijian(java.util.Date jiedanshijian) {
		set("jiedanshijian", jiedanshijian);
	}
	
	/**
	 * 接单时间
	 */
	public java.util.Date getJiedanshijian() {
		return getDate("jiedanshijian");
	}
	
	/**
	 * 客户端数据id
	 */
	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	/**
	 * 客户端数据id
	 */
	public java.lang.Integer getBid() {
		return getInt("bid");
	}
	
	/**
	 * 加气站编号
	 */
	public void setStationId(java.lang.Integer stationId) {
		set("station_id", stationId);
	}
	
	/**
	 * 加气站编号
	 */
	public java.lang.Integer getStationId() {
		return getInt("station_id");
	}
	
}

