package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIotSyncRecordsV3<M extends BaseIotSyncRecordsV3<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * iot实例id
	 */
	public void setIotId(java.lang.String iotId) {
		set("iotId", iotId);
	}
	
	/**
	 * iot实例id
	 */
	public java.lang.String getIotId() {
		return getStr("iotId");
	}
	
	/**
	 * 产品key
	 */
	public void setProductKey(java.lang.String productKey) {
		set("productKey", productKey);
	}
	
	/**
	 * 产品key
	 */
	public java.lang.String getProductKey() {
		return getStr("productKey");
	}
	
	/**
	 * 设备名称
	 */
	public void setDevicename(java.lang.String devicename) {
		set("devicename", devicename);
	}
	
	/**
	 * 设备名称
	 */
	public java.lang.String getDevicename() {
		return getStr("devicename");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 请求id
	 */
	public void setRequestId(java.lang.String requestId) {
		set("requestId", requestId);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getRequestId() {
		return getStr("requestId");
	}
	
	/**
	 * 1号电机阀状态; 1-开，0-关
	 */
	public void setValveStatus1(java.lang.Integer ValveStatus1) {
		set("ValveStatus1", ValveStatus1);
	}
	
	/**
	 * 1号电机阀状态; 1-开，0-关
	 */
	public java.lang.Integer getValveStatus1() {
		return getInt("ValveStatus1");
	}
	
	/**
	 * 2号电机阀状态; 1-开，0-关
	 */
	public void setValveStatus2(java.lang.Integer ValveStatus2) {
		set("ValveStatus2", ValveStatus2);
	}
	
	/**
	 * 2号电机阀状态; 1-开，0-关
	 */
	public java.lang.Integer getValveStatus2() {
		return getInt("ValveStatus2");
	}
	
	/**
	 * 3号电机阀状态; 1-开，0-关
	 */
	public void setValveStatus3(java.lang.Integer ValveStatus3) {
		set("ValveStatus3", ValveStatus3);
	}
	
	/**
	 * 3号电机阀状态; 1-开，0-关
	 */
	public java.lang.Integer getValveStatus3() {
		return getInt("ValveStatus3");
	}
	
	/**
	 * 4号电机阀状态; 1-开，0-关
	 */
	public void setValveStatus4(java.lang.Integer ValveStatus4) {
		set("ValveStatus4", ValveStatus4);
	}
	
	/**
	 * 4号电机阀状态; 1-开，0-关
	 */
	public java.lang.Integer getValveStatus4() {
		return getInt("ValveStatus4");
	}
	
	/**
	 * 切断阀状态 1-开，0-关
	 */
	public void setMValstat(java.lang.Integer mValstat) {
		set("M_ValStat", mValstat);
	}
	
	/**
	 * 切断阀状态 1-开，0-关
	 */
	public java.lang.Integer getMValstat() {
		return getInt("M_ValStat");
	}
	
	/**
	 * 报警 1-操作间，2-气瓶间，3-视频，4-视频+操作间，5-压力表超压。
	 */
	public void setAlarm(java.lang.Integer Alarm) {
		set("Alarm", Alarm);
	}
	
	/**
	 * 报警 1-操作间，2-气瓶间，3-视频，4-视频+操作间，5-压力表超压。
	 */
	public java.lang.Integer getAlarm() {
		return getInt("Alarm");
	}
	
	/**
	 * 气体压力状态 0-正常，1-压力低于下限，2-超压。
	 */
	public void setGasPg(java.lang.Integer gasPg) {
		set("Gas_Pg", gasPg);
	}
	
	/**
	 * 气体压力状态 0-正常，1-压力低于下限，2-超压。
	 */
	public java.lang.Integer getGasPg() {
		return getInt("Gas_Pg");
	}
	
	/**
	 * 系统供电状态 0-正常，1-故障。
	 */
	public void setPowerStatus(java.lang.Integer PowerStatus) {
		set("PowerStatus", PowerStatus);
	}
	
	/**
	 * 系统供电状态 0-正常，1-故障。
	 */
	public java.lang.Integer getPowerStatus() {
		return getInt("PowerStatus");
	}
	
	/**
	 * 电子标签1 数组[14] 
	 */
	public void setRfid1(java.lang.String Rfid1) {
		set("Rfid1", Rfid1);
	}
	
	/**
	 * 电子标签1 数组[14] 
	 */
	public java.lang.String getRfid1() {
		return getStr("Rfid1");
	}
	
	/**
	 * 电子标签2 数组[14] 
	 */
	public void setRfid2(java.lang.String Rfid2) {
		set("Rfid2", Rfid2);
	}
	
	/**
	 * 电子标签2 数组[14] 
	 */
	public java.lang.String getRfid2() {
		return getStr("Rfid2");
	}
	
	/**
	 * 电子标签3 数组[14] 
	 */
	public void setRfid3(java.lang.String Rfid3) {
		set("Rfid3", Rfid3);
	}
	
	/**
	 * 电子标签3 数组[14] 
	 */
	public java.lang.String getRfid3() {
		return getStr("Rfid3");
	}
	
	/**
	 * 电子标签4 数组[14] 
	 */
	public void setRfid4(java.lang.String Rfid4) {
		set("Rfid4", Rfid4);
	}
	
	/**
	 * 电子标签4 数组[14] 
	 */
	public java.lang.String getRfid4() {
		return getStr("Rfid4");
	}
	
	/**
	 * 电子标签5 数组[14] 
	 */
	public void setRfid5(java.lang.String Rfid5) {
		set("Rfid5", Rfid5);
	}
	
	/**
	 * 电子标签5 数组[14] 
	 */
	public java.lang.String getRfid5() {
		return getStr("Rfid5");
	}
	
	/**
	 * 电子标签6 数组[14] 
	 */
	public void setRfid6(java.lang.String Rfid6) {
		set("Rfid6", Rfid6);
	}
	
	/**
	 * 电子标签6 数组[14] 
	 */
	public java.lang.String getRfid6() {
		return getStr("Rfid6");
	}
	
	/**
	 * 电子标签7 数组[14] 
	 */
	public void setRfid7(java.lang.String Rfid7) {
		set("Rfid7", Rfid7);
	}
	
	/**
	 * 电子标签7 数组[14] 
	 */
	public java.lang.String getRfid7() {
		return getStr("Rfid7");
	}
	
	/**
	 * 电子标签8 数组[14] 
	 */
	public void setRfid8(java.lang.String Rfid8) {
		set("Rfid8", Rfid8);
	}
	
	/**
	 * 电子标签8 数组[14] 
	 */
	public java.lang.String getRfid8() {
		return getStr("Rfid8");
	}
	
	/**
	 * 数据来源
	 */
	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getSource() {
		return getStr("source");
	}
	
	/**
	 * 数据内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 数据内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
}

