package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploaddianzibiaoqian<M extends BaseUploaddianzibiaoqian<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setDrivername(java.lang.String drivername) {
		set("drivername", drivername);
	}
	
	public java.lang.String getDrivername() {
		return getStr("drivername");
	}
	
	public void setDriverphone(java.lang.String driverphone) {
		set("driverphone", driverphone);
	}
	
	public java.lang.String getDriverphone() {
		return getStr("driverphone");
	}
	
	public void setDrivercarid(java.lang.String drivercarid) {
		set("drivercarid", drivercarid);
	}
	
	public java.lang.String getDrivercarid() {
		return getStr("drivercarid");
	}
	
	public void setCarno(java.lang.String carno) {
		set("carno", carno);
	}
	
	public java.lang.String getCarno() {
		return getStr("carno");
	}
	
	public void setJingdu(java.lang.String jingdu) {
		set("jingdu", jingdu);
	}
	
	public java.lang.String getJingdu() {
		return getStr("jingdu");
	}
	
	public void setWeidu(java.lang.String weidu) {
		set("weidu", weidu);
	}
	
	public java.lang.String getWeidu() {
		return getStr("weidu");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setBiaoqianlist(java.lang.String biaoqianlist) {
		set("biaoqianlist", biaoqianlist);
	}
	
	public java.lang.String getBiaoqianlist() {
		return getStr("biaoqianlist");
	}
	
	public void setUploadtime(java.lang.String uploadtime) {
		set("uploadtime", uploadtime);
	}
	
	public java.lang.String getUploadtime() {
		return getStr("uploadtime");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setDeviceid(java.lang.String deviceid) {
		set("deviceid", deviceid);
	}
	
	public java.lang.String getDeviceid() {
		return getStr("deviceid");
	}
	
	public void setBiaoqiancount(java.lang.String biaoqiancount) {
		set("biaoqiancount", biaoqiancount);
	}
	
	public java.lang.String getBiaoqiancount() {
		return getStr("biaoqiancount");
	}
	
}

