package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAutoGasFillingWaitQueue<M extends BaseAutoGasFillingWaitQueue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGunNo(java.lang.String gunNo) {
		set("gun_no", gunNo);
	}
	
	public java.lang.String getGunNo() {
		return getStr("gun_no");
	}
	
	public void setLastTradeDate(java.lang.String lastTradeDate) {
		set("last_trade_date", lastTradeDate);
	}
	
	public java.lang.String getLastTradeDate() {
		return getStr("last_trade_date");
	}
	
	public void setLastProcessId(java.lang.String lastProcessId) {
		set("last_process_id", lastProcessId);
	}
	
	public java.lang.String getLastProcessId() {
		return getStr("last_process_id");
	}
	
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}
	
}

