package com.sjzu.edu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}
	
	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}
	
	public java.lang.String getBirthday() {
		return getStr("birthday");
	}
	
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 数据插入时间
	 */
	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 数据插入时间
	 */
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}
	
	/**
	 * 加气站id，或者是公司id
	 */
	public void setCompanyid(java.lang.String companyid) {
		set("companyid", companyid);
	}
	
	/**
	 * 加气站id，或者是公司id
	 */
	public java.lang.String getCompanyid() {
		return getStr("companyid");
	}
	
	/**
	 * 用来控制角色权限的，现在暂时没用。
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 用来控制角色权限的，现在暂时没用。
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}
	
	/**
	 * 用户对应gas_station表内的id
	 */
	public void setStationid(java.lang.Integer stationid) {
		set("stationid", stationid);
	}
	
	/**
	 * 用户对应gas_station表内的id
	 */
	public java.lang.Integer getStationid() {
		return getInt("stationid");
	}
	
}

